### ISSUE TITLE
support more file types

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#100]
## The Issue
I tried opening this content (included screenshot)  and after the download was completed, this is how the screen appeared(please check screen)
### Steps to reproduce
1. In the mobile app, look for the community post that has a broken cup
2. Download and after the download is completed, the screen appears white
3.

### Expected behaviour
It should have opened the content as it does on PC: seems to me like the android app does not seem to support text/html as the desktop app

### Actual behaviour
Instead the screen appears white, and does not include the full video description

## System Configuration
- Device: Note 8 Samsung
- Android version: 8.0.

## Anything Else

https://cdn.discordapp.com/attachments/439055085616496640/441960963302752267/Screenshot_20180504-192359_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/441961042998722571/Screenshot_20180504-192341_LBRY_Browser.jpg

**Comment by akinwale** [comment]
We can try to add support for images and text/html to display in-app.

**Comment by akinwale** [comment]
Added in-app view support for the following content types:
- image/*
- text/*
