### ISSUE TITLE
Overlapping text on newly published video

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-android#1012]
![Screenshot_20200916-134640_LBRY.jpg](https://user-images.githubusercontent.com/16981283/93373453-e1530380-f844-11ea-8a9a-d09ca4554dd4.jpg)

**Comment by kekkyojin** [comment]
LBRY Android app version, @clay53 ?

**Comment by clay53** [comment]
Latest on master 722c829

**Comment by ycohen-dev** [comment]
So, I've looked into this cause I think it is a good first time bug fix.
The problem (I think) is with the logic deciding the visibility of the "Pending" string.
It looks like the code intended to toggle between "Pending" and the publishing time string - never both

ClaimListAdapter.java
`vh.publishTimeView.setVisibility(!isPending ? View.VISIBLE : View.GONE);`
`vh.pendingTextView.setVisibility(isPending && !item.isLoadingPlaceholder() ? View.VISIBLE : View.GONE);`

All good so far - but few lines down below we have the following line:
`Helper.setViewVisibility(vh.publishTimeView, !item.isLoadingPlaceholder() ? View.VISIBLE : View.GONE);`

Now we are ignoring the pending state and just turn on the visibility.
I think that we can delete that line.
The thing that confuses me is the usage of the Helper - it is used here to guard us from applying view methods on a null 
view. 
Why would it be necessary?
We already addressed PublishTimeView without the null guard, is this some kind of concurrency issue - causing the view reference to be null in the middle of onBindViewHolder method?

Anyway , I'll create a PR for the suggested fix soon.

**Comment by ycohen-dev** [comment]
Added PR for the fix
#1026

**Comment by ycohen-dev** [comment]
Hey @clay53 , you can close this issue.

@akinwale fixed it in commit 3d48fa574189c30398cb12bc154530f1e7e38f79

**Comment by tzarebczan** [comment]
hey @ycohen-dev , sorry for not following up earlier, but thanks for all the help on the repo! Can we show you [some appreciation](https://lbry.com/faq/appreciation)?
