### ISSUE TITLE
Display problems on channel page when loaded from HTTPS deep-link

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-android#1014]
### Steps to reproduce
1. Open LBRY Android app
2. Wait for it to fully load wallet balance
3. Click on any open.lbry.com/lbry.tv link on a web browser on the device

### Expected behaviour
When link is for a channel claim, wonderbar should show correct lbry:// instead of the https:// one. If no content had been consumed when clicking the link the bottom section should not appear.

### Actual behaviour
See screenshot. If some content was been consumed when clicking on the link, the bottom bar keeps showing the content, as expected.

## System Configuration
- Device: Pixel on emulator
- Android version: 11
- App version: 0.16.2

## Screenshots

![device-2020-09-21-124657](https://user-images.githubusercontent.com/4984239/93758373-9ea87700-fc08-11ea-9ab2-a922f8edc247.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
