### ISSUE TITLE
APK download and install attempt: "App not installed"

### ISSUE THREAD

**Issue by runvnc** [lbryio/lbry-android#1018]
## The Issue
Can't install APK.
### Steps to reproduce
1. Download from http://build.lbry.io/android/latest.apk
2. Clear warnings and change setting to allow from this source.
3. Click Install

### Expected behaviour
Installation completes

### Actual behaviour
Progress bar moves all the way, but at the end just get message "App not installed"

## System Configuration
- Device: Moto G6
- Android version: 9

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Sorry to hear. Do you have the playstore version installed ? If so, it needs to be removed first (make sure you have wallet sync on).

Maybe you can try the fdroid version so it supports updates, or this 32 bit: https://build.lbry.io/android/build-1113_commit-a5d4eda/browser-0.16.6-release__arm.apk

**Comment by runvnc** [comment]
Assuming Play store version is called LBRY then no it's not installed.  I tried clearing space. I have more than 3 GB free now and it does the same thing.  I will search to find out what the fdroid version is.

**Comment by runvnc** [comment]
I can't find the "wallet sync" setting to check it.

**Comment by runvnc** [comment]
Okay so I installed F-droid from https://f-droid.org/

F-droid says app tracks location and also is incompatible.  I changed settings to allow incompatible.  At the end the problem is the same  "App not installed".

My phone is a piece of crap and freezes a lot but I don't know if I've ever seen "App not installed" before and don't usually see incompatible.

So I don't know for sure if my phone is just too old or if Google is blocking this somehow or what.

**Comment by kekkyojin** [comment]
@runvnc ====> https://github.com/lbryio/lbry-fdroid/issues/3#issuecomment-699492038

A fix for this problem is underway.

**Comment by runvnc** [comment]
I have a Moto G6

**Comment by tzarebczan** [comment]
This should now work on Fdroid for 32bit devices.
