### ISSUE TITLE
First run permissions requests.

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#102]
### Steps to reproduce
1. Install latest apk
2. Run app with all fresh data.
3. Accept permissions

### Expected behaviour
When specific permissions in an app are requested the user should be notified why the app requires said permission.  Then the app should trigger the android function to request said permission.  Once this process is done, it should go back to the app and test if the permission was given.  If it's been given progress onward or if it's not been given ask again or offer to close the app.

Also, when I'm asked for Photo and Media access in some cases before I have the chance to answer the permission for "draw over app" access is requested, and then I don't believe I'm asked for photo and media access again. However, the app seems to work fine afterwards. **This was not verifiable on the Nexus6p**

Finally, if you need access in the future for if we allow Android users to upload anything directly from their devices.  It should call the check for the permission just in case the person disabled the permission after it was installed.  ( clearly, this part isn't relevant just yet )

### Actual behaviour
The App requests with no pretext for Photo and Media(Storage) access and closes the app instantly if the user says no with a notification that seemed a bit long for the amount of time it stayed on the screen for.

If you accept the Photos and Media permission it then throws you into the Draw over App permission enable setting in Android with no pretext either. Not accepting the draw over app permission seems to not be required and if I just back out it tries to launch normally anyways.

## System Configuration
- Device: OnePlus3t
- Android version: 8.0.0
- OS Version: OxyegenOS Version 5.0.1
## Anything Else
I know that the draw over app permission is only intended for the alpha development stage.

**Comment by akinwale** [comment]
If storage permission is denied, the notification actually shows for 3.5 seconds explaining that the storage permission is required. The overlay permission is currently shown because the app is in alpha and this is required for debugging purposes. This will not be requested for in beta builds.
