### ISSUE TITLE
Untranslatable string in wallet activity limiting translation efforts 

### ISSUE THREAD

**Issue by ycohen-dev** [lbryio/lbry-android#1024]
## The Issue
String "Credits" in wallet activity cannot be translated.
This String is being used in the wallet activity alongside the current balance the user have.
This string key ("lbc") is marked untranslatable - this prevents translators to correctly adapt it to their language.
It is especially problematic with RTL languages - it gives the feeling of an incomplete translation of the app.

### Steps to reproduce
1. Open LBRY app
2. Open the navigation drawer
3. Click Wallet
4. In the "Balance" box , under "You currently have" string,
you can find the balance - it is formatted as (amount)("Credits")
"Credits" remain untranslated across all available languages although it can be translated.

### Expected behaviour
 "Credits" is translated correctly in each language

### Actual behaviour
"Credits" remain untranslated across all available languages

## System Configuration
- Device: Xiaomi Mi 9
- Android version: 10 (API 29)

## Screenshots
![2020_10_10_121823](https://user-images.githubusercontent.com/33922624/95635624-928c3880-0a95-11eb-9364-7993a46c29e3.png)

**Comment by kauffj** [comment]
@akinwale will this become the credits icon?

**Comment by kauffj** [comment]
<div dir="rtl">תודה @ycohen-dev</div>

**Comment by ycohen-dev** [comment]
@kauffj 
Well... I'm not sure if that was google translate or my suspicion about the Kauffman surname turned out to be true

anyway, It's nice to get a reply from the man himself :)

**Comment by akinwale** [comment]
@kauffj Yes. I previously replaced all occurrences of the LBC suffix with just "Credits".

**Comment by akinwale** [comment]
"Credits" is now a translatable string. The credits icon also replaces the "credits" text in the wallet balance card.
