### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by LaroTayoGaming** [lbryio/lbry-android#1028]
## The Issue
I've want to do the signin and for some reasons, I can't login via the LBRY app itself because I've clicked the remember me checkbox.

### Steps to reproduce
1. Sign in to LBRY Android
2. Login with your email
3. Check your email and click the link, and opened it via the LBRY app

### Expected behaviour
I've expected to have a confirming account and the wallet password after.

### Actual behaviour
I've seen nothing instead. I've redirected to the homepage except of that.

## System Configuration
- Device: Realme C3
- Android version: 10

## Screenshots

![Screenshot_2020-10-10-23-44-35-25](https://user-images.githubusercontent.com/24932514/95659340-ed379a00-0b52-11eb-841c-4cce2d985110.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
Open LBRY app settings on your Android device, it should be under Settings/Applications. Or try long-pressing the app in your Recents List.

Then click on "remove defaults"

**Comment by ycohen-dev** [comment]
@kekkyojin 
It's not an unreasonable assumption that the login verification link can be handled in LBRY app itself.
Maybe we should consider changing this issue to a feature request.

@LaroTayoGaming 
Don't open the link inside the verification email with the LBRY app - open it with a browser.

**Comment by tzarebczan** [comment]
We used to do this but won't be handling that anymore. It's done via a separate login. 

And it looks like you are already logged in.
