### ISSUE TITLE
Switching to PiP mode while displaying notifications doesn't display video

### ISSUE THREAD

**Issue by ycohen-dev** [lbryio/lbry-android#1034]
## The Issue
When viewing a video on the app, while having the "Enable background playback" toggle on,
and then pressing the bell to view notification, and then pressing the home button
PiP window shows cropped version of the notifications view

### Steps to reproduce
1. Open LBRY app
2. Open the navigation drawer
3. Choose Settings
4. Ensure that the "Enable background playback" toggle is on
5. Go back to "Following"
6. Watch a random video
7. Press the bell to view notifications
8. Press the home button to trigger Picture-In-Picture mode

### Expected behaviour
PiP window should contain the video being played

### Actual behaviour
PiP window shows cropped version of notifications view

## System Configuration
- Device: Xiaomi MI9
- Android version: Android 10 (API 29)

## Screenshots
![lbry_pip](https://user-images.githubusercontent.com/33922624/96184118-aaa20300-0f40-11eb-9f75-135967ba097e.gif)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing! I've definitely seen this before... and I think it even happens with the Youtube App haha

**Comment by ycohen-dev** [comment]
Allready PR'd it. Really simple fix

**Comment by ycohen-dev** [comment]
Sorry for the messy storyline - newest PR request contain 1 single commit
