### ISSUE TITLE
Download Notification shows 100% downloaded but still has progress bar.

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#104]
### Steps to reproduce
1. Start a video download that doesn't play right away.
2. Wait for the download to complete.
3. Completed download notification doesn't change or take you directly to the video.

### Expected behaviour

1. I would imagine the notification should take you directly to the media when clicked.
2. The notification should update to say something similar to "Your video file [FileName] is completed tap here to play." 

### Actual behaviour

1. Currently, it just brings you back to the LBRY mobile app if you're not in the app.  Also when in the app it just goes back to the app as well and not the media that you downloaded.
2. Instead, the notification shows a download progress bar and that the download is at 100% and some stats. https://imgur.com/a/3rqmCGv When clicked the app is taken back to whatever was its last state, and if the app was closed it just takes you to the dashboard and not the video.

## System Configuration
- Device: OnePlus3T
- Android version: 8.0.0
### Verified on
- Device: Nexus6P
- Android Version: 8.1.0

## Screenshots
One plus 3t Android 8.0.0 Lbry.io app from Google drive ![https://imgur.com/a/3rqmCGv](https://i.imgur.com/mIqJbw2.jpg)

**Comment by akinwale** [comment]
Fixed.
