### ISSUE TITLE
Add a preference to stop sending data to Segment.io

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-android#1047]
## The Issue
LBRY FDroid requires any sending of tracking data to be disabled by default. Not allowing it makes the app show a warning on its listing on F-Droid site and F-Droid app.

### Expected behaviour
A Preference should be added to the app so user could enable or disable it if it is its desire.

### Actual behaviour
App sends data and it is not configurable

## Anything Else

lbry-android-sdk allows Java code to set lbry-sdk to not send any tracking event to segment.io. In order to fix this, I plan to:

* Add a new preference modelled from LBRY Desktop. This includes warning user about rewards been not available to users which aren't sending that data
* Set the preference on/off by default on lbry-android/lbry-fdroid respectively.
* Add a call on MainActivity to 'settings-set' SDK method according to the preference value
* Add a call on MainActivity to that same method whenever the preference value changes
* Once this is merged, request F-Droid to remove the warning on the LBRY listing

This new feature is not related to #72. That one is about the app code, while this new one is about lbry-sdk, which uses Segment tracking service.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
@akinwale what data is sent directly to segment? Is it used? I can't think of a report...

**Comment by akinwale** [comment]
I'm not sure what's being sent specifically, but I believe https://github.com/lbryio/lbry-sdk/blob/master/lbry/extras/daemon/analytics.py holds the key to this.

**Comment by kekkyojin** [comment]
Fixed after LBRY Android SDK 0.85.2 on lbry-fdroid repository. It sets the setting to not send it by default at the SDK level.
