### ISSUE TITLE
URL encode error on share link : using non authorized characters ! And fail opening well formatted URL.

### ISSUE THREAD

**Issue by oopen** [lbryio/lbry-android#1052]
# Share link not encoded

### Steps to reproduce
1. open a video on the android app
2. click on share button
3. the link is not url encoded, on fail to open on browser, sms app...

### Expected behavior
The link should be URL encoded

### Actual behavior
the link is not encoded and contain not allowed characters, like utf-8 icon, ! : ...

# Not open well encoded links

### Steps to reproduce
1. open a encoded link with lbry app
2. the content is not find, because the link is not decoded

### Expected behavior
link decode, open content

### Actual behavior
link not decoded, content not found

**Comment by kekkyojin** [comment]
Is it happening on any video or on a few of them?

**Comment by tzarebczan** [comment]
Can you give us an example of a URL that's happening on? We may need to encode the claim name on the share portion. We just added that on the lbry.tv/odysee side.

**Comment by oopen** [comment]
On android app: I click Share button, like generated : 

[https://lbry.tv/La-Peur,-Nos-Attentats,-c'est-VOTRE-Sécurité!-Les-Guignols#6](https://lbry.tv/La-Peur,-Nos-Attentats,-c'est-VOTRE-Sécurité!-Les-Guignols#6)

As you can see, the link contain not url allowed caraters like : `,` `!`, `é` `'`
there characters must be urlencoded.

Secondly, if I urlencode the link to :

[https://lbry.tv/La-Peur%2C-Nos-Attentats%2C-c%27est-VOTRE-Se%CC%81curite%CC%81%21-Les-Guignols#6](https://lbry.tv/La-Peur%2C-Nos-Attentats%2C-c%27est-VOTRE-Se%CC%81curite%CC%81%21-Les-Guignols#6)

This link can't be open by android app, 
but mobiles & desktop browsers can.

So link is not urldecoded on android app.
