### ISSUE TITLE
Floating balance may obscure text throughout app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#1054]
Example: https://www.reddit.com/r/lbry/comments/jxe76n/lbc_balance_blocks_last_comments_on_some_videos/

**Comment by kekkyojin** [comment]
I think the floating button is not exactly the best UI for this. It appears like a FAB, which it is normally used for the very often usual action on an Android activity, like the Play button on a music player or the Purchase button on a shop detail page.

The floating wallet button is instead opening a new fragment with either the wallet ot the reward list. It is opening a new view where user could then act, not allowing user to act directly on the current view.

Right now, LBRY Android shows:

- A loading spinner on the splash activity
- Another loading spinner on the wallet floating button
- Wallet and available balances on the navigation drawer

From here, I would suggest:

- Add an activity transition which shares the splash spinner and the floating button spinner, using the Android API Level 21 animation API. Then,
- Animate reward balance into the wallet balance spinner, making it disappear. Then,
- After a few seconds, animate the spinner to the top bar, along the wonderbar, animating -decreasing size- wonderbar to make space so the spinner fits
- When LBRY daemon is ready, animate the spinner into the navigation drawer icon, indicating user where balances could be found

First two animations could be skipped, but current users would be a little bit confused if they are no longer seeing the balances and they are seeing a new spinner over there, likely no relating both changes without the UI hinting it. Over time, these first two animation could be removed and directly animate the splash spinner to the spinner along the wonderbar.

To do all of this, maybe ViewOverlay Android API could be used.
