### ISSUE TITLE
Comment input boxes are the wrong color for dark themes.

### ISSUE THREAD

**Issue by styromaniac** [lbryio/lbry-android#1060]
I can't see any text that I'm entering. This limits my engagement with others. I don't want to typo or have swype enter the wrong word and make me regret writing comments.

**Comment by tzarebczan** [comment]
What app or browser are you using? Any other theming in your browser? Seems to work fine in Brave, Chrome and Firefox.

Please double check and reopen with screenshots.

**Comment by styromaniac** [comment]
LBRY F-Droid

**Comment by styromaniac** [comment]
Oh. I think it's when I don't have enough LBRY credit to comment. One problem is that the app says "Post for 1 credit," which isn't clear if that's a give or take from your wallet balance.

It should say something like "Post for 1 credit cost."

Yeah, I was confused by it.
