### ISSUE TITLE
Channels seem empty..even when there are not

### ISSUE THREAD

**Issue by cavey65** [lbryio/lbry-android#107]
## The Issue
Cannot browse channels in the app

### Steps to reproduce
1. Search therubinreport
2. Open the channel in the results
3. Empty claim or metadata info

### Expected behaviour
would expect to see all the posts in a channel

### Actual behaviour
it says it is empty

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Fixed. Fetching additional claims for multi-page channels will be added later.
