### ISSUE TITLE
Unable to log in...can't use password, and mailed link won't open in app

### ISSUE THREAD

**Issue by salfter** [lbryio/lbry-android#1072]
## The Issue

I can't log in to LBRY with the Android app.

### Steps to reproduce
1. Tap "sign in."  Fill in email address and submit.
2. Tap the link that arrives in email (there's no option to provide a password).
3. The link will only be handed off to a web browser.  The LBRY app doesn't appear as an option.

### Expected behavior

Either the link is set to open in the LBRY app or (better) password login is enabled.

### Actual behavior

Can't log in.

## System Configuration
- Device: OnePlus 7 Pro
- Android version: 10

## Screenshots

![Screenshot_20201215-080232](https://user-images.githubusercontent.com/1380958/102240146-64b7db80-3eac-11eb-8b74-9187aacd9923.jpg)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kekkyojin** [comment]
This is the expected behavior. That link should be opened on a browser and not on the app.

**Comment by salfter** [comment]
Tried again...and it looks like this time it worked, even with the link opened in Chrome.  Never mind, then. :-)
