### ISSUE TITLE
Ability to revoke support

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-android#1073]
## The Issue
Add the ability to revoke support from the wallet similar to the desktop app. This will make it so users can more fully manage their channel from their phone.

## Screenshots

With the same kind of functionality as this:
![image](https://user-images.githubusercontent.com/16981283/102282574-cdc83f00-3efe-11eb-9a9c-82d5fc2af2dd.png)

### Acceptance Criteria
1. Ability to revoke support is added

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Will be handled under https://github.com/lbryio/lbry-android/issues/1141
