### ISSUE TITLE
'Subscribe and Earn' Notification can Appear Multiple Times

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1075]
**DESCRIPTION:**

The notification entitled 'Subscribe and Earn' can appear multiple times in the feed if a new user Subscribes, Unsubscribes and restarts the app.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0
2) Select 1 Channel to Subscribe to
3) View that Channel and Unsubscribe
4) Restart the App
5) Repeat Steps 2 through 4
6) View notification list

**Results:** Notification appears twice (and can appear an unlimited number of times)

**Expected:** Notification only appears once

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**MEDIA:**

![LBRY_16 11_DuplicateNotification](https://user-images.githubusercontent.com/30788194/102551082-27a24380-407c-11eb-838d-3e93c89aaa46.gif)

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Thanks for the issue but this is not a common flow so I don't think we'll be fixing it.

**Comment by cahlenlee** [comment]
Is this even a valid notification?  I don't see any reward for this in my reward history.  Could be advertising a reward that doesn't exist.

**Comment by tzarebczan** [comment]
Once you verify an account, there are rewards for subscribing.
