### ISSUE TITLE
Text Color in Email Field Changes when Rotating Phone

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1077]
**DESCRIPTION:**

Rotating the phone while on the Log In screen causing the text in the email field to change color.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0 in Portrait
2) Select 'Sign In'
3) Note color of text in email field
4) Rotate phone to Landscape

**Results:** Text color changes

**Expected:** Text color remains the same

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**MEDIA:**

![LBRY_16 11_EmailColor](https://user-images.githubusercontent.com/30788194/102551707-2faeb300-407d-11eb-963c-accba90879ce.gif)

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
I'm seeing while in both cases here.

**Comment by tzarebczan** [comment]
I think this is fairly minor and not common, so we won't be fixing at this time.
