### ISSUE TITLE
Background media controls

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#108]
### Steps to reproduce
1. Play a video or sound file
2. Press home button
3. Still, enjoy your media but wish to control it without returning to the app.

### Expected behaviour
If the app is minimized or put into the background consider creating a few media controls outside of the app.

### Actual behaviour
Currently, it just plays the sound in the background until you either return to the app to stop playback or close the app via the app switcher.

## System Configuration
- Device: OnePlus3T
- Android version: 8.0.0

## Anything Else
Thumbnails could be used in a fancy background like what is shown in Čľëmĕņťs screenshot.

## Screenshots
![lock screen controls](https://cdn.discordapp.com/attachments/303400498155749377/443073323828510740/Screenshot_20180507-113338_01.jpg)
Notification controls screenshot courtessy of Čľëmĕņť - Today at 11:14 AM in #lbry-android
![Notification controls courtessy of Čľëmĕņť - Today at 11:14 AM](https://cdn.discordapp.com/attachments/439055085616496640/443068203632164865/20180507_204349.jpg)

**Comment by vv181** [comment]
https://github.com/tanguyantoine/react-native-music-control
The modules fit with the issue.
