### ISSUE TITLE
Debug Error Appears when Tapping Resend Repeatedly on Sign In Screen

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1080]
**DESCRIPTION:**

Tapping the 'Resend' button many times repeatedly eventually results in an error appearing which the user is unable to understand.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0
2) Choose 'Sign In'
3) Enter an email address and submit
4) Tap the 'Resend' button repeatedly many times

**Results:** Debug Error

**Expected:** Readable Error or No Error

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**MEDIA:**

![LBRY_16 11_ResendError](https://user-images.githubusercontent.com/30788194/102552518-9a142300-407e-11eb-9313-e20ea8bcc23a.gif)

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
This is a rate limitation feature on our APIs and a known issue there.

**Comment by cahlenlee** [comment]
Shouldn't something be done about the non-nonsensical user-facing error?

**Comment by tzarebczan** [comment]
1) No one is going to do that. 2) It's not an issue on this repo, it's already filed in our API repo. 

Thanks again!
