### ISSUE TITLE
Application Restarts when Closing Sign In Screen after Orientation Change

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1081]
**DESCRIPTION:**

Closing the Sign In screen after rotating the phone's orientation results in the app restarting.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0 in Portrait orientation
2) Go to 'Sign In'
3) Rotate to Landscape orientation
4) Rotate back to Portrait orientation
5) Tap the X in upper right to close screen

**Results:** App restarts

**Expected:** User is returned to previous screen

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**MEDIA:**

![LBRY_16 11_RestartEmail](https://user-images.githubusercontent.com/30788194/102552790-01ca6e00-407f-11eb-9aae-36b247e6d63d.gif)

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Thanks for the issue. I don't think this is a common user flow and not a big deal to fix at this time.
