### ISSUE TITLE
Quickly Selecting and Deselecting Channels Causes them to Disappear and Reappear in Feed

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1084]
**DESCRIPTION:**

On the initial screen where you select channels to subscribe to, if you quickly select several of them, and then quickly deselect all but one of them, the channels will appear and disappear multiple times when you proceed to the feed.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0
2) Quickly select 6 channels to subscribe to
3) Quickly deselect 5 channels
4) Tap '4 Remaining' to proceed to feed
5) View subscribed channels list

**Results:** Channels disappear, reappear and disappear again

**Expected:** Only subscribed channels are listed

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**MEDIA:**

![LBRY_16 11_SubscribeSpam](https://user-images.githubusercontent.com/30788194/102553826-b9ac4b00-4080-11eb-81cb-f2626ddaaef4.gif)

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Thanks for filing, but I don't think this a typical use case and that we'll fix it anytime soon. As you add them, it adds them to the searches and they happen in the background. So it's just queuing up the tasks and then fixes itself. As long as the result is correct in the end, then it's all good.
