### ISSUE TITLE
Option to include a debugging information watermark overlay in testing version.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-android#109]
### Steps to reproduce
1. Want to create a ticket with screenshots.
2. Create screenshots and upload them however you choose.
3. Have to explain the version of the app and android details etc.

### Expected behaviour
Enable better and higher quality issue reporting by providing an option to enable a watermark/overlay which includes debugging information on the different views.  This behaviour could consist of things like device, android version, os details, and other system information like resource usage etc.

### Actual behaviour
Currently, you have to know a bunch of things to help feed data to developers via issues.  They seem trivial to us, but if the intended audience is the average user, it should be easy for the average user to explain from their perspective what appears ambiguous or problematic to them.

## System Configuration
- Device: Any
- Android version: Any

## Anything Else
This enhancement may be makework but since there is no real downside aside from dev time to create a grey watermark or debug overlay that can be enabled by testers so when screenshots are submitted it would be easier to get more in-depth relevant information.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
will not be able to do this right now, will revisit

**Comment by chamunks** [comment]
Sure the only reason I really submitted it was for in early testing it would make it easier to go from someone submitting a screenshot to getting developer help & feedback.
