### ISSUE TITLE
Wallet Balances are Incorrect Once Fully Loaded

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1098]
**DESCRIPTION:**

Wallet balances are incorrect once fully synced on Android.  Also, two Android devices launched at the same time come to different final balances.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0 and Android 10
2) Login to an existing account 
3) Once daemon is running, go to Wallet
4) Wait and allow Wallet balances to stop changing (may take a long time)
5) Compare the balances with Android 8 and 10 versions, and then with lbry.tv balances

**Results:** Android balances are different, and both are wrong

**Expected:** Android balances match lbry.tv balances

-----

**MEDIA**

![Android8](https://user-images.githubusercontent.com/30788194/103103972-e4972180-45e1-11eb-944f-15dddda1945a.jpg)
![Android10](https://user-images.githubusercontent.com/30788194/103103975-e82aa880-45e1-11eb-85dd-0782872858cd.jpg)
![Linux](https://user-images.githubusercontent.com/30788194/103103977-ebbe2f80-45e1-11eb-8e4e-32aaf26c82a2.png)

-----

**ENVIRONMENT:**

- LG V20 Android 8.1.0
- Galaxy A01 Android 10
- LBRY 0.16.11

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
This is fixed in the latest sdk releases and will be updated on Android soon.
