### ISSUE TITLE
Large Wallets Take Over an Hour to Sync

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1099]
**DESCRIPTION:**

I have an account with a large number of videos and transactions, and it takes 70min for the Android app to sync everything.  During that process my wallet balances are constantly changing and I am unable to make transactions.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.11 on Android 8.1.0
2) Log in to an account with a large history
3) Wait for wallet sync to finish

**Results:** Takes over an hour 

**Expected:** Takes a short period of time

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
This is an issue on the sdk and there's some improvements we've made, but this will always be the case with large histories and having many reinstalls (each creates a new account). Resync is only required when we make major changes or you reinstall. 

In the future, there will be a light mode that uses the lbry.tv synced wallet.
