### ISSUE TITLE
Extreme stuttering of audio when screen is turned off

### ISSUE THREAD

**Issue by pakar** [lbryio/lbry-android#1101]
## The Issue
Whenever the screen is turned off while a video is playing causes extreme stuttering of the audio. Playback in background mode, while screen is on, works perfectly.

### Steps to reproduce
1. Start payback of video 
2. Lock screen

### Expected behaviour
Audio to work without stuttering when screen is off.

### Actual behaviour
Continuous stuttering during playback as soon as the screen is locked.

## System Configuration
- Device: OnePlus 5
- Android version: 10

## Anything Else
- It does not matter if the app is in foreground or minimized (playback overlay-window). The common denominator seems to be when locking the screen.
- As soon as screen turned on playback continues normally.
- I have tried all the android settings (optimized/on/off) for power-saving that you can set on the app - same behavour.
- I have tried with the in-app settings of "Keep the LBRY service running in the background" on and off.
- Issue appears with and without any bluetooth devices connected (bluetooth turned on/off on phone)
- Part of the LBRY beta program so running latest available version listed here on github.
- Behaves the same if downloading the content before playback 
- Sometimes the playback will pause after leaving the stuttering playback running for a while.

 
Have worked with video-playback on embedded (non-android) devices previously so the following may or may not be relevant, but might give some hints. 
** It sounds extremely similar to a buffer underrun where the decoder is just on the edge of not getting enough data.
** It could *possibly* be related to audio-video sync. If the playback is synced on video the audio playback may run in to issues if the video-decoder is turned off for power-saving, like when the screen is turned off.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by pakar** [comment]
Another observed behavior. I have managed to minimize LBRY a few times during playback without getting the mini-playback overlay-window and the same choppy audio is then experienced.. Ie this is with the screen on but without a visible video-window.

**Comment by pakar** [comment]
Sounds similar to #981

**Comment by pakar** [comment]
Started with a bit of research and found this.
https://github.com/sedubois/ExoPlayer/commit/9f963a9f01a3c38468aa70f1b3d3c0749c3e5d19

Have done a ExoPlayer upgrade to 2.12.2 (PR on the way) and trying to get my head around how the player-management works in this app. Long time since i did any android development so any hints would be appreciated.

**Comment by tzarebczan** [comment]
Looks like that was merged in - is the problem gone now? 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the PR?

**Comment by pakar** [comment]
Issue is not resolved. First PR was only to update the player. Fixing the issue is a bit more involved and will require a rewrite of at least parts of the player code and have not found any time for it yet.
