### ISSUE TITLE
History Menu does not Display Viewed Videos from Other Devices

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#1109]
**DESCRIPTION:**

The history menu displays the name of the device which each video was watched on.  This indicates there is an intention to display videos watched on other devices here.  However, only videos watched on the present device are shown.

-----

**REPRO STEPS:**
1) Open LBRY 0.16.11 on Android 8.1.0 w/ a Synced Account and Daemon Running on 2 devices
2) Watch different videos on each device
3) On one device, go to Library > History

**Results:** Only videos watched by current device are listed

**Expected:** All videos watched by account are listed, or this menu does not show device name

-----

**MEDIA**

![HistoryDevice1](https://user-images.githubusercontent.com/30788194/103304607-4c74b000-49c6-11eb-8927-bdea6a905ef0.png)
![HistoryDevice2](https://user-images.githubusercontent.com/30788194/103304615-51d1fa80-49c6-11eb-8e1f-b14c0aaab502.jpg)

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.11

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
There is no sync feature for this yet, it's only local for now.
