### ISSUE TITLE
Viewing All the Recent Transactions Not Working

### ISSUE THREAD

**Issue by vv181** [lbryio/lbry-android#111]
## **The Issue**

Clicking 'view all' in the recent transaction should show all the transaction instead it shows an error.

## ** Steps to reproduce**

1. Open navigation bar
2. Click Wallet
3. Click View All at the Recent Transactions section.

## **Expected behavior**

It should show all the transactions.

**## Actual behavior**

The error pop out shows as in the below screenshot.

## **System Configuration**

    Device: Xiaomi MI A1
    Android version: 8.1

## **Anything Else**

If the user has made a transaction, clicking the 'view all' works fine.

## **Screenshots**
https://cdn.discordapp.com/attachments/439055085616496640/442412615734657035/Screenshot_LBRY_Browser_20180506-024424.png

**Comment by akinwale** [comment]
Fixed.
