### ISSUE TITLE
 The contents searching results always shows the [future] contents on top of the list

### ISSUE THREAD

**Issue by markchang2006** [lbryio/lbry-android#1124]
## The Issue: The contents searching results always shows the **[future]** contents on top of the list

The contents searching results always shows the **[future]** contents on top of the lists when search
 all contents among all channels for options of **[latest]** and **[trending classics]**. 

I think it's harmful for the LBRY protocol if the problematic contents with future publishing schedule are listed on top always appeal to the most users.

![Search_All_Latest_Published_Scope_all](https://user-images.githubusercontent.com/15308926/105608638-17018d80-5ddf-11eb-9356-39216b3eaabc.jpg)
![Search_all_Trend_Up_Scope_All](https://user-images.githubusercontent.com/15308926/105608648-284a9a00-5ddf-11eb-8eef-7fef9bdeea4d.jpg)

It looks normal when search all content among all channel for option of **[top]**.
![Search_All_Top_Content_Scope_All](https://user-images.githubusercontent.com/15308926/105608670-58923880-5ddf-11eb-9352-1862f3ae3a6c.jpg)

### Steps to reproduce
1. Press [All Content] button (the 3rd button) on main menue.
2 Select option 1 [Trending Classics] and option 2 [All Channels], or
3.Select option 1 [Latest] and option 2 [All Channels]

You can reproduce the issues reported here by executing the above steps.

### Expected behaviour
Tell us what should happen

1. All contents should be published after the time when user searches content.
2. And all the listed contents should be listed orderly by the original definition.

PS.
1.>The app. should be able to figure out the incorrect publish schedule, especially for those contents which are published [in the future].
2.>It's better to think about how to treat those contents which are benefited from the software bug, since it's unfair. however.

### Actual behaviour
Tell us what happens instead
It's reported in the section of [## The Issue:] already.

## System Configuration

- Device: **_Huawei_LYA-L29 GPU Rurbo**
- Android version: **9 with EMUI Ver.9.1.0**
-CPU: **Huawei Kirin 980**

## Anything Else

The page of [about LBRY.tv App.]:
![Page of About LBRY](https://user-images.githubusercontent.com/15308926/105608710-92fbd580-5ddf-11eb-82bf-11cb6b5c5a62.jpg)

Information about my mobile phone:
![Information_about_my_mobile_phone](https://user-images.githubusercontent.com/15308926/105608837-5086c880-5de0-11eb-8bd6-bf753b33db1d.jpg)

## Screenshots

This is the screenshot when I searches the content without any specific keyword:
![Main_Manue](https://user-images.githubusercontent.com/15308926/105608885-a78c9d80-5de0-11eb-9968-1c79b92b2029.jpg)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
The plan is to hide any future date content, this will be done at the protocol level.

**Comment by markchang2006** [comment]
Thanks for your prompt response!

Best Regards,
築韻空間美學工坊
張世忠(Mark Chang)
0939-061556
竹北市福興路1028巷1號(來訪時請先預約,以免向隅.感恩!)
https://www.twdreamspace.com/


Thomas Zarebczan <notifications@github.com> 於 2021年1月25日 週一 上午8:51寫道：
