### ISSUE TITLE
Shared link preview shows only channel name - Replace # with : in share URLs

### ISSUE THREAD

**Issue by stevie86** [lbryio/lbry-android#1126]
Hi! Thanks for your great work on this app and the lbry network. Recently, I shared a video and checked the preview of the link. It shows the channel name but not the video title. Can you please add an option to decide what the user would like the preview to show?
Thank you very much!
Keep up the good work!
Best regards Steve

**Comment by tzarebczan** [comment]
Can you share a sample of the link? I think it's a bug with the format of the link we're adding.

**Comment by stevie86** [comment]
For example this one https://lbry.tv/@Kessel_Buntes_TV#e/es-ist-eine-l-ge-punkt-preradovic-mit#6

**Comment by tzarebczan** [comment]
Thank you, this is a bug with the urls themselves. You can try replacing # with : manually to make it work for now, we'll need to fix this.

**Comment by stevie86** [comment]
Thanks a lot. Also link preview doesn't seem to work in WhatsApp.

**Comment by stevie86** [comment]
Also this workaround doesn't show correct results. See https://www.sp.sknetworx.at/privatenextcloud/index.php/s/TCYWa8yJ7JbRL7C

**Comment by stevie86** [comment]
The original Link https://lbry.tv/@KulturstudioTV#c/TROJANER#6

**Comment by stevie86** [comment]
Hi! Can you please show me what the link should look like?
Thanks!
Mit freundlichen Grüßen / Best Regards

Stefan Pirker


Am Mo., 8. Feb. 2021 um 19:47 Uhr schrieb Thomas Zarebczan <
notifications@github.com>:
