### ISSUE TITLE
Lbry app crashes by lacking WAKE_LOCK permission

### ISSUE THREAD

**Issue by waltercool** [lbryio/lbry-android#1129]
## The Issue

App crashes trying to play a video. It used to work 2 releases ago, but an update make it crash.

### Steps to reproduce
1. Open app
2. Play a video
3. See crash

### Expected behaviour
Should work

### Actual behaviour
It crashes

## System Configuration
- Device: Galaxy S10, Samsung S7+
- Android version: LineageOS 10, Android 11

## Anything Else

App from F-Droid, on both previously mentioned devices.

Stacktrace:

02-05 23:39:19.679 10524 10524 E AndroidRuntime: Process: io.lbry.browser, PID: 10524
02-05 23:39:19.679 10524 10524 E AndroidRuntime: java.lang.SecurityException: Neither user 10226 nor current process has android.permission.WAKE_LOCK.
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2071)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2039)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1987)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:810)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2221)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2187)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.WakeLockManager.updateWakeLock(WakeLockManager.java:96)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.WakeLockManager.setStayAwake(WakeLockManager.java:83)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.SimpleExoPlayer.updateWakeAndWifiLock(SimpleExoPlayer.java:2077)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.SimpleExoPlayer.access$4700(SimpleExoPlayer.java:75)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onPlaybackStateChanged(SimpleExoPlayer.java:2407)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$7$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:1447)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$tUn7tXLH0gigHS24TehPEnTXTJ0.invokeListener(Unknown Source:2)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1496)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1445)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1326)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:954)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1427)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.playMedia(FileViewFragment.java:1760)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.handleMainActionForClaim(FileViewFragment.java:1982)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.onMainActionButtonClicked(FileViewFragment.java:1871)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.renderClaim(FileViewFragment.java:1628)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.checkParams(FileViewFragment.java:466)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at io.lbry.browser.ui.findcontent.FileViewFragment.onResume(FileViewFragment.java:733)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
02-05 23:39:19.679 10524 10524 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.app.ContextImpl.enforce(ContextImpl.java:1896)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4485)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:373)
02-05 23:39:19.679 10524 10524 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1021

## Screenshots
It crashes, doesn't worth.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by amrsoll** [comment]
Issue happens for me too on /e/ , lbry updated from their 'apps' manager and version displayed is 8.0

**Comment by waltercool** [comment]
Oh right, I forgot to mention my version, which it's 0.16.14

**Comment by TransientResponse** [comment]
Same issue here, 0.6.13 and 0.6.14 crash on OnePlus 7Pro with Android 10. Downgraded to 0.6.12 on F-Droid.

**Comment by waltercool** [comment]
Duplicated of https://github.com/lbryio/lbry-fdroid/issues/11

Seems like Lbry uses an exclusive repository for F-Droid.

Devs, I would personally suggest to use flavors instead of two projects. You can make one flavor to use Google Play Services and all the code related to it, and another flavor for F-Droid.

**Comment by tzarebczan** [comment]
This is a known bug previously filed and an Fdroid update is in progress.
