### ISSUE TITLE
Search Results Not Clearing After Clearing Search

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#113]
## The Issue
Search Results Not Clearing After Clearing Search, the android app search is in such a way that, each keyword brings up options without needing to press enter, these options are not just the content titles but the contents themselves.
### Steps to reproduce
1. Search anything like "cat"
2. Click the X on the right side of the search
3. The search bar closes, click on the search again and your results will be there

### Expected behaviour
It could mimic the Desktop app, where the search shows the titles of the contents rather than the contents it self at first and once the title is selected, the related contents can show up. if the android app is going to show the actual contents as search results it's good, but when the search bar is cleared, the results should be cleared as well. 

### Actual behaviour
what happens instead is that when the search bar is cleared, the search results remain

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0

## Anything Else

https://cdn.discordapp.com/attachments/439055085616496640/443614116599562250/Screenshot_20180509-085320_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/443614116599562251/Screenshot_20180509-085338_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Fixed.
