### ISSUE TITLE
notification bugs and improvements

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#1142]
bugs:
- [x] clicking on a notification (new content / comment) doesn't take you to the content/comment most of the time.
- [x] pass is_app_readable param to notification list (to support comment replies)
- [x] clicking notification and then clicking related video takes you back to notifcation page (lbry://bug.ae0e4bdad7b5f67141743366026d2ea5#f)
 
improvements:
- [ ] show channel thumbnail of commenter/replies
- [ ] show thumbnail of content

I'm working on a PR to add this right into all notification metadata so we don't have to resolve it.

**Comment by kekkyojin** [comment]
For the bug about "notification not working most of the times", when testing it before MR 1175 merging and after merging it, I saw a big improvement. The bug report was lacking some explanation on the steps to be followed to reproduce the problem, but as I said on chat, this was a problem I found long time ago, but stopped from appearing. The cause of this disappearance could be a different flow of action when using notifications.

What I tried today was:

1. Open the LBRY Android app
2. Open notification list
3. Clicking on any notification. In my case, there were only new content notifications
4. Wait for content to at least show, not playing it but seeing the snapshot and related content populated
5. Opening again the notification list directly, from the single item view
6. Clicking on a different notification item

Building without 1175, a new single content appears but notification list reappears quickly before even the snapshot or related content is shown. When building from current master branch, content from the notification is shown, just as expected.

I will still keep testing for this when adding the thumbnail and the channel picture to notifications.
