### ISSUE TITLE
Google-Free phones and Reward confirmation confusing.

### ISSUE THREAD

**Issue by maxlinux2000** [lbryio/lbry-android#1145]
## The Issue
I have a google-free mobile with android 7.1 and therefore I don't have the playstore. (only F-droid and no google service)
I have installed LBRY and clicked on the REWARDS option in the side menu.
It tries to take me to a Discord account (which I can't install) and it gives me this error: ERROR_UNKNOWN_URL_SCHEME

I recommend you let people use other confirmation channels, such as Telegram-foss / Element (Matrix) or simple emails.

### Steps to reproduce
1. use a google-free mobile like lineageOS WITHOUT Gapps
2. install LBRY from FDroid
3. login in your account
4. Pulse REWARDS on left side menu

### Expected behaviour
Have a simple way to confirm i'm not a robot

### Actual behaviour
force me to use discord server an accepting the invetation there is the  ERROR_UNKNOWN_URL_SCHEME error

## System Configuration
- Device: Moto g4+
- Android version: LineageOS 15.1 (android 7.1)

## Anything Else

Telling me that Google-free mobiles ar not supported are not a good answer. LBRY is a youtube alternative... well this mean that you need to be a google service anlternative.

## Screenshots

![Captura de pantalla de 2021-02-20 09-19-08](https://user-images.githubusercontent.com/5683921/108589042-ba9d7980-735c-11eb-8676-224fa47af835.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing, I don't think we'll be changing anything here for now. Our main support is on discord and it sounds like this error is after trying to open from the chat.lbry.com link. 

Related to this would be https://github.com/lbryio/lbry-android/issues/1082 - which should be taken care of if google services not available. 

Phone verification will be added in the future too.
