### ISSUE TITLE
Use coins as likes and subscriptions 

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry-android#1154]
Hey guys,

I've seen on Odysee that there are like/dislike buttons on content and comments and there's currently the subscription function.

Why not use coins to implement those functions to avoid abuse (to a degree) and help creators and not just algorithms by using this functions?

A like and a subscription could just cost 0.2 coins. While a like on content and comments is a tip, a subscription could be just a "support" payment. This way content and comment likes are permanent while a subscription can be canceled which results in less support of a creator naturally. 

This way content where many people have "invested" money in is pushed while if the content isn't interesting for many people it's less "visible". 

While 0.2 coins is a very small amount of money, it would allow people to use likes and subscriptions like before, while abuse, like create thousands of fake accounts would consume quite a lot of money. 

Additionally making good or funny comments on videos would also be rewarded to a degree, while people might be a bit more careful when using likes on negative or mean comments. 

Hope you like the idea! 

Thanks for considering :)

**Comment by tzarebczan** [comment]
This is planned for the future and will happen under a separate issue on the protocol level and then brought into the apps.

**Comment by RubenKelevra** [comment]
@tzarebczan very cool! :)

**Comment by RubenKelevra** [comment]
@tzarebczan is the new monetization the implementation of this?

If so it would still be nice to autotip comments and videos when you "like" them with a fixed amount of lbry coins.

Not sure where the coins for monetization comew from, but I feel like there's some reason to make give likes on comments and videos "weight" in terms of the crypto currency to make sure the author of the content gets something for the like and don't have to rely on advertisements inside his content.
