### ISSUE TITLE
Updating channel does check the wallet amount wrong

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry-android#1160]
When I have a channel with 10 coins stacked but only 5 coins available to be spend in my wallet, an edit of the channel will fail with the message that my wallet has too little coins left.

But when I lower it to say 0.1 coins, 9.9 stacked coins will be removed from the channel.

So the check should count already stacked coins and the field should be prefilled with 0 coins.

When the user enters -5 the channel would end up with 5 coins stacked while when he enters 5 coins, the channel would end up with 15 coins stacked.

**Comment by tzarebczan** [comment]
Sorry about the bug, this is filed under https://github.com/lbryio/lbry-android/issues/860
