### ISSUE TITLE
Make Same Name Everywhere

### ISSUE THREAD

**Issue by yasharya2901** [lbryio/lbry-android#1166]
Odysee is a fantastic place as it has more categories to explore and I got to find a lot of Youtubers in Odyssey than I would ever found on LBRY. I'm Android user and there's only an app named LBRY, which has less categories and so buggy. But when someone recommends Odysee, it kind of create a confusion if they both are the same thing or not. Also, there's an app called Odysee only for iOS but same not available on Android, Mac, Linux and Windows. Please make every app name same or add more categories to LBRY or make it so that if we get invite link whether from LBRY or Odysee, it should open on the installed app in given platforms.

**Comment by tzarebczan** [comment]
Thanks for the feedback, an Odysee Android app is coming and LBRY one will be for power users.
