### ISSUE TITLE
Total amount of LBC does not convert correctly to USD in wallet

### ISSUE THREAD

**Issue by lgyurci** [lbryio/lbry-android#1185]
## The Issue
Wallet in the app displays the total owned amount in $ incorrectly.
### Steps to reproduce
1. Support any channel/make any revokable support
2. Go to wallet
3. ???
4. Profit

### Expected behaviour
The total amount (revokable stuff + owned stuff) is displayed, and below that that amount is displayed in $. The total amount in LBC should be equal to the total amount in $.

### Actual behaviour
The two values are not equal (if you convert one to the other). The value in $ only represents the value you currently have, without the revokable support stuff, which is incorrect, since the two values are connected with a ≈ sign.

## System Configuration
- Device: Xiaomi Redmi Note 5 Pro
- Android version: 10

## Screenshots

![Screenshot_20210414-000622](https://user-images.githubusercontent.com/55853197/114628223-d0715000-9cb6-11eb-9f3d-6875b1650763.jpg)
As you can see, 2.3 LBC does not convert to 0.08 USD

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing. Right now it's showing the available balance total, but we need to show the overall value. We'll get this fixed soon!
