### ISSUE TITLE
Non-video crashing app

### ISSUE THREAD

**Issue by braderhart** [lbryio/lbry-android#1189]
### Steps to reproduce
1. Search for ed25519 on LBRY
2. Click on the first [video](https://odysee.com/ed255c9e-dd5c-4fbd-894b-37c9192f8ded:d)
3. The app crashes

### Expected behaviour
The app shouldn't crash

### Actual behaviour
The app crashes

## System Configuration
- Device: moto one action
- Android version: 11

**Comment by kekkyojin** [comment]
Fixed on master
