### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by chb1828** [lbryio/lbry-android#1196]
Hi, I cloned the repository as written in the readme and opened the project in Android Studio, but I get an error like the picture below.   
![캡처](https://user-images.githubusercontent.com/55731606/121858348-8138b180-cd31-11eb-9348-f4efd9e8e70a.PNG)

And I tried to access the address written in the error log.

![캡처](https://user-images.githubusercontent.com/55731606/121858545-b34a1380-cd31-11eb-85b3-4c766fab46c3.PNG)

**Comment by kekkyojin** [comment]
Hello, @chb1828. I have just been able to get all dependencies after invalidating cache and restarting Android Studio.

LBRY Android SDK is being currently hosted at BinTray, which is shutting down. They said that from time to time, they will stop serving files to encourage developers to migrate to other services. I suggest you to keep trying it. Then Android Studio will reuse the cached version of the AAR file.

LBRY Android SDK was previously bundled with the source code, but had to be moved into some third-party so LBRY FDroid could be built. LBRY Android SDK uses some customized tools to be built so it won't work with other 'built-on-the-fly' services and FDroid requires that hosting service is one of those which are "well-known" for the free software community.

Some solutions are being discussed but a choice has not been performed yet.

**Comment by kekkyojin** [comment]
Fixed on commit 5f2c72ec4d07b1904ad5a2fe1626480b820ce521 when LBRY SDK Android was updated from 0.94.1 to 0.100, which is now hosted on MavenCentral.
