### ISSUE TITLE
Pop out player / minimize videos instead of exiting when back button pressed

### ISSUE THREAD

**Issue by vv181** [lbryio/lbry-android#120]
## The Issue
Mimicking The Youtube android APP, pressing back button while playing video should minimize the current playing video and continues to play, instead of exiting the video entirely. The video should be shown in pop out mode. 

### Steps to reproduce
1. Open any videos
2. Press back button
3. The videos are exiting

### Expected behavior
The user should able to browsing another videos/content while the current videos that currently they watching are not exiting.

### Actual behavior
The videos exited.

## System Configuration
- Device: Mi A1
- Android version: 8.1

## Anything Else
Reference: https://codedaily.io/tutorials/10/Create-a-Youtube-Video-Page-with-Animated-Video-Drag-to-Corner-in-React-Native

## Screenshots
https://i.imgur.com/9Xg58r4.gif

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This would require a pop out player. Will update the issue.

**Comment by akinwale** [comment]
Done!
