### ISSUE TITLE
Option to cache or keep files for devices with limited storage.

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#121]
## The Issue
Downloading video content most particularly is problematic for lower-end mobile devices.  Filesizes since they are not dynamic as they are on vanilla streaming platforms this means you're going to get whatever file the uploader committed to the LBRY network.  It's appropriate behaviour, but it has a side effect of not being low-end device friendly.

### Enhancement
One potential remedy for this issue would be any of the following options singularly or in some hybrid combination:
* Calculate free space and keep LBRY app usage below a specific percent through deleting the oldest files.
* Automatically delete oldest files.
* Delete files when finished consuming them.
* Ignore files marked for keeping.

### Possibly Ideal Option.
* Add a downloads management view to the app as mentioned in issue #105
* allow users to "sticky" files so that they don't get cleaned up automatically.
* Keep track of playback progress for larger video/audio files or files marked with certain meta like "podcast" or "audiobook."
* If a file has been completed then mark it for cleanup.
* If a file is over X time old and hasn't been touched also consider the file for cleanup.

### Reasoning
The app should aim to deliver a fairly simple interface which is going to function ideally by default and then if we so desire to give people options to change the behaviour secondly.

The priority here would be to focus on ensuring that devices free space is available as much as possible as to not get in the way of the user's needs.

I also don't imagine people will be seeding much from their mobile devices that sort of work will likely be done by PC / variant hardware.

**Comment by alyssaoc** [comment]
this has been implemented
