### ISSUE TITLE
Media stats and info

### ISSUE THREAD

**Issue by trymeouteh** [lbryio/lbry-android#1213]
Please add the following details when viewing a video, audio or document in the LBRY app.

- See how many nodes are hosting the file
- File size
- Transaction ID (WHere in the blockchain the file is stored)
- Magnet Link
- Metadata

**Comment by tzarebczan** [comment]
Same reply as the Desktop thread

**Comment by trymeouteh** [comment]
I cannot find any details of the file on the mobile app such as Claim ID, LBRY URL, Languages, Media Type, License, and file size.

I cannot find a magnet link anywhere on the content page for the data

By nodes, It would be nice to have a number on how many people are seeding the file and how many peers are there for the file just like in a bittorrent client to determine the strength of the file on the network
