### ISSUE TITLE
File hosting settings

### ISSUE THREAD

**Issue by trymeouteh** [lbryio/lbry-android#1214]
Please add the following feature and setting on content you are helping to host in the LBRY app

- host viewed data (See what you are hosting/seeding)
- Storage size limit (Set a limit of how much data you store and share and once it reaches the limit, it will delete the oldest files to store and share the new files)
- Starred file (Files that are starred will not get deleted automatically by the app when the app deletes files once the storage limit is reached)

**Comment by tzarebczan** [comment]
Same reply as the Desktop thread
