### ISSUE TITLE
Alternative App Stores [ App Beta ]

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#125]
## The Request

Get this app listed on alternative app stores like the following.

- [ ] [F-Droid](https://f-droid.org/en/contribute/)
- [ ] [Amazon](https://developer.amazon.com/app-submission)
- [ ] Other Suggestions welcomed.

### Benefits
The Amazon App Store is likely the only way to install apps on the [Amazon Fire](https://www.amazon.com/Amazon-Fire-7-Tablet-5th-Generation/dp/B00TSUGXKE) 

The F-Droid app store is a bit more nieche but it will appeal to the security and open source conscious people.  Which I can imagine that Block Chain tends to attract a lot of.

### Actual behaviour
Direct APK download and Beta Access Android App Store release.

### Other Information
Issue submission inspired by ICTman from Discord.

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/growth #87](https://github.com/lbryio/growth/issues/87) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ahangarha** [comment]
The link to https://github.com/lbryio/growth/issues/87 is broken.

I wanted to get update on this issue. If you have plan to add the app on F-Droid or not. Is there any issue in this regard?

**Comment by tzarebczan** [comment]
Thanks for reaching out! We'll make this determination after the app is out of it's intial beta state. Users who wish to download the apk can do so from here: 
http://build.lbry.io/android/latest.apk

But please be aware that there is no update notification in that case (issue filed under https://github.com/lbryio/lbry-android/issues/385)
