### ISSUE TITLE
Unable to select text under video description

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#127]
## The Issue
you cannot select any text under the video description, or open or click links
### Steps to reproduce
1. open any video
2. check below the video if there's a text description or link
3. try copying

### Expected behaviour
you should be able to copy the description, and open links if any

### Actual behaviour
nothing happens, no option to copy, and links are not highlighted

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0

**Comment by akinwale** [comment]
Fixed.
