### ISSUE TITLE
Video is too much stretched in landscape mode (not full scree)

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#152]
## The Issue
The video appears too stretched in landscape 
### Steps to reproduce
1. Download any video
2. Start playing 
3. Switch device from portrait to landscape 

### Expected behaviour
Video should show normal in landscape even if not fullscreen

### Actual behaviour
Instead it shows in landscape too stretched and the delete button also stretches as well 

## System Configuration
- Device: Samsung note 8
- Android version: Androind 8.0

## Anything Else

The delete button becomes too long as well in landscape 

## Screenshots

https://cdn.discordapp.com/attachments/439055085616496640/452097036867600385/Screenshot_20180601-112729_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Fixed.
