### ISSUE TITLE
Video starts playing after dragging scrubbar forward

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#154]
## The Issue
The video playing starts over again when you drag the scrubbar forward, there'll be an indication at the point where the video Is to start playing after dragging forward and yet another indication of the video starting from beginning. 
### Steps to reproduce
1. Download any video, for this issue was generated with lbry://ethereum-asic-miner-shipping-soon#0f399396ec18a783f9bc66d58fe2095b31f36d40
2. Start playing after download is completed
3. Drug the scrubbar forward, if it continues playing, drag it back and forward again. The video will pause at where you dragged it to and when you press play, it'll start the video from the beginning whiles pointing to where you dragged it to, I've included a screenshot for easier explanation. 

### Expected behaviour
Tell us what should happen
1. Video should continue playing when we drag it forward not pause
2. Video should not start over again for dragging scrubbar forward.

### Actual behaviour
Tell us what happens instead
1. Video pauses for moving scrubbar forward
2. When you hit play it stays again 
3. You get 2 indicators, one showing the progress of the video starting and another showing where you dragged the scrubbar to.

## System Configuration
- Device: Samsung note 8
- Android version:android 8.0

## The Issue
The video playing starts over again when you drag the scrubbar forward, there'll be an indication at the point where the video Is to start playing after dragging forward and yet another indication of the video starting from beginning. 
### Steps to reproduce
1. Download any video, for this issue was generated with lbry://ethereum-asic-miner-shipping-soon#0f399396ec18a783f9bc66d58fe2095b31f36d40
2. Start playing after download is completed
3. Drug the scrubbar forward, if it continues playing, drag it back and forward again. The video will pause at where you dragged it to and when you press play, it'll start the video from the beginning whiles pointing to where you dragged it to, I've included a screenshot for easier explanation. 

### Expected behaviour
Tell us what should happen
1. Video should continue playing when we drag it forward not pause
2. Video should not start over again for dragging scrubbar forward.

### Actual behaviour
Tell us what happens instead
1. Video pauses for moving scrubbar forward
2. When you hit play it stays again 
3. You get 2 indicators, one showing the progress of the video starting and another showing where you dragged the scrubbar to.

## System Configuration
- Device: Samsung note 8
- Android version:android 8.0

## Screenshots

![smartselect_20180602-132407_gallery](https://user-images.githubusercontent.com/38915222/40872227-598f6f58-6668-11e8-9b0a-bee77847fa7c.jpg)
![20180602_132309](https://user-images.githubusercontent.com/38915222/40872228-59dd0b8c-6668-11e8-82f6-7ebe83e47610.jpg)

**Comment by akinwale** [comment]
Fixed.
