### ISSUE TITLE
The video screen goes white when you click the search,

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#161]
## The Issue
The video screen goes white when you click the search, and after you exit the search bar by clicking back, still appears white and blank but you can hear the video playing until you tap the screen, then the video comes up again. This only happens in Landscape mode and I have been able to generate it over again...

## System Configuration
- Device: Lenovo Vibe K4 Note
- Android version: 6.0 Marshmallow

**Comment by akinwale** [comment]
https://github.com/lbryio/lbry-android/pull/197 should fix this.
