### ISSUE TITLE
Android Beta Epic

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#167]
## The Issue
Epic to track cross repo / lbry-android items needed to move into Android Beta launch. This includes internal api changes as well as rewards.

## System Configuration
- Device:
- Android version:

**Comment by alyssaoc** [comment]
@akinwale Why did you close the current epic? Did you start a new one?

**Comment by akinwale** [comment]
@alyssaoc My assumption this was meant for issues required to transition from closed alpha to open beta.
