### ISSUE TITLE
Authentication and device_id

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#168]
## The Issue
The Android app needs to authenticate a user to internal-apis using an auth token and store a unique device id. 

See:
- https://github.com/lbryio/internal-apis/issues/387
- https://github.com/lbryio/lbry-app/issues/1579

@akinwale please fill in the details as you get to this.

## System Configuration
- Device:
- Android version:

**Comment by tiger5226** [comment]
This is the only issues left open for the epic. @akinwale what do you need from internal-apis to close this out?

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/lbry-android/pull/232
