### ISSUE TITLE
Generate a unique device ID that persists between installs

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#170]
The daemon's `install_id` is not a reliable way to uniquely identify a device, because a new one can be generated upon uninstall and reinstall of the app.

A unique ID needs to be generated which will always be the same for a particular device.

**Comment by kauffj** [comment]
Do we need to generate this? Doesn't the phone provide this?

**Comment by akinwale** [comment]
Generate is probably the wrong term, but the idea is to hash the ID that the phone provides before storing it. According to https://developer.android.com/training/articles/user-data-ids, we can use the IMEI (associated with a device) or IMSI (associated with a SIM card). I would be inclined to use the former.

**Comment by kauffj** [comment]
Got it - no opinion on choice between those two
