### ISSUE TITLE
Media playback while downloading

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#191]
At the moment, when the media player loads a file that hasn't completely downloaded yet, it plays up to the point when the incomplete file was loaded. In some cases, this leads to a loss of audio during video playback, and then the video eventually stops shortly after that. When playing audio, the playback gets interrupted and the player doesn't do anything afterwards.

We need to find a way to allow the media player to continuously load the file until the download is completed.

I have been exploring options for this and one of the suggestions I've found is to set up a local stream server on the device which will only be used for files which have not been completely downloaded. This may ultimately be the solution if there is no way to enable the underlying media player (ExoPlayer) to progressively play an incomplete file until it is completed.

**Comment by kauffj** [comment]
More research should be done into possible solutions before doubling down on the existing one.

**Comment by akinwale** [comment]
Fixed.
