### ISSUE TITLE
media player doesnt support Autohide Virtual Navigation Button features

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#193]
## The Issue
upgrade media player full-screen mode on android smartphone that has a virtual navigation button. this should be at levelkn in order to get the best results when viewing the video in full screen mode then the virtual navigation button should be automatically hidden. and if you want to bring it up then we have to swipe up the bottom of the screen. smartphones now have in-screen navigation features. because it will progress to bezelless scrren phone. better if lby app android version have or enhance this video player to support auto hide navigation virtual button. i test using Sony Xperia Z5
### Steps to reproduce
1.  Using Smartphone has in-screen virtual navigation button ( eg Sony Xperia Z5 or  etc)
2.  open LBRY APP and watching some video
3.  start fullscreen mode inj landscape mode

## System Configuration
- Device: Sony Xperia Z5
- Android version: 7.0 Naugat

## Anything Else

Most Media Player have this features and youtube app also have this feature. LBRY App why not. hehe

## Screenshots

![jpeg_20180623_222526](https://user-images.githubusercontent.com/26609573/41867122-646d972a-78dc-11e8-9e75-49117a8e693d.jpg)

**Comment by tzarebczan** [comment]
Thanks for filing Chris! Not a huge priority, but a feature we should support at some point.

**Comment by ceoger** [comment]
The search bar should also disappear during full screen mode, I believe that could also hide the navigation, my phone does not show navigation but shows the search box 

https://cdn.discordapp.com/attachments/439860056683446293/471748882905432066/Screenshot_20180726-000658_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Fixed.
