### ISSUE TITLE
Defer collection of device ID until necessary (presumably for rewards)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#194]
The app asks for my device ID (and thus, ability to make calls) on startup. This is offputting to some users.

It would be preferable if this wasn't requested until necessary as part of opting in to rewards.

**Comment by ribeiro458** [comment]
como obter recompesa nesse aplicativo porque estou perdido

**Comment by shyba** [comment]
Olá, recompensas para Android estarão disponíveis em uma futura versão beta.
