### ISSUE TITLE
Support new daemon startup process

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#196]
## The Issue
When lbryio/lbry#1164 is merged, the status calls returned to the app will be different. From changelog:
STARTUP_STAGES from status API and CLI call, it instead returns a dictionary of components along with their running status(this is a potentially breaking change if STARTUP_STAGES is relied upon)

This might be a good opportunity to make the startup messages more user friendly.

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/223
