### ISSUE TITLE
Issue: Error produced while pressing the back button upon app startup

### ISSUE THREAD

**Issue by FireDFL** [lbryio/lbry-android#206]
## The Issue
When the LBRY Android app is loading, if you press the "back" button, an error message will pop up (refer to screenshots.)

### Steps to reproduce
1. Open the LBRY app.
2. While the daemon is loading and/or blockchain sync is occurring, press the back button to get the error.

### Expected behaviour
Pressing back should either exit the app or do nothing.

### Actual behaviour
The error is produced instead.

## System Configuration
- Device: Samsung Galaxy S5 (SM-G900P)
- Android version: LineageOS 14.1 (Android 7.1)

## Screenshots

![screenshot_20180722-160453](https://user-images.githubusercontent.com/14083041/43087895-ed07c50e-8e6e-11e8-8a6c-3d59688c6b09.png)

**Comment by tzarebczan** [comment]
@FireDFL thanks for filing this, sent you some LBC on Discord :)

**Comment by akinwale** [comment]
Fixed.
