### ISSUE TITLE
Implement email verification flow for authentication

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#207]
Once we have email verification code endpoints (or another solution) implemented on api.lbry.io, the rewards flow needs to be updated in order to allow a user enter a verification code after they provide their email address.

Once an email address is verified, an authentication token can be retrieved which will be used to send the device_id to the API.

#168 and #180 depend on this.

**Comment by kauffj** [comment]
@akinwale what about the changes that need to happen that are outside of this repo?

**Comment by akinwale** [comment]
@kauffj I filed https://github.com/lbryio/internal-apis/issues/454
