### ISSUE TITLE
Video  Unable to Play Before/After Download

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#213]
## The Issue
Video does not play whiles downloading, only shows download progress with the thumnail and when download is completed only shows black screen with 0:0 start time and 0:0 end time

### Steps to reproduce
1. try playing this video https://open.lbry.io/HowToCreateAChannelAndPublishAVideoOnLbry
2. Wait fro download to start, you'll see download progress on thumbnail
3. After download is completed, try playing, video shows playing but nothing shows and the duration is default 0:0 from start to end all you see is the black screen

### Expected behaviour
video should play when download start

### Actual behaviour
video does not play until after download is completed, you close the app from backgroun and click the link to open again, then it plays

## System Configuration
- Device: Samsung Note 8 
- Android version: 8

## Screenshots

https://cdn.discordapp.com/attachments/439055085616496640/467724814648344577/Screenshot_20180714-213650_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/467724814648344578/Screenshot_20180714-213707_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/471743582299095041/SmartSelect_20180725-234931_LBRY_Browser.jpg

**Comment by tzarebczan** [comment]
Does this video play normally in the LBRY app?

**Comment by ceoger** [comment]
Yes It does

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/229.
