### ISSUE TITLE
Disk Space Management / UX and File Stopping

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#241]
The current app behavior around file starting and stopping, especially as it relates to disk management, is likely to cause both user confusion and user complaints about large disk size usage.

I'd propose the following modifications to the current design:

1) When a user explicitly pauses a video or navigates away, stop the download `n` seconds later (maybe 5? 10?), but do not delete the content.
2) Add a setting that specifies the maximum disk space the app should use for content. Mention that this setting may be exceeded if the user streams a video that exceeds the set value. Pick a sane default for this, like 1GB. Include an ability to set this to "No limit / Manual management". 
3) When viewing a file that is taking up space on the disk, show some ability to delete the file but give it much less prominence than it's given currently. Most users will not expect to directly manage this and will not be used to it. Possibly hide it entirely unless the user has selected to not have a disk space limit.
4) On app startup and periodically (either time interval, or when new downloads start, or some other sensible choice) delete the least recently accessed files until disk use comes below this value.

It's also worth considering if this is better implemented in `lbry`, since this logic may be useful beyond just mobile.

**Comment by alyssaoc** [comment]
We need to identify the issues for this epic
