### ISSUE TITLE
Track the time it takes for media to start playing after a user presses Play 

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#244]
We need to measure the time it takes for a media file to actually start playing from the moment the user presses the Play button.

**Comment by kauffj** [comment]
@seanyesmunt is doing and/or did this, code can probably be shared?

**Comment by akinwale** [comment]
Indeed. Assuming the related actions and selectors are going to be implemented using redux, I suppose it makes sense to implement the functionality in `lbry-redux`.
