### ISSUE TITLE
lbry://update-cardano doesn't play, filename?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#254]
## The Issue
I suspect it's due to special characters in the file name - I uploaded the same file to: lbry://testmp4 and it streams.

Related: https://github.com/lbryio/lbry/issues/794 - I'm under the impression this will be fixed in python3

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Yes, this is due to special characters in the filename. I'll have to fix by escaping some additional special characters in the file URI.
