### ISSUE TITLE
Claim page for 3d files shows blank preview

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#255]
## The Issue
When going to a 3d file like lbry://libraryiconbookend, the stl downloads but the preview is blank. Maybe we can just continue to show the thumb there and allow users to open the stl with something like: https://play.google.com/store/apps/details?id=com.performance.meshview
![screenshot_20180822-224857_lbry browser](https://user-images.githubusercontent.com/8120721/44542312-6ad18f00-a6da-11e8-988d-b7284c9a7adb.jpg)

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
It's actually supposed to keep showing the thumb, and an "Open" button.
