### ISSUE TITLE
Landscape Mode on a video gives a wild error

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#258]
## The Issue
Landscape mode on a selected video gives a wild error screen in "eye piercing" red lol

### Steps to reproduce
1. Open the app, 
2. click any video in the discovery page
3. switch view mode on phone to landscape and this error comes up

### Expected behaviour
We should be able to view video in landscape mode

### Actual behaviour
once you select a video, and switch to landscape mode, this error comes up

## System Configuration
- Device: Note 8
- Android version: 8

## Screenshots

https://cdn.discordapp.com/attachments/363087331475062785/482266735593127956/Screenshot_20180824-004259_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/482269809686478848/LBRY_Browser_2018-08-24-00-51-24_1.mp4

**Comment by ceoger** [comment]
video however plays, i hear the background sound of the video playing over the error message, and back takes me to the video playing

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/271.
