### ISSUE TITLE
No option for continue after entering email address on startup

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#259]
## The Issue
App does not provide option for continue or next/cancel after entering email
### Steps to reproduce
1. install the app
2. launch and on startup screen, enter email
3. No option for next/continue only skip

### Expected behaviour
there should be a next or continue... some action on the email entered other than just the skipp

### Actual behaviour
all you can do after entering email is skip

## System Configuration
- Device: Note 8 Samsung
- Android version: 8

## Screenshots

https://cdn.discordapp.com/attachments/439860056683446293/482271689154232331/Screenshot_20180824-003815_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Thank you for this report. The PR related to this is still a work in progress. Please see https://github.com/lbryio/lbry-android/pull/251.

**Comment by tzarebczan** [comment]
this is still occurring...we should get this fixed ASAP.
