### ISSUE TITLE
Can you explain the current solution?

### ISSUE THREAD

**Issue by avoloshko** [lbryio/lbry-android#28]
Can you explain the current solution?

Android IPC to communicate with the service?

Can you list the supported API and Java examples of the service usage?

**Comment by akinwale** [comment]
@avoloshko 
The main package is built using the buildozer build tool which combines three different things:
- The Python code located in `src/main/python`
- The Java code located in `src/main/java`
- The React Native app bundle which is built from the React source located in `app/`. You can have a look at the `build.sh` for an idea how to create the bundle.

The service starts the Python daemon which runs a JSONRPC HTTP server on localhost:5279. With this, you can make requests as shown here: https://lbry.io/quickstart/api

Here's the full API reference:
https://lbryio.github.io/lbry/
