### ISSUE TITLE
Go to recommendations after video plays

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#280]
As an android app user, I would like the app to go to/ scroll to recommend new videos after the current video finishes.

This would be a similar experience to the desktop app.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
We show related content, but it's at the bottom and some users may not even see it. Think this can be improved somehow.

**Comment by akinwale** [comment]
Done.
