### ISSUE TITLE
Open Beta Feedback - UX

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-android#282]
### Steps to reproduce
1. Install fresh app
2. go through the setup process
3. ???

### Expected behaviour
The app is perfect and I have no feedback

### Actual behaviour
The app isn't perfect and I have feedback :)

- Phone number field is not easy to select, there are no visible input areas/boxes and they don't take up the whole screen width. I thought the app was bugged until i tapped close enough to the prefix
- When the keyboard is up (perhaps this was just me mis-tapping twice?) tapping a button doesn't do anything, it only hides the keyboard. I had to tap once more
- When the text message is sent, the app expects a code to be inserted. I had granted permissions on the first step but it didn't autofill, I had to fill the numbers myself
- Bonus/malus point: the swiss flag was messed up when I typed in my phone number NBD I guess
- When the player is in full size I can't change the orientation by simply flipping the phone (it's set to be portrait only but youtube allows you to do that) (actually even if it's in rotation mode it doesn't allow you to choose your own orientation)
- When watching full screen, if I tap on back (nav bar) the video stops playing and I go back 1 menu. I'd expect the player to exit fullscreen only
- when checking rewards, if one wants to try and claim one they have to tap on the small circle. tapping on the whole box does't work. I think it should
- hitting back doesn't actually bring you back to where you were. Example: go to "my lbry", tap on a video, hit back, you're not in "my lbry" anymore
- hitting back from the main menu kills the app. That's fine, but i think there should be a confirmation box first.
- Actually hitting back will make it so that if you go back to the app you need to wait for the green screen again, however it seems impossible to close lbry for good thus also removing the notification on the top.

## System Configuration
- Device: Oneplus 5T
- Android version: 8.1

**Comment by alyssaoc** [comment]
closing, opened issues for each item
