### ISSUE TITLE
Check is_reward_approved  or is_identified_verified for rewards status

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#286]
## The Issue
In addition to is_identity_verified, check if is_reward_approved is set to 1 (this is the case for manually approved accounts and grandfathered ones).  If is_identity_verified is 1 but is_reward_approved is set to 0, that's the case we want to show the Rewards review message. 

App code: https://github.com/lbryio/lbry-desktop/blob/5407dc188e8fbafba0bd42a7b910443ead078bb6/src/renderer/page/rewards/view.jsx#L32

## System Configuration
- Device:
- Android version:

**Comment by tzarebczan** [comment]
@akinwale think we should patch this up before open beta, otherwise it could cause some confusion for grandfathered and manually approved users.

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/lbry-android/commit/fe5d711fea57247ed0054a025328024bbeaea57b.
