### ISSUE TITLE
"My LBRY" data usage stats sometimes don't include all content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#287]
## The Issue
When I first accessed My LBRY to see download stats, the stats only showed a few KB, but there was a video listed at 17MB that wasn't included. Going back into My Later later showed the correct stats. @akinwale said he's seen this before as well. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Renamed "My LBRY" to "Downloads". https://github.com/lbryio/lbry-android/commit/e0f746b5ae70ae5a337f93e91dd2dddeec8c22bc
Also made some changes previously which should tackle this. Please reopen if the issue occurs again.
