### ISSUE TITLE
Images/HTML/Markdown files should show "view" and open file immediately after download

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#288]
## The Issue
Currently, you are shown the "Download" button. If you click download, then you are shown the "Open" button which leads to a new screen with the image/HTML file. This flow should be replaced with a "View" button that goes directly to the content. 

Not sure what other file types outside of video we support, but any viewable formats should follow this flow. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
