### ISSUE TITLE
React development server for development

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#29]
Find a way to enable get the React development server working so that Javascript code can be reloaded without having to rebuild the app bundle and APK every time.

**Comment by akinwale** [comment]
I was able to take a different approach by creating a new React Native app using the `create-react-native-app` CLI tool, and developing this app UI separately from the daemon. I can then proceed to easily test the app with a daemon running locally on the device, or a daemon running remotely.

With the created React Native app, I can hot reload any UI changes which speeds up the frontend development process. I am also maintaining the same folder structure as the android build which makes it easy to just copy over the files and then build the APK as required with buildozer.

**Comment by kauffj** [comment]
@akinwale nice! I encourage you to keep the `README` or `INSTALL` file up to date with the recommended dev set up.
