### ISSUE TITLE
Wallet data / Cross-device sync plan

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#290]
## The Issue
When you uninstall the LBRY android app, it cleans up all data including the wallet. This will be quite common especially when going from test APK builds to a Google Play store build (need to uninstall the apk before installing from Google Playstore).

I think we should put an extra warning on the wallet if we don't plan to support a backup/restore option before beta. 

## System Configuration
- Device:
- Android version:

## DOD

Design the cross-device sync solution

**Comment by tzarebczan** [comment]
Discussed on standup today - even if we want to test APKs internally, we'd need to uninstall the google play store version first (which results in wallet/data/email loss).

**Comment by kauffj** [comment]
Is this the only issue inhibiting testing/running different versions?
