### ISSUE TITLE
LBRY Lite Wallet

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-android#291]
Can we have separate app with just wallet function if someone just wanna be able to access LBC founds without need to download whole GUI (maybe lightwallet)

**Comment by tzarebczan** [comment]
You can use the Coinomi app if you just want to access the wallet. I also think the LBRY Android app will act enough as a light wallet (just don't download/view any content). I don't think we'll be creating anything separate from this in terms of a wallet.

**Comment by ribeiro458** [comment]
Porque a minha carteira do aplicativo android nao e a mesma do windous e tambem os resultados sao diferentes
