### ISSUE TITLE
Download doesn't cancel properly sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#299]
## The Issue
If you stop a download/stream that's in progress, sometimes it goes back into a "0% complete" state (does not download). You have to click "stop download" a 2nd time to go back to the normal state. @akinwale mentioned this may be due to file_list quirks - do we wait until the file_set_status/file_delete calls complete successfully before refreshing the page? 

## System Configuration
- Device:
- Android version:

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/lbry #1443](https://github.com/lbryio/lbry/issues/1443) via [**ZenHub**](https://www.zenhub.com/)
