### ISSUE TITLE
Notify user or prompt for default when other lbry:// schema apps installed

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-android#300]
## The Issue

"Magic link" confirmation link makes Android offer to open LBRY app OR Coinomi (since the also registered for lbry://). The page needs a better how-to explanation for the new user to reduce confusion and number of people who will choose to open with Coinomi. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
I originally thought this note might be better on the Android app, but agree that it makes more sense ont he verification page. Will move this over to lbry.io.

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry.io #765](https://github.com/lbryio/lbry.io/issues/765) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tzarebczan** [comment]
Reopening per https://github.com/lbryio/lbry.io/issues/765#issuecomment-422105471

**Comment by akinwale** [comment]
This is handled at the device OS level. The user is prompted to select the default app for the corresponding schema links.
