### ISSUE TITLE
Hide top menu bar in android

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-android#301]
When using the app it would be better if the top menu bar of android was hidden, the one I mean is where the time is displayed

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by oakey22** [comment]
https://spee.ch/d/Screenshot20180917-181057

**Comment by kauffj** [comment]
We think that bar should remain (unless you are seeing the bar in full screen, in which case, re-open).
