### ISSUE TITLE
Support special link navigation to pages (i.e. rewards page) in the LBRY Android App

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#306]
## The Issue
support special link navigation

### Steps to reproduce
1.  copy this link to a browser on any android device: `email.mail.lbry.io/c/eJxNjMEKwyAQBb8m3ipqrNkcPDS0-Y81btKAxmAtbf6-Uij08hh4zHjrUGgxsdUqIUH0EupKobnkY2sGc-s72fVmGK6XRouIa-DB5YOvid2t015oDw5AzoKcmrFVBsx57owDicCCTTttP6NRY9OOmV6Y_YNlO1FaKDvKtbx801OKrNhCcQ9Y6ITPkmIFX82N3uXk8fj7P_hAOyo` - this link is: https://open.lbry.io/?rewards
2. open with the lbry app
3. you get an error

### Expected behaviour
link should open correctly in the android app and go to the rewards page. 

### Actual behaviour
link breaks app

## System Configuration
- Device: Note 8
- Android version: 8

## Anything Else

a reference to a similar issue Tom opened: https://github.com/lbryio/lbry-desktop/issues/1352
## Screenshots

https://cdn.discordapp.com/attachments/439055085616496640/491670919463436297/Screenshot_20180918-233425_LBRY_Browser.jpg

**Comment by tzarebczan** [comment]
Thanks for filing @ceoger ! I've updated your issue to make it a bit clearer.

**Comment by robvsmith** [comment]
I added language to this in the next-day email. This does not resolve the problem but will function as a stop-gap.

**Comment by robvsmith** [comment]
@alyssaoc - can you add a "consider soon" I don't think I can edit tickets in this board, but this needs to happen. Our outbound communications all have to have super lame, "Doesn't work on android" disclaimers.

**Comment by robvsmith** [comment]
open.lbry.io/?discover should open in all apps, since it is the most commonly shared link with our audience.

**Comment by akinwale** [comment]
Fixed.
