### ISSUE TITLE
Red screen when entering phone verification code

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#308]
## The Issue
2 users reported the below when using their phone number during verification:

![screenshot_20180918-172440](https://user-images.githubusercontent.com/8120721/45822669-fdedec80-bcb9-11e8-9942-c05db99a5eeb.png)
![screenshot_lbry_browser_20180920-053418](https://user-images.githubusercontent.com/8120721/45822676-ffb7b000-bcb9-11e8-827d-3bc5939857f6.png)

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Fixed with https://github.com/lbryio/lbry-android/commit/7c969cbe933095113b28038810407e70232382e1.
