### ISSUE TITLE
Easier deletion of videos

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#309]
## The Issue
Currently, to delete a video you must access the claim page from MY LBRY and then click the delete button. We should give the user an easier way to do this and also include batch/all actions.

1) Be able to delete a single video directly from MY LBRY page
2) Be able to delete all videos directly from MY LBRY page
3) Be able to use a selector to select and then delete videos from MY LBRY page

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-react-native/pull/28/commits/3ee6162ed40fcf94c0ac1290be71f3f944932485.
