### ISSUE TITLE
Error screen when scrolling

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-android#311]
## The Issue
When i try to take a screenshot with my oneplus 5t using the 3 fingers method i get a red error screen
### Steps to reproduce
1. in the app use 3 fingers to scroll down to take a screenshot

### Expected behaviour
i get a screenshot

### Actual behaviour
i get a screenshot of the error

## System Configuration
- Device: Oneplus 5t
- Android version: 8.1

## Screenshots
https://imgur.com/a/q0TwA7s

**Comment by akinwale** [comment]
Related: https://github.com/facebook/react-native/issues/15059

**Comment by alyssaoc** [comment]
closing, cannot address at this time
