### ISSUE TITLE
Prompt users to make LBRY Browser default for lbry:// links

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#312]
## The Issue
Per https://github.com/lbryio/lbry.io/issues/765, we should prompt users to make `LBRY Browser` the default for lbry:// links (possibly when they go through email verification or as a hint somewhere in the app startup process). 

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Handled at device OS level.
