### ISSUE TITLE
Autofill Code

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#319]
* When the text message is sent, the app expects a code to be inserted. I had granted permissions on the first step but it didn't autofill, I had to fill the numbers myself

from Niko

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Closing, this is no longer possible.
