### ISSUE TITLE
Back Nav bar behavior unexpected

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#322]
* When watching full screen, if I tap on back (nav bar) the video stops playing and I go back 1 menu. I'd expect the player to exit fullscreen only
* hitting back doesn't actually bring you back to where you were. Example: go to "my lbry", tap on a video, hit back, you're not in "my lbry" anymore
* hitting back from the main menu kills the app. That's fine, but i think there should be a confirmation box first.
* Actually hitting back will make it so that if you go back to the app you need to wait for the green screen again, however it seems impossible to close lbry for good thus also removing the notification on the top.

from Niko

**Comment by tzarebczan** [comment]
Related https://github.com/lbryio/lbry-android/issues/295

**Comment by alyssaoc** [comment]
duplicate of #295
