### ISSUE TITLE
lbry:// hyperlink fails to open sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#333]
I've run into this a few time - click a lbry:// hyperlink while the app is closed  - the app opens, but it fails to load the url requested. If I click it again, it works. If I exit out, it's hit or miss on the next try. 

## System Configuration
- Device:
- Android version:

**Comment by alyssaoc** [comment]
unable to reproduce, reopen with more detail

**Comment by tzarebczan** [comment]
This is still happening randomly - usually on cold open or when the app goes through startup phase (daemon already running)

**Comment by akinwale** [comment]
This is now definitely fixed!
