### ISSUE TITLE
Autoclaim rewards after downloads

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#334]
## The Issue
Similar to the desktop app experience, we should attempt to claim download related rewards after each download, and if it's not available, the call should fail silently. 

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Should this be done after the download is completed or immediately after get request succeeds?

**Comment by kauffj** [comment]
The app does it after `get` succeeds.

**Comment by alyssaoc** [comment]
closing, completed
