### ISSUE TITLE
Send email doesn't trigger new verification email

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#336]
## The Issue
If you don't confirm your email and then press the `send verification email` button (leave the rewards screen and come back if you don't see the button), nothing is sent.

**Comment by alyssaoc** [comment]
couldn't reproduce, closing

**Comment by tzarebczan** [comment]
I ran into this again...seems to happen if I use an email that's already existing in our system - maybe we aren't calling resend email, but just email new which 500s?  If I change the email to something like tom+2323232@lbry.com then it sends.
