### ISSUE TITLE
Simultaneously "active" and "no active" downloads

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#353]
The context text of the notification for LBRY downloads is logically impossible.
![screenshot_2018-10-29-13-52-22](https://user-images.githubusercontent.com/530774/47670994-f9540800-db84-11e8-963f-88c5b28a7437.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
close, reopen if able to reproduce
