### ISSUE TITLE
Duplicate entries in My LBRY downloads list (random)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#358]
## The Issue
Haven't been able to reproduce this consistently, but sometimes I see the same claim twice in the My LBRY section. Leaving the page and coming back fixes it. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Was able to grab a screenshot when it happened (3 dupes!). Looks like it may be related to accessing the My LBRY page during a download. 

![screenshot_20181111-201344](https://user-images.githubusercontent.com/8120721/48365958-6afa7e80-e67a-11e8-9a58-8a60f5a653b0.jpg)

**Comment by akinwale** [comment]
This should be fixed with https://github.com/lbryio/lbry-android/commit/0cc2b4e3683a0cc201762f5386ddcddd7006eae2. @tzarebczan Please keep an eye out for this in the latest build and let me know if you it happens.

**Comment by alyssaoc** [comment]
closed, reopen if necessary
