### ISSUE TITLE
can't claim rewards on latest APK

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#359]
## The Issue
The undefined issue has surfaced again when trying to claim rewards. 

`undefined is not a function (evaluation a.lbry.wallet_unused_address()'`

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
This is due to the `lbry-redux` yarn build retaining some older code, despite adding the `yarn cache clean` command. Usually, restarting the Travis build after updating the `dist/bundle.js` in the `lbry-redux` repository creates an functional APK. Need to find a permanent solution to the issue.

**Comment by akinwale** [comment]
Fixed in the most recent builds.
