### ISSUE TITLE
menu display issues on OnePlus 6T

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#360]
## The Issue
See below, same goes for the section title on the top bar. 
![screenshot_20181112-130011](https://user-images.githubusercontent.com/8120721/48366178-0ab80c80-e67b-11e8-934f-885b1f7c5b91.jpg)

## System Configuration
- Device:
- Android version:

**Comment by akinwale** [comment]
Related: https://github.com/facebook/react-native/issues/15114

@tzarebczan Could you change your system font to Roboto and see if the menus display without the text getting cut off? A workaround may be to set a custom font for the text in the menus, but I'll need to test if it works with just one specific font or any font that isn't the default OnePlus system font.

**Comment by tzarebczan** [comment]
Yep, menus are fine after switching to roboto.
