### ISSUE TITLE
App Rating

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#376]
## The Issue
As a user, I would like to be prompted to leave a rating in the google play store.
If I want to leave a negative review, I should be given an opportunity to submit it directly to LBRY

### Acceptance Criteria
1. Get prompted to a leave a review after x number of hours of use
2. Leave a positive review at Google play
3. Leave a negative review at LBRY

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
