### ISSUE TITLE
Issues when stopping download

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#377]
## The Issue
After stopping a download, the thumbnail shows 0% and the notification says 0 downloaded/doesn't dismiss. 

## System Configuration
- Device: One Plus 6T
- Android version: Pie

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Still get the notification, but thumb returns to normal. If you download again right after and then delete, you get a "connecting" message.

**Comment by akinwale** [comment]
Fixed.
