### ISSUE TITLE
Redeem reward notifications needs improvement

### ISSUE THREAD

**Issue by toktoakhil** [lbryio/lbry-android#380]
### Steps to reproduce
1.Click Rewards and enter a custom code and press redeem

### Expected behaviour
Make reward notification come in top of the screen with a much more black or white overlay.

### Actual behaviour
Reward notification is showing below in overlapping keyboard which is not much readable on specific cases. I am attaching screenshots for that.

## System Configuration
- Device: Nokia 6.1 Plus
- Android version: Android Pie

## Screenshots
https://ibb.co/GFyR3rf 
https://ibb.co/CsPHGVY
https://ibb.co/0fk5T49

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Hey @toktoakhil. Thank you for your issue report. We display notifications using Android's default toast notifications, which makes use of the default device theme. Unfortunately, there isn't much we can do here.

**Comment by toktoakhil** [comment]
Can you make the keyboard vanish when we click on redeem button.

**Comment by tzarebczan** [comment]
@akinwale is the above possible?

**Comment by akinwale** [comment]
This has been addressed in https://github.com/lbryio/lbry-android/pull/411/commits/f389e315a6a5ccfc612cf6d6e856a14a35412ffd

The soft keyboard will be dismissed when you press the claim button.
