### ISSUE TITLE
Unable to copy verification email text into android app

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#383]
## The Issue
cannot paste email verification text into android app
### Steps to reproduce
1. Try verifying your email on the android app,
2. Copy Verification and there's no where in the app to paste
3.

### Expected behaviour
just like desktop, there should be a space to copy verification text into the app

### Actual behaviour
nowhere to paste text, had someone using brave browser facing this issue

## System Configuration
- Device: OnePlus 3
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@ceoger the Android app is meant to use the Magic link button, there's no manual entry as this method should work 99% of the time. 

We are also moving away from the magic link/verification codes and will be allowing verification directly on LBRY.io. Closing in favor of https://github.com/lbryio/lbry-android/issues/384 ( just opened, but most of the work is already completed on the api/app - which will be re-used here).
