### ISSUE TITLE
Email verification on lbry.io instead of device

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#384]
## The Issue
Android side issue for: https://github.com/lbryio/lbry-desktop/issues/1299 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
The Desktop app is already using this, should support on mobile ASAP. We'll need to modify internal APIs when this is ready for testing (can do it based on version).

**Comment by akinwale** [comment]
Done.
