### ISSUE TITLE
Allow videos to play in the background

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-android#388]
I sometimes use my phone to listen to things while walking or falling asleep. I used the LBRY app this morning while walking, sometimes I use YouTube. Both have the same problem for this use case, which is that if you navigate away from the app, videos stop playing. YouTube lets you listen in the background but only if you upgrade to a paid version.

This can get extremely annoying because if I leave the app open in my pocket, and then want to reach into my pocket to do something with my phone, I accidentally pause the video, click other videos, seek around in the video and lose my place, etc etc. It also means draining the battery because the screen is on the whole time.

I would love to see an option in the LBRY Browser for Android that allows videos to continue to play when you navigate away from the app. This would be useful at least for me and hopefully for many others. I am also guessing it would not be too hard to do.

**Comment by skhameneh** [comment]
Thanks for the excellent suggestion @eggplantbren!

I thought we had an issue filed on this (apparently we don't, I just verified) and it's good to know what our users want.

**Comment by eggplantbren** [comment]
Closing because this is already an option. Sorry for the bother.

**Comment by tzarebczan** [comment]
@eggplantbren thanks for filing this! This feature is already available under Settings. We could do a better job as alerting users that this is a feature that's standard in the app - hopefully we can get some mini tutorials going in the future :)

**Comment by kauffj** [comment]
Given that it was not obvious this was possible (expecting users to go into settings is somewhat unreasonable), this ought to be improved. @tzarebczan can you look at what the YouTube app or other apps do and file an issue? Maybe default to play in background but prompt/ask the first time it happens?
