### ISSUE TITLE
Android 6 - error when sending log

### ISSUE THREAD

**Issue by blcx** [lbryio/lbry-android#390]
### Steps to reproduce
1. Go to about 
2. Click send log 
3. (Error red screen) can't go back  ,  app freeze. Only option for force close

### Expected behaviour
Tell us what should happen
Send log file option

### Actual behaviour
Tell us what happens instead
Red error screen

## System Configuration
- Device:
- Android version:
Android 6, 

## Screenshots

https://spee.ch/f/Screenshot2019-01-09-21-50-24-904iolbrybrowser.undefined

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for finding and filing this! @ykris45  confirmed on his older phone too. Sent ya some appreciation on Discord.

**Comment by akinwale** [comment]
Fixed.
