### ISSUE TITLE
Feature request: Subcription Button on channel page

### ISSUE THREAD

**Issue by toktoakhil** [lbryio/lbry-android#393]
## The Issue
 I should be able to sub/unsub to a channel from the channel page

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@toktoakhil thanks for filing this! Per our Discord chat, there's really no "channel info" yet - we're planning to add profiles sometime in 2019. The sub button is a great idea though!

**Comment by tzarebczan** [comment]
Closing in lieu of https://github.com/lbryio/lbry-android/issues/393
