### ISSUE TITLE
Next/Prev button on channel page is consuming more space on the screen

### ISSUE THREAD

**Issue by toktoakhil** [lbryio/lbry-android#394]
## The Issue
Next/Prev button on channel page is consuming a lot of space and it is unwanted
### Steps to reproduce
1.Browse to a channel page and see
2.
3.

### Expected behaviour
Next/Prev button on channel page should act just like LBC credits balance shown on the homepage.

### Actual behaviour
Next/Prev button on channel page is consuming lot of space on the screen

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
Could you please add screenshots? Thank you

**Comment by tzarebczan** [comment]
The buttons cut off part of the tile, I think that's the main complaint. It's probably worse on smaller / lower res screens.
 
![screenshot_20190122-181451](https://user-images.githubusercontent.com/8120721/51571922-a632de00-1e71-11e9-87d6-22f5dfdb1b1b.jpg)

**Comment by akinwale** [comment]
Fixed.
