### ISSUE TITLE
Wallet encryption flow on Android

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#395]
## The Issue
Similar to how we allow wallet encryption/decryption on the Desktop app, we should allow users to do so on Android. This will also ensure users can sync encrypted wallets between desktop/android. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
closing per @akinwale
