### ISSUE TITLE
relative published times on show pages / tiles

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#396]
## The Issue
Similar to the desktop app, we should add relative published times (i.e. 1 day ago) to anywhere we show claim data. See app side/redux for implementation details

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
