### ISSUE TITLE
There is no Custom reward when redeemed all rewards already

### ISSUE THREAD

**Issue by namujan78** [lbryio/lbry-android#398]
## The Issue
There is no Custom reward when redeemed all rewards already

### Steps to reproduce
1. Claimed/Redeemed all rewards in Android app
2. Go to "Rewards" tab again

### Expected behaviour
Can see Custom reward function to redeem reward code

### Actual behaviour
Cannot see custom reward to redeem reward code
![nocustomreward](https://user-images.githubusercontent.com/37721875/51222912-4076bb80-1972-11e9-8215-093744a8634c.png)

## System Configuration
- Device: Redme 5A
- Android version: 7.1.2
- App version: 0.3.1
![version](https://user-images.githubusercontent.com/37721875/51222917-453b6f80-1972-11e9-9d70-cf3136062b6e.png)

### Acceptance Criteria
1. Can see Custom reward function when redeemed all rewards already
2. Can see Custom reward function when there is still unclaimed rewards

### Definition of Done
- [ ]  Tested against acceptance criteria

**Comment by tzarebczan** [comment]
Thanks for filing this @namujan78! You are our new tester with all claimed rewards :)

**Comment by namujan78** [comment]
> Thanks for filing this @namujan78! You are our new tester with all claimed rewards :)

Thanks & Sorry for late filing the issue

**Comment by akinwale** [comment]
Fixed.
