### ISSUE TITLE
More subscription view options

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#399]
## The Issue
Similar to https://github.com/lbryio/lbry-desktop/issues/2190, but for Android. Right now we only have latest by date.  This would also include matching the app experience with marking videos as new. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
