### ISSUE TITLE
Use icon that is just an icon (no "LBRY")

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#401]
Mobile icons typically just include the graph, not text. The text is already below the icon and provided by Android.

**Comment by kauffj** [comment]
@akinwale can you be clear about what specific asset (size, format, etc.) you need to complete this?

**Comment by akinwale** [comment]
@NetOperatorWibby I uploaded the icon assets on Slack. Need to remove the LBRY text and change the shade of green to match the current shade in the app.

Thanks.
