### ISSUE TITLE
Reduce or eliminate UI unresponsiveness

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#406]
I'm not sure if this is a threading issue or what, but it's fairly easy to get the app into a state in which the UI is unresponsive at least briefly.

Sometimes just playing a video is sufficient.

**Comment by tzarebczan** [comment]
Noticed this as well. Was going to reopen https://github.com/lbryio/lbry-android/issues/296, but the new issue is good too.

Commonly happens when you watch a video and then go back. Or if you open the menu, quick switch out and back in.

**Comment by kauffj** [comment]
@tzarebczan please be on the look out for performance related comments (positive or negative) after 0.8.x release.

@akinwale says we do not have firm performance metrics and are still relying on anecdotes
