### ISSUE TITLE
Fix back navigation on file page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#416]
## The Issue
When you go to a file page, clicking back always take you back to explore. This is not expected when you are coming to the file page from a channel or subscriptions.
From Akin:
```For going back to discover, that's because the file page is designed to always return to discover because they're in the same "stack" navigator. I'll see if there's a way I can alter this behaviour when the start point is Trending. For the Prev / Next buttons, the back button is not connected at all to this.```

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by robvsmith** [comment]
This came up in the reviews on BetaTesting.com a few times. Making a note here instead of making a new ticket.

**Comment by akinwale** [comment]
Fixed.
