### ISSUE TITLE
Add feature to support opening files externally

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#419]
## The Issue
Not all content downloaded in the app can be viewed internally, so we should allow an option to open the content externally with whatever apps the user may have installed. i.e. if I download a PDF,I should be able to open with a pdf reader. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by toktoakhil** [comment]
Also add an option for explicitly setting the download folder for LBRY on Android. This will let them easily open the downloaded content easily using the android file browser easily.

**Comment by kekkyojin** [comment]
#1045 fixed this. May someone close this bug report?
