### ISSUE TITLE
Unresponsiveness after update / viewing / downloading content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#421]
Spoke to @akinwale about this last week - a few users on discord experienced very poor performance after the latest android app update. Not sure if it's related to a long running install (lot of cache?) or something not being cleared during an update, but clearing app data has helped them. Need to investigate why this is happening. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
I experienced this today and so have a couple other users. This should be bumped in priority. Not sure if it's related to cache or having multiple downloads. The UI does seem to lockup during SDK calls, but it's hard to tell.

**Comment by tzarebczan** [comment]
One user that experienced this had it go away after deleting downloads, but it would come back after minimizing/reopening the app (then clear up after about 30 seconds). After clearing app data, the delay after minimizing goes away. So part of the problem is download data related, but there are still issues between upgrades until app data is cleared.

**Comment by tzarebczan** [comment]
After testing with more downloads, I'm seeing more unresponsiveness. Sometimes it's definitely in the UI - for instance - I just loaded a video, it started playing, but the video was not moving (but audio was playing) and progress bar did not update until 6 seconds in. 

Some questions:

When you call file list on the claim pages, is it called with the parameter for that particular claim? 

Do you call file list by itself anywhere? If so, when? 

Any other calls happening in the background repeatedly beside account_balance?

**Comment by alyssaoc** [comment]
also seen in user videos, And could be related to the SDK not handling multiple downloads well...maxing out the user's connection (lbryio/lbry#1971)

**Comment by tzarebczan** [comment]
Nope, that's a different issue. This is after the downloads are already completed

**Comment by kauffj** [comment]
@tzarebczan we are expecting the next release addresses this. Please re-open if you still see this.
