### ISSUE TITLE
Channel links on tiles/file pages go to vanity URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#422]
## The Issue
If you click on a channel link from a tile or file page, it goes to a vanity url and possibly not the one expected. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/424/commits/918a7e64bd0d244903b1f9ec65454d02be8eac64.
