### ISSUE TITLE
Add invites capabiltiy similar to desktop app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#429]
## The Issue
Add ability to send / claim invite rewards like we do on the desktop app. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
With lbry-desktop and lbry.tv getting a revamped invites process, it makes sense to bring this to Android too.
