### ISSUE TITLE
Allow subscription to multiple channels from suggestions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#437]
## The Issue
From the subscription suggestions page, we allow users to click subscribe on a number of channels, but this list disappears once a single one is subbed to. On the desktop app, we let them sub to multiple and then have them click a button to view them, instead of going directly to the sub page with the newly subbed channel. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
