### ISSUE TITLE
Show fewer videos per featured channel and/or add horizontal scrolling

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#445]
The "Explore" area feels fairly difficult to use because it is a long vertical list of ~100 pieces of content. Scrolling through it is difficult to even see the breaks when the channel changes (though you can notice when the channel changes in the tiles).

We should explore alternative designs and approaches here. One to consider is to mirror the desktop experience, where only one tile per creator is shown, and use horizontal scrolling to see more videos.

**Comment by alyssaoc** [comment]
youtube app does horizontal scrolling
