### ISSUE TITLE
Bypass suggested searches and go right to search results

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#447]
Per discussion on meeting, go right to search results as the user types, with an additional call-out card for the exact URL resolution shown above results.

**Comment by robvsmith** [comment]
From the reviews - SaintlyNexus51 had an issue where search returned "No Results" for about a second before populating. Not sure if that warrants a ticket, or if commenting here is appropriate.

I would rather err on not creating too many tickets. Let me know if that is different from this @kauffj @akinwale or if it could be included in the AC for this ticket.

**Comment by akinwale** [comment]
@robvsmith That's a different issue. I'll file it and see if I can reproduce. Thanks.
