### ISSUE TITLE
Explore Page Channel Display

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-android#451]
As a user, on the Explore page I must scroll a lot to find the next channel of content. This means that if I don't find the featured content to be interesting, I am likely to back out and not come back.

Instead, I should see the most recent video, and have an option to explore that channel further with a button.

This means one video per channel on the Explore page in Android. I swipe, I see a video from a different channel.

**Comment by tzarebczan** [comment]
Similar to https://github.com/lbryio/lbry-android/issues/445 ? Can probably close one of them...

**Comment by robvsmith** [comment]
Fair enough! Closing as the same as #445
