### ISSUE TITLE
Videos Keep Playing In Background

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-android#452]
Seen in user SincerePuffins' video at roughly 4:30 (and a few other places that I did not note) - users sometimes watch a video and navigate away from the video, only to have the audio continue to play.

**Comment by tzarebczan** [comment]
@robvsmith - haven't watched all the videos - but did they navigate to another page in the app, or to another app? If background media playback is enabled, the video will keep playing if minimized.

**Comment by tzarebczan** [comment]
Just watched it - that one happened when the video seemed to time out after the user went into the search. So it said it failed but actually downloaded? Not sure. He did have other downloads going in the background....

**Comment by tzarebczan** [comment]
Probably the same as https://github.com/lbryio/lbry-android/issues/352

**Comment by alyssaoc** [comment]
closing for #352
