### ISSUE TITLE
Prolonged Usage Issues In Android

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-android#453]
Users who tested the app with a session of longer than 4 minutes had a consistently degrading experience.

The likelihood of a video loading slowly increased, as well as the likelihood of a failure to load.

See SincerePuffins video, and any others that were over 5 minutes long.

**Comment by tzarebczan** [comment]
Probably similar to https://github.com/lbryio/lbry-android/issues/421

**Comment by tzarebczan** [comment]
And could be related to the SDK not handling multiple downloads well...maxing out the user's connection (https://github.com/lbryio/lbry/issues/1971)

**Comment by alyssaoc** [comment]
closing for #421
