### ISSUE TITLE
Stop Download Lacks Prominence

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-android#455]
Consistent issue in the app is that the Stop Download button gets missed by the testers.

This means when people want to stop a download, they can't because they don't know the button is right there.

Possible solutions:

Alternate color - red or orange denote stopping/slowing down. Just on the text so its not too prominent/distracting.

Animated button - have the button wiggle after the player presses play to pull their attention to it for a moment. This could be a single second right-left wiggle.

**Comment by akinwale** [comment]
Downloading is no longer the default behaviour for videos and audio, so this shouldn't be a problem anymore.
