### ISSUE TITLE
Stop Download From Android Menu

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-android#457]
In review from WorthyPorch96 - tries to stop download from an Android screen outside of the app, and it doesn't stop the download.

This would feed into the prominence of the Stop Download Prominence ticket, but it should probably work if possible. We see multiple people try to stop the download this way.

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/lbry-android/commit/8fcf135280a29c81aa871ba1540ecdedfdfc1fb4.
