### ISSUE TITLE
Download progress freezes when app minimized

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#459]
## The Issue
Even though the download is still happening in the background, the progress locks up in the notification bar. It should be possible to allow it to keep updating like other apps (Chrome for instance) do, when minimized. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
