### ISSUE TITLE
No Way to Leave Settings

### ISSUE THREAD

**Issue by Coolguy3289** [lbryio/lbry-android#46]
If you go to the settings tab, the Menu button isn't there, so you can't re-open the menu to return to the home page. If you hit the back button on your phone, it returns you to your home screen, I'd suggest making the back button just return to the app's home page, and/or adding the menu button on the settings page as well.

![](https://cdn.discordapp.com/attachments/377895389992321064/429322698380935188/Capture_2018-03-30-12-54-53.png)

**Comment by akinwale** [comment]
@Coolguy3289 Thank you for all the issues created so far. I agree there needs to be an intuitive way to navigate back from the settings page. At the moment, you can swipe from the left of the screen to show the drawer menu.

Additionally, for future bug reports or issues, please include details about your device and Android version. We'll also be adding an issue template to the repository, which should also help.

**Comment by akinwale** [comment]
Fixed. You can now navigate back from the Settings screen using the back button on-screen, or the device's back button.
