### ISSUE TITLE
"Send a tip" broken when video playing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#460]
## The Issue
Nothing happens when you click send a tip and the video is playing. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
The margins need to be updated due to the URI bar now positioned at the top. This will be addressed as part of the fix for https://github.com/lbryio/lbry-android/issues/430.

**Comment by alyssaoc** [comment]
closing, duplicate
