### ISSUE TITLE
Video keeps playing when searching

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#462]
## The Issue
If you play a video and then perform a search, it keeps playing. Not sure if this is the same scenario as https://github.com/lbryio/lbry-android/issues/452

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
fix broader picture in picture issue #120

**Comment by akinwale** [comment]
Fixed.
