### ISSUE TITLE
Thumbnail slightly cut off on top/bottom

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#463]
## The Issue
If you compare the thumbs on Android vs the desktop app, you'll notice they are slightly cut off on the top and button. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Thumbnail aspect ratios have been adjusted for better display.
