### ISSUE TITLE
Loading icon when visiting content for first time

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#466]
## The Issue
Sometimes when visiting a claim for the first time, you get a loading spinner before the play button shows up. I believe this is when the claim is resolving related content + running a file_list. This could be avoided if we cached file list data so it didn't have to be called each time. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
I noticed download progress also stops updating on other files being downloaded when this occurs.

**Comment by akinwale** [comment]
Fixed.
