### ISSUE TITLE
More pre-fetching

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#471]
Can resolve of the "Explore" URLs begin as soon as the app opens / blockchain is current?

Can we begin resolving trending or subscriptions when the client is idle?

Can we pre-fetch in other areas / at other times?

The more app pages can load instantly, the better our app is.

**Comment by kauffj** [comment]
Related to #515

**Comment by akinwale** [comment]
App startup time has been significantly improved so this is no longer required.
