### ISSUE TITLE
Error when playing an mp3

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#476]
## The Issue
Sample file at lbry://mp3:
![Screenshot_20190307-163138](https://user-images.githubusercontent.com/8120721/54055419-04fead80-41bb-11e9-9ed6-e1d5ea36db0b.jpg)

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
This is fixed with the latest media player update. https://github.com/lbryio/lbry-android/pull/529
