### ISSUE TITLE
Save scroll position when navigating between screens

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#477]
## The Issue
When you navigate to a claim from Discover/Trending/Channel page, and then click back, it takes you back to the top of the respective pages. I want to be able to pick up where I left off on the previous page. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
