### ISSUE TITLE
Back button navigation issues (exits app sometimes)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#478]
## The Issue
These are the scenarios where I found the back button doesn't work as expected after the latest fixes. It will randomly just close the app after a few navigation steps, and then clicking back. One of the most consistent ways it happens is: go to a channel page, click first item, click back, then click 2nd item, click back...closes app. 

Also, when flipping between subscription views, the back button just goes to the previous page.

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
should be fixed

**Comment by tzarebczan** [comment]
There are still some edge cases with this which I got into recently (clicking back would not go to the screen I expected), but I can't repro. Will keep an eye on it.
