### ISSUE TITLE
Improve resuming from background

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#479]
## The Issue
When the background service is running, there's still a rather long (5 seconds?) startup process that goes that starting daemon (does it check if it's started? cause it's not actually starting it), waiting for name resolution (does it try a resolve to see if the sdk is responding?) and then finally you get the homepage. The resume function should be quicker since the sdk is already running. Should it also show a different splash screen in this case? 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
The startup process has been sped up when resuming from background. It only takes about a second for a hot start and 2 - 3 seconds for a warm start.
