### ISSUE TITLE
Gracefully shutdown SDK on close

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#481]
## The Issue
When LBRY is closed, we should try to gracefully shutdown the SDK by calling the stop command. Right now, it just abruptly closes the process. Terminating it like this can cause various issues with the databases. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
