### ISSUE TITLE
Re-work rewards and LBC onboarding area generally

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#482]
This ticket should not be considered just reworking rewards, but reworking LBC onboarding generally, of which rewards are a major component.

There are three reward statuses: verified, interested, uninterested.

A user starts as interested (but unverified).

### Wallet Area
- [x] Interested users with a balance of zero are shown a reward driver
- [x] Backup notice removed and/or dismissable
- [ ] Add card that links to https://lbry.com/faq/earn-credits (crib from lbry-desktop)
- [ ] Icons are too thick, a thickness level down would look better

### Rewards Area (Interested and Uninterested Users)
- [x] Landing area shows full page splash screen showing "n unclaimed LBRY credits" with icon (similar to current header, but full screen). 
- [x] Include a single onboarding sentence, normal size text: "LBRY credits allow you to purchase content, publish content, and influence the network" (possibly improve this)
- [x] Landing area shows a single primary button with text Enroll. Clicking this begins Verification Flow
- [x] Include a small button or just plain text that says "Not Interested". Clicking this marks a user's reward status as uninterested, the link no longer shows, and they are sent to Explore.

### Balance Overlay
- [x] Uninterested users are not shown the rewards prompt.
- [ ] Verified users with no unclaimed rewards are shown a rainbow or something else cool.

### Verification Flow
- [x] Verification flow is an independent page. While a user is engaging in verification, he is broken out of all app navigation flow entirely (no top bar, no navigation button, etc.), until verification is completed or exited. 
- [ ] After completing verification, a user is returned to where verification began from (typically rewards). 
- [x] Drop the "Humans Only" and accompanying text entirely
- [x] Verification steps match the style from first run

### Verification Step: Email (Collection)
- [x] Title: Email (instead of Pending Action: Verify Email)
- [x] Text: Please provide an email address.
- [x] Input + Submission

### Verification Step: Email (Verification)
- [x] Title: Verify Email (instead of Pending Action: Verify Email)
- [x] Text: An email has been sent to xxx@yyy.com
- [x] Two Actions (Buttons? Links?): Resend (I believe API supports this) and Edit (goes back 1 step)
- [ ] https://github.com/lbryio/lbry.com/issues/1033

### Verification Step: Phone (Collection)
- [x] Title: Phone Number
- [x] Text: Please provide a phone number to prevent fraud.
- [x] Input + Submission (current one is good)

### Verification Step: Phone (Verification)
- [x] Title: Verify Phone
- [x] Text: Please enter the code sent to xxx-yyy-zzzz
- [x] Two actions just like Email Verification step
- [x] After completion, go to Rewards and claim first reward.
- [ ] Maybe shoot a rainbow across the screen

### File Show
- [ ] Interested users with insufficient LBC are driven to rewards area when clicking play
- [ ] Possibly fix other bugs with clicking play with insufficient LBC

### Rewards Area (Verified)
- [ ] Drop empty circle for unclaimed rewards
- [ ] Claiming first reward seemed to be bugged?
- [ ] Custom reward claiming is wonky

**Comment by kauffj** [comment]
First task is to groom this ticket.

**Comment by akinwale** [comment]
Splitting off File Show and Rewards Area into new issues.
