### ISSUE TITLE
LBRY Notification doesn't open LBRY

### ISSUE THREAD

**Issue by Coolguy3289** [lbryio/lbry-android#49]
The Thin LBRY Browser Notification when tapped, doesn't do anything, my suggestion is making that button open the LBRY app.

![](https://cdn.discordapp.com/attachments/377895389992321064/429322507099570186/Screenshot_2018-03-30-12-54-00.png)

**Comment by IndianCryptoMiner** [comment]
I was about post this .Then saw this is already open .Yeah it feels irritated when we click on the notification tab expecting app will open and it does nothing.

**Comment by akinwale** [comment]
The service notification was displayed for testing purposes, and isn't supposed to launch the app. This will not visible in the next release. However, tapping on the download progress notifications should launch the app as expected.
