### ISSUE TITLE
Update "Welcome to LBRY" splash screen

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#506]
1. Drop the second paragraph about syncing with blockchain.
2. Add a graphic or animation of some kind (maybe @NetOperatorWibby @robvsmith or @jsigwart can help with this)

**Comment by alyssaoc** [comment]
@NetOperatorWibby @jsigwart  What do you think we could do here?

**Comment by kauffj** [comment]
@akinwale are you actively working on this? If not, can you unassign and return to groomed?
