### ISSUE TITLE
Faster app startup and resume

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#515]
After some experimentation with the app startup process last week, I was able to identify a couple of bottlenecks which could possibly be resolved with updates to the sdk.

* At the moment, the sdk `resolve` call is rather slow. This is currently being worked on, and there is a PR open for tracking this: https://github.com/lbryio/lbry/pull/2008. This should result in better performance and faster resolves which should enable the app startup faster (especially after first run).

* The sdk needs to be able to allow `resolve` to be called upon startup instead of having to wait for other components to be ready. An issue to track this was created. https://github.com/lbryio/lbry/issues/2029

**Comment by kauffj** [comment]
Also bundle the headers

**Comment by kauffj** [comment]
Also see #471

**Comment by kauffj** [comment]
Next steps:
- [ ] Defer all requests (and possibly more rendering?) on file/show until video plays
- [ ] Reduce re-renders on file/show page

**Comment by akinwale** [comment]
Closing this for https://github.com/lbryio/lbry-react-native/pull/129 and https://github.com/lbryio/lbry-react-native/pull/132.
