### ISSUE TITLE
Use range requests provided by SDK when playing media

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-android#523]
## The Issue
See lbryio/lbry-desktop#2452 for write up from desktop app side for implementation guidelines.

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
See https://github.com/lbryio/lbry-desktop/issues/2452 for write up from desktop app side for implementation guidelines.
