### ISSUE TITLE
Disable phone verification until email is verified

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#524]
## The Issue
If an existing user tries to enter a phone number before their email is verified, it will tell them it already exists. We should confirm their email before allowing them to proceed with rewards verification. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/lbry-android/pull/538.
