### ISSUE TITLE
Stop a file from playback after range requests

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#531]
At the moment, the sdk attempts to continue downloading blobs for streaming even upon restart. There should be a way to stop media that is being streamed when the user navigates away from that particular file page. All pending requests should also be terminated upon a fresh start of the sdk.

**Comment by tzarebczan** [comment]
This is noted as a bug on the SDK side and should be fixed. Downloads/streams should not restart unless the file was being saved and had not completed before restart.

**Comment by kauffj** [comment]
@tzarebczan can you link this issue with the SDK one?

**Comment by tzarebczan** [comment]
This should be working now. The regular file stop command should be used to cancel a pending save file command.

**Comment by tzarebczan** [comment]
Closing, please reopen if this is still happening.
