### ISSUE TITLE
Rework doPurchaseUri flow for playable media

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#533]
With range requests implemented, the `doPurchaseUri` flow has to be modified to handle the new /get requests for audio and video content, which are not downloads.

**Comment by kauffj** [comment]
@akinwale if this is not in `lbry-redux`, would it make sense to move it into there while doing this work?

@seanyesmunt says the desktop app is not using it yet. We can use standup tomorrow to get on the same page on this.
