### ISSUE TITLE
Wallet sync and restore not clear / other concerns

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#539]
## The Issue
These are my notes when going through the sign in process on Android:

1) You are forced to sync wallet when setting up an account on first run flow - is that expected? I can sign into an email after skipping this, so it is possible to have an account without syncing (see issue 4 below)  

2) We say "keep your content and settings synced" - I think we should mention "account".  

3) If I did skip the initial screen or have an existing account, how do I get back into the account sync flow? Create a separate issue for this or do we want to handle it now? If we don't want to handle, we need to understand what happens if I do sign back in and to make sure sync is not called.

4) If you skip setting up account, the sdk will throw "NoneType object has no attribute 'encode'" - i assume it's trying to call the sync function somewhere. 

5) When signing back into a synced account, there's no indication on the password screen that you should be entering your account password - it just tells you to create a new password which is confusing. 

6) When you do sign back in with the correct password, nothing will sync back until you verify your email. This is not clear from the UX. I think we should start/finish this process if someone is signing back into a synced account before they get into the app. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Notes after speaking to Jeremy:
1) Is email verification necessary to restore an account?
2) wallet sync doesn't start until email is verified,  should we be alerting them to email verification on app startup / after x amount of time?
3) Restore process must be better for first release - if their account can't be synced until they verify, we should guide them thought that before proceeding into the app?

**Comment by kauffj** [comment]
Putting in progress for this week, @tzarebczan please talk with @akinwale 1-1 to ensure you're on the same page.

**Comment by tzarebczan** [comment]
These have all been knocked out by @akinwale...still clearing up a few minor bugs but closing for now.
