### ISSUE TITLE
Handle sync flow for users with existing wallets

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#541]
1. Handle flow for users opting to enroll in sync later in the process
1. Handle (or except / drive to FAQ) the syncing of two active accounts (i.e. both with balances and/or channel keys).

**Comment by kauffj** [comment]
What if we do the following:

- If authenticated with an email, you have to enroll in sync. If a user upgrades the app and is already authenticated, they are driven to the password step of first run and can't skip it (or skipping it is equivalent to logging out).
- Add a card to the wallet representing sync status. If the user is authenticated with an email, this always says on. Otherwise, it says off, but attempting to turn it on simply begins authentication flow.
- Ensure that the password setting step is part of account creation, regardless of how it is trigger (i.e. the account flow trigger by rewards would add the password setting step as well, so that sync can be turned on).

**Comment by akinwale** [comment]
The planned approach is:
* Once a user provides an email address for verification, the user has to complete the verification before any other action can be performed in the app.
* The user can choose to cancel the verification process which will clear the email address and allow the user to use the app normally.

**Comment by akinwale** [comment]
Partly done. sdk changes required for treating all accounts in a wallet as a single account when obtaining the balance or spending.

**Comment by kauffj** [comment]
@akinwale will create a new issue with the remaining changes and then close this one.
