### ISSUE TITLE
Text on Download Screen was cutting off on some Android Phone

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#543]
## The Issue
the text is cut slightly on the right and left of the screen Lenovo Vibe K4 note 1920 * 1080 FHD screen resulution. it would be better if this writing was not cut off, LBRY Android Version 0.7.0. on Download Menu 

### Steps to reproduce
1. Install Push.Apk From build.lbry.io
2. Go to Download Menu
3. and see whats i meanly on screenshot below

## System Configuration
- Device: LENOVO VIBE K4 Note
- Android version: 6.0 Marshmallow
![Screenshot_2019-05-14-21-11-46-027](https://user-images.githubusercontent.com/26609573/57707212-6cd8e500-7691-11e9-8a5b-9c59a753c257.jpeg)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
