### ISSUE TITLE
App Crashes if see video from LBRY android Version 0.7.0

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#544]
## The Issue
App automatically closing and crash after watch video from publisher.

### Steps to reproduce
1. Download Push.Apk from build.lbry.io
2. Install App to Your Android
3. Watch featured content Eg Cryptocandor or Etc and lets see app closes automatically..
![Screenshot_2019-05-13-22-15-32-201](https://user-images.githubusercontent.com/26609573/57707599-15874480-7692-11e9-8440-e9e6c17dd7e5.jpeg)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration
- Device: Lenovo Vibe K4 Note
- Android version: 6.0 Marshmallow

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Chris said this works with the regular APK, closing for now. Kris, you can re-test when we have something ready to go.
