### ISSUE TITLE
Red screen with codes when i search my channel after that it went full white screen

### ISSUE THREAD

**Issue by seadox** [lbryio/lbry-android#545]
## The Issue

![Capture_2019-05-15-05-33-58](https://user-images.githubusercontent.com/38296486/57745209-89ded980-76cc-11e9-955d-0058b4f0333b.png)
![Capture_2019-05-15-05-34-30](https://user-images.githubusercontent.com/38296486/57745210-89ded980-76cc-11e9-949a-bb7f1d5beb3d.png)
![Capture_2019-05-15-05-33-04](https://user-images.githubusercontent.com/38296486/57745211-89ded980-76cc-11e9-8133-180808bcac76.png)

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This will be an issue with newly created or updated channels until we update the Android app to support the new sdk. We hope to get this out this week. 

Thanks for filing the issue, but closing for now. 

In the future, please include more information like the channel name.
