### ISSUE TITLE
Changes to Wallet Onboarding and Sync Status Display

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#551]
- Update the text of the warning on Wallet first run. Only show the second paragraph if sync is off. New text: 

This is beta software. You may lose any LBC that you send to your wallet due to software bugs, deleted files, or malicious third-party software. You should not use this wallet as your primary wallet. 

Because you are not using the LBRY sync service, you will lose all of your credits if you uninstall this application. Instructions on how to enroll as well as how to backup your wallet manually are available on the next page.

If you understand the risks and you wish to continue, please tap the button below.

- Drop the warning/acknowledgement at the top of the Wallet area (only use the first-run warning). Also, the yellow warning card with a green button on top is kind of ugly and should probably be avoided in general.
- Add a card to the bottom of the wallet area labeled "Sync & Backup". It should display your sync status, with an option to enroll or turn it on if it is off. Additionally, it should explain how to backup and link to the FAQ article that is currently shown in the warning header.

**Comment by kauffj** [comment]
@NetOperatorWibby curious on your opinion if the yellow warning is appropriate for the first-run acknowledgement at all or should be dropped in favor of a less loud style.

**Comment by NetOperatorWibby** [comment]
@kauffj I think it's fine. We want people to acknowledge it.

**Comment by akinwale** [comment]
@kauffj I feel like we can hide this paragraph in the warning if the user already has sync enabled:
> Because you are not using the LBRY sync service, you will lose all of your credits if you uninstall this application. Instructions on how to enroll as well as how to backup your wallet manually are available on the next page.

Could also change "Because" to "If".

**Comment by akinwale** [comment]
Done.

**Comment by kauffj** [comment]
@akinwale yes, my original text says to hide the second paragraph if sync is enabled :)

"If" is not appropriate since we know they are not using the service, but it's probably better to start the sentence with "Since" than "Because".
