### ISSUE TITLE
Allow deletion from file view history 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#557]
## The Issue
Files that are streamed end up in file list and cannot be removed currently. The Library section should should both streamed content (history) and downloaded/offline. There should be an easy way to delete one or multiple streams from Library.

On the desktop app, we have a multi-select/clear option for history. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
@tzarebczan can you pick either this or #309 and close the other?
