### ISSUE TITLE
Local settings don't persist

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#558]
## The Issue
@akinwale and I noticed an issue where local settings may not persist sometimes. This means you'll see the wallet warning multiple times, even after restarts, and sometimes wallet sync shows off (even though it's on). If you go through the enroll process again, it will ask for current password and turn back on. 

It does seem to happen when I kill the app without clicking back to exit sometimes. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
@akinwale says this should be fixed, please re-open if you see it again
