### ISSUE TITLE
Library sorting is backwards

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#559]
## The Issue
When working on the Library enhancements, make sure Library is sorted properly (newest on top). 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
This is currently working as expected in the current release. Please reopen if it reoccurs.
