### ISSUE TITLE
LBRY app just crashes upon start

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-android#56]
As alpha test participant I installed the app through Google Play on my phone and the app can not start. Just crashes on the home screen. I've reported the issue with the Android reporting feature. It is probably due to my older Android version 4.2.2.
I've tried several times and restarted the phone but nothing happens. 
I've also noticed that it does not install the app icon on the main screen but the icon is only visible in the application menu.  

![screenshot_2018-04-02-22-52-21](https://user-images.githubusercontent.com/10566738/38219235-f7485ff2-36d4-11e8-8174-eb2d59c6ae18.png)

**Comment by tzarebczan** [comment]
Thanks for filing this @LavRadis ! @akinwale / @finer9 once we know what minimum version of android is supported, we should add that info to the Playstore so it won't allow older devices to install.

**Comment by finer9** [comment]
That is more than likely the reason, thank you

**Comment by akinwale** [comment]
@finer9 Let's set the minimum version to 6 for now. I'll have to get my hands on an old device (since the simulator tends to be very slow) to be able to figure out why it's not launching.

**Comment by kekkyojin** [comment]
API Level 22. Low end device.

I am not a React Native developer, so I am currently unable to debug this.

Partial log of start-up crash:

V/NotificationService(  764): pkg=io.lbry.browser canInterrupt=true intercept=false
E/art     ( 3242): dlopen("/data/app/io.lbry.browser-1/lib/arm/libpython2.7.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "forkpty" referenced by "libpython2.7.so"...
D/PhoneStatusBar(  873): addNotification key=0|io.lbry.browser|1|null|10081
E/AndroidRuntime( 3242): Process: io.lbry.browser:service_lbrynet, PID: 3242
V/fb-UnpackingSoSource( 3224): locked dso store /data/data/io.lbry.browser/lib-main
I/fb-UnpackingSoSource( 3224): dso store is up-to-date: /data/data/io.lbry.browser/lib-main
V/fb-UnpackingSoSource( 3224): releasing dso store lock for /data/data/io.lbry.browser/lib-main
D/ViewRootImpl(  764): hardware acceleration is disabled, fakeHwAccelerated = false, HardwareRenderer.sRendererDisabled = true, forceHwAccelerated = false, HardwareRenderer.sSystemRendererDisabled = true, this = ViewRoot{ed25521 Application Error: io.lbry.browser,ident = 192}
V/WindowManager(  764): Changing focus from null to Window{1038db07 u0 Application Error: io.lbry.browser} Callers=com.android.server.wm.WindowManagerService.addWindow:2928 com.android.server.wm.Session.addToDisplay:174 android.view.ViewRootImpl.setView:645 android.view.WindowManagerGlobal.addView:289 
I/WindowManager(  764): Gaining focus: Window{1038db07 u0 Application Error: io.lbry.browser}
I/BufferQueueConsumer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:0,p:-1,c:199) setConsumerName: Application Error: io.lbry.browser
I/BufferQueueConsumer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:0,p:-1,c:199) setDefaultBufferSize: width=129 height=129
I/BufferQueueConsumer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:0,p:-1,c:199) setDefaultBufferSize: width=812 height=429
I/BufferQueueProducer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:2,p:764,c:199) connect(P): api=2 producer=(764:system_server) producerControlledByApp=false
I/BufferQueueProducer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:2,p:764,c:199) new GraphicBuffer needed
I/BufferQueueProducer(  199): [Application Error: io.lbry.browser](this:0xb77f8330,id:1392,api:2,p:764,c:199) new GraphicBuffer needed
D/AES     (  764):     process : io.lbry.browser:service_lbrynet
D/AES     (  764):      module : io.lbry.browser v101 (0.1.1)
D/AEE/LIBAEE(  764): shell: raise_exp(4, 3242, -1361051648, io.lbry.browser:service_lbrynet, 0x0xb8a6e438, 0x0x0)
I/AEE/AED ( 3266): [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 3242, tid: -1361051648, name: UNKNOWN  >>> io.lbry.browser:service_lbrynet <<<
V/AEE/AED ( 3266): dashboard_record_update() : rec->module = io.lbry.browser:service_lbrynet

**Comment by akinwale** [comment]
Published a new version which should work on Android 5.0 Lollipop and higher. Unfortunately, older Android versions are not supported.
