### ISSUE TITLE
Cannot change search text without switching pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#562]
## The Issue
Something must have broken with the way we handle search text after searching in a recent version. You can select, but it won't overwrite it until you switch pages / then retype. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed. Creating a new build.
