### ISSUE TITLE
Pasting the contents from clipboard by long press touch is not working

### ISSUE THREAD

**Issue by toktoakhil** [lbryio/lbry-android#568]
## The Issue
On the wallet send area we cant paste the address by long touching

I am attaching screenshot of the window
![Screenshot_20190601-143034-01](https://user-images.githubusercontent.com/11274633/58750153-4944d580-84ac-11e9-852b-59108f2251d3.jpeg)

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
From Akin:
https://github.com/facebook/react-native/issues/9958

https://github.com/facebook/react-native/issues/18926

**Comment by tzarebczan** [comment]
On some devices, it crashes the app too.

**Comment by vgm8** [comment]
I have the same problem: https://github.com/facebook/react-native/issues/18926#issuecomment-502645846

**Comment by akinwale** [comment]
Did some more digging into this and it looks like it pretty much has to do with the core tech we're using: React Native and React Navigation (https://github.com/react-navigation/react-navigation/issues/5476). This will have to be fixed upstream. As a temporary work around, I will add a paste button beside the wallet address field which will paste the text in the clipboard into the field.
