### ISSUE TITLE
Video keeps playing with background playback when app is closed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#583]
## The Issue
If you have background media playback enabled, minimize, and then close the app (or sometimes this happens on its own where it needs to reload), the video continues playing but there's no longer any controls for it.  If you reopen the app, it continues playing without any way to stop it. 

It also happens with background playback on/playing video and if you just close the app via tab menu also or if you click back twice from a video. If we do want this to work, the app state should return to the video. Or it needs to stop the video if closing the app. 

To kill the video now, the app needs to be restarted, closed and sdk manually quit from notification bar - and even then it doesn't stop sometimes (takes a minute for it to run out of range request data) 

There was also a time where I closed and when I came back, sound was missing from other videos until restart. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
should be fixed, re-open if you get reports or experience @tzarebczan
