### ISSUE TITLE
NSFW content is shouldn't show on discover page

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#61]
![screenshot_2018-04-06-00-51-22-061](https://user-images.githubusercontent.com/26609573/38383122-d862729a-3935-11e8-9817-c7e6d885f1d1.jpeg)

![screenshot_2018-04-05-20-42-55-984](https://user-images.githubusercontent.com/26609573/38382803-18cbbe82-3935-11e8-8202-55bbbb5a9baa.jpeg)
would be nice if NSFW Content should'nt showing in to discover page after unmarked NSFW on setting page..

**Comment by akinwale** [comment]
Thank you for your report. This may be due to the uploaded content not being marked as NSFW by the publisher. The NSFW overlay should display correctly over content that has been properly marked as NSFW.
