### ISSUE TITLE
There No shutter button to take a photo using camera on LBRY App Publish Area

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#611]
## The Issue
i test on Android Latest Release V 0.7.5, on publish menu. i try to publish my content through my sony xperia xz camera, but im confusing where a shutter button/icon located, would be nice if have shutter button on it. there only black area as my screenshot below.. if i clicked the black area its works to capture photo using camera.  
### Steps to reproduce
1. Install LBRY App V 0.7.5
2. Go to Publish menu and then click camera
3. Camera Works and see there no shutter button on it

## System Configuration
- Device: Sony Xperia XZ
- Android version: 8.0.0 Oreo/LBRY Android V 0.7.5

## Screenshots
![e7ddba3f-d03c-4ea4-ae29-4929953d8e41](https://user-images.githubusercontent.com/26609573/61954839-f6872600-afe3-11e9-8953-05415f4e6d07.jpg)
0.7.5

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed in latest release.
