### ISSUE TITLE
No Tip Unlock Button on transaction page (LBRY Android 0.7.5)

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#612]
## The Issue
I published some files via LBRY Android App V 0.7.5, then i inform to #lbry-android discord channel to everyone. and after that i received 1 LBC as tip on recent transaction page. and im confusing to unlocking tipping from my LBRY android app.
Because tip unlock button not available on transaction page.. so would be nice if has a tip unlock button on transaction page.
### Steps to reproduce
1. Publish some stuff on LBRY android latest version
2. after publish some stuff on LBRY Network
3. try to tip your content via Desktop app 
4. go to recent transaction on wallet page and see what happend. no tip unlock button

## System Configuration
- Device: Sony Xperia XZ
- Android version: Oreo 8.0.0 / LBRY Android 0.7.5

## Screenshots

![1e93e94a-32d0-4d9e-8625-3de1846cd77d](https://user-images.githubusercontent.com/26609573/61955447-3dc1e680-afe5-11e9-8e4b-b674702f11b9.jpg)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
We'd also need to consider other actions for deleting publishes/channels/supports.

**Comment by kauffj** [comment]
good ticket @ykris45

**Comment by akinwale** [comment]
Done.
