### ISSUE TITLE
Sliding menu quirks 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#615]
## The Issue
When swiping the menu, you get a strange in between transition and it gets stuck sometimes. See video - [libre.zip](https://github.com/lbryio/lbry-android/files/3436439/libre.zip)

Thanks Link for the video! 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.

**Comment by tzarebczan** [comment]
This is now back after we downgraded the package.

**Comment by tzarebczan** [comment]
This will be fixed in next release.
