### ISSUE TITLE
would be nice if this video player strected on landscape mode

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#62]
![screenshot_2018-04-05-04-47-36-355](https://user-images.githubusercontent.com/26609573/38383053-a6c53bf0-3935-11e8-9dd4-45665760a85a.jpeg)
Another thing is, the text description flows into the video 
![20180503_193145](https://user-images.githubusercontent.com/26609573/39582404-176c3780-4f18-11e8-85f6-85ae043d9ee8.jpg)

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/132.
