### ISSUE TITLE
Remaining publish and discovery fixes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#621]
- [x] BLOCKER: fix vanity resolution...can't get to lbry://jiggytom, and when I search jiggytom, I see the vanity url on top, and then it disappears. 

- [x] BLOCKER: if you choose an image/video and then click cancel, and then choose another, the publish page does not update. 

- [x] BLOCKER: rename hot to trending

- [x] BLOCKER: add isURIValid checking to channel names. 

- [x] BLOCKER: persist selector when going from explore to another page (i.e. clicking more from top explore goes to Hot for the 

- [x] back button navigation seems to have gotten worse (worse than previously filed bug). i.e. I'm on trending, then go to explore, clicking back takes me to an old channel page I was on.

- [x]  initial load of publish page image/video picker took like 30 seconds - does this try to load all images? Can we limit this?

- [x] Mature should not be advanced - this should be a Mature tag shown in pink like we do with the desktop app

- [x] URL checking for names/channels should happen in line, not as a snackbar. 

- [x] I was able to publish at `lbry:// ` - blank. Need to prevent this, these will break the desktop app. 

- [x] update redux branch with new list of recommended tags - this used to be sorted alphabetically, but now shows common tags first

- [x] need a way to at least delete publishes from file page. 

- [x] consider moving bid/url out of advanced, and make that section similar to Publishing on Desktop.

**Comment by kauffj** [comment]
A few split out into separate issues, remainder being prioritized for this week

**Comment by akinwale** [comment]
Finished everything!
