### ISSUE TITLE
Subscription sync  / local cache issue? Resubscribed to channels

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#623]
## The Issue
If you have subscriptions saved on Desktop and Android devices, you may run into a scenario where you unsubscribe on Desktop, but the subscription is stored locally on Android and you get re-subbed next time when running the app. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by auber262** [comment]
I experienced this problem recently and reported in the Discord. If you have unsubscribed on the app or desktop, you will need to do the same on both separately, The steps undertaken to recreate this are (in Android app):
1) Open app and navigate using the hamburger to 'subscriptions'
2) When the listing of your subscriptions appears click the channel name (the '@channel') in green below the description.
3) This links you to the actual video - but here it will show that you are not subscribed to the channel and display 'subscribe' + heart symbol. Often it will also show 'no content found' but after a few attempts will load it.
4) If you view it at the same time on desktop, you'll see you are subscribed and it will display the greyed-out broken heart symbol to unsubscribe.

Conclusion: there is a disconnect between the subscribe/unsubscribe function on the individual video page and its parent channel and so it is not syncing correctly on app & desktop.

**Comment by kauffj** [comment]
Will be fixed when we move this data into wallet and use sync process to keep it consistent.

**Comment by auber262** [comment]
That's great Jeremy thanks very much for the update.

kindest,

Mark

Mark Tomkins
Creative Director - Aubergine
.................................................
M: +44 (0)7810 753878
T:  +44 (0)1525 373020

Please excuse brevity and any typos - the message was sent from my phone on
the move.

**Comment by akinwale** [comment]
This has been addressed in the latest release with user settings sync.
