### ISSUE TITLE
URL bar spellchecking  - red underline

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#624]
## The Issue
Disable spell check in URL . Some users are seeing: 
![photo_2019-07-31_10-16-40](https://user-images.githubusercontent.com/8120721/62468521-42fcff00-b764-11e9-8400-d537679cab4c.jpg)

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
