### ISSUE TITLE
Add analytics events

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#627]
- Email provided
- Email verified
- Reward eligibility completed
- App version

**Comment by akinwale** [comment]
Is the last one supposed to be a distinct event? It seems like app version should be something that we could attach to every event (which is already being done automatically on mobile).

**Comment by kauffj** [comment]
@finer9 can you share the best way to do this?

**Comment by finer9** [comment]
The app version is already reported to Firebase/GA automatically for mobile.

**Comment by finer9** [comment]
Also email verify is already an event, only rewards might need to be added @akinwale ?

**Comment by akinwale** [comment]
The `first_run_email_verify` event is only raised when the user makes it to the email verification page in the first run process. I assume this new event would be after a user has successfully verified their email.

@kauffj could you confirm?

**Comment by kauffj** [comment]
I want distinct events for email provided and email verified.

**Comment by akinwale** [comment]
Done!
