### ISSUE TITLE
Added Exit/close menu on LBRY Android App

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#65]
![screenshot_2018-04-13-18-55-46-548](https://user-images.githubusercontent.com/26609573/38733563-8ca15746-3f4c-11e8-9502-932b97f8420f.jpeg)
 

## The Issue
Would be nice if lbry app android version have Exit/close menu . this can make alpha testers can quiting app by tapping on this menu.. 

## System Configuration
- Device: Lenovo Vibe K4 Note
- Android version: 6.0 Marshmallow

**Comment by kekkyojin** [comment]
NO. Please DON'T.

For exit, just press the HOME device button and find a way to exit the app, normally via the multitask list.

Exit buttons are against best practices in Android.

**Comment by akinwale** [comment]
Thank you for posting the issue. It is not standard practice to have an exit or close option in Android apps. You can either press the device's home button to return to your home screen, or the back button until the app is dismissed.
