### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#655]
Add i18n support using one of the available react native modules. Will need to evaluate the modules and pick a suitable one.

**Comment by kauffj** [comment]
Assigned to @kauffj to explain Transifex and how i18n works in desktop

**Comment by kauffj** [comment]
### How Translations Work On LBRY Desktop

#### Loading Translations
Translations are loaded from https://lbry.com/i18n/get/lbry-mobile/mobile-messages/<language>.json.  Store these however you like. For ease of use across web and desktop, the app does this somewhat crudely and writes them to `window.i18n_messages`. You can see the code for this [here](https://github.com/lbryio/lbry-desktop/blob/master/static/index-web.html#L33-L36).

The lbry.com translations URL will refresh every 8 hours. You can supply `?nocache=1` to force reload.

#### Rendering Translations
Rendering translations in the app happens one of two ways:

1. For strings without embedded JSX, via `__(message, args)`, which is defined [here](https://github.com/lbryio/lbry-desktop/blob/master/src/ui/i18n.js#L46).
1. For strings with embedded JSX, via `<I18nMessage>`, defined [here](https://github.com/lbryio/lbry-desktop/blob/master/src/ui/component/i18nMessage/view.jsx). `i18nMessage` uses `__` under the hood. 

Both of these files are relatively simple. If you using the same implementation, please move to a shared location. Certain aspects of `i18n.js` would need to become configurable if shared.

#### Adding Translations

`__` will write new messages to disk if running in a non-production environment. This file can then be committed to disk and should be pushed at build time to Transifex. On desktop, that is still being done manually, via the Transifex command line utility. Steps for that are [here](https://docs.google.com/document/d/1xhoiakNNpWIocPmkbW_JUGu98cBaYoMMAeGFDrP44LU/edit#heading=h.k6ybr0cae875). You can do this manually as well, use the Transifex API to do it, or use the Transifex utility and add the steps in the linked document to your build process.

**Comment by akinwale** [comment]
Finally done!
