### ISSUE TITLE
Can't restore with blank password

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#658]
I synced with a blank password and can't restore - tells me invalid password specified. Thanks to @seanyesmunt for spotting this.

**Comment by kauffj** [comment]
@akinwale says this issue is probably SDK side. Leaving this open and assigning to him until he confirms and opens ticket over there.

**Comment by tzarebczan** [comment]
Spoke to Akin and he'll try passing '' instead of null (SDK has issues with null values). 

We also ran into a user that was able to run a sync apply with blank password, but still ended up with wallet in locked state - not sure how that happened.

**Comment by tzarebczan** [comment]
Fixed in 0.8.4
