### ISSUE TITLE
Change Lbry. to LBRY on startup screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#66]
@tzarebczan commented on [Tue Apr 17 2018](https://github.com/lbryio/lbry-app/issues/1340)

## The Issue
Change to uppercase LBRY on the startup page. 

Is it used anywhere else? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

---

@seanyesmunt commented on [Tue Apr 17 2018](https://github.com/lbryio/lbry-app/issues/1340#issuecomment-382123509)

Already done

---

@seanyesmunt commented on [Tue Apr 17 2018](https://github.com/lbryio/lbry-app/issues/1340#issuecomment-382123667)

The android app is the one with Lbry.

**Comment by akinwale** [comment]
Done.
