### ISSUE TITLE
Add support for daily watch reward

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#664]
- Attempt to claim the reward after every watch (or add local logic to only ask every 24 hours).
- Update reward display to accommodate ranges (once the reward is live, /reward/list will return a property on rewards that indicates the amount)

**Comment by tzarebczan** [comment]
Will be claimable in 0.8.4 but the reward won't display the range.

**Comment by kauffj** [comment]
@shyba how come you didn't notice I assigned this to you by accident? :stuck_out_tongue:
