### ISSUE TITLE
Navigation path to first run to support hyperlinking into app / other missing routing?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#665]
We want to allow users to click a button from lbry.com after verifying their email to bring that back into the app. Today we have special hyperlinks like lbry://?discovery which open to the homepage, but this actually takes the user to the homepage even though they are still going through first run. So if I just verified my email and I'm on the password page, and then click the ?discover url, it goes straight to the explore page in a broken state. 

Need a navigation path that will re-open to the first run process, or wherever they left off. The desktop app uses /account - it would be good if Android used the same one. 

Also need to check what happens if the app is never run + one of these links are clicked - if a user didn't go through first run, it should still send them through it.

**Comment by akinwale** [comment]
If first run is never completed, the user cannot navigate to any of the other routes.
