### ISSUE TITLE
Add tip button to channel pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#666]
We recently added this on the desktop side.

**Comment by aditya1rawat** [comment]
Can I still do this @tzarebczan ? I'm interested in doing it for hacktober? Also can you clarify by what you mean on tip buttons?

**Comment by tzarebczan** [comment]
Check out the present icon that's on content pages - we'd want to add something similar on the channel page.

**Comment by killbotXD** [comment]
@tzarebczan I would also like to work on this one. Can you please attach an image of what the tip button should look like.

**Comment by tzarebczan** [comment]
There's one already on the content pages, it would be the same. 

Probably would go with the share button
