### ISSUE TITLE
Improve snackbar behavior / styling

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#687]
We show feedback via snackbars at the bottom of the screen, but they are white/grey and blend into the rest of what's on the screen.

**Comment by akinwale** [comment]
We're using toasts (https://developer.android.com/guide/topics/ui/notifiers/toasts) to display these notifications, and we are unable to change the styling within the app. The styling is affected by the user's OS theme.

**Comment by tzarebczan** [comment]
ah, I think I remember that. It sucks cause they can be easily missed. Can we use something else or close for now?

**Comment by kauffj** [comment]
My proposal is to match what YouTube does more closely. This would mean:
- Fix it to the bottom
- Use darker color with more contrast
- Support links
- Hold display longer

If the message is long or multiple lines, the height of the bottom element can last longer.
