### ISSUE TITLE
Random app crash when abandoning channels/publish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#692]
Got this when trying to select 2 channels to delete. Also happened when I deleted a publish. A user also ran into it when deleting from file page (he said it didn't delete the first time or something). I think it happens if it tries to delete something that's already not there. 

![Screenshot_20190926-121623_LBRY](https://user-images.githubusercontent.com/8120721/65732682-fe714e00-e098-11e9-9165-e8ea6b05bd55.jpg)

A user also ran into

**Comment by akinwale** [comment]
Yes, this occasionally happens when you try to delete the same item repeatedly. The item may still appear in the list, but it would have already been deleted. Need to implement a way of handling this properly.

**Comment by akinwale** [comment]
Fixed.
