### ISSUE TITLE
End of support for Python2

### ISSUE THREAD

**Issue by ju-sh** [lbryio/lbry-android#707]
## The Issue
Python2 is nearing it [end of life](https://pythonclock.org/). In a few months, it will cease to be maintained and chances of it being used further is not significant due to the popularity of Python3.

Kivy, used by this project, has pledged not to support Python2 from the year 2020 and already supports Python3.7.

Can we modify our code base to remove the parts that deal only with Python2 and embrace Python3?

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
We're already building against Python 3.7+.

**Comment by ju-sh** [comment]
@akinwale I didn't mean supporting Python3.7. I meant *removing* support for Python2. I saw the code checks for Python version and follows one path if Python2 is used and another when Python3 is used.

Is this Python2 support being removed as well?

**Comment by tzarebczan** [comment]
I believe you can remove it. Wanna take a shot at a PR @ju-sh ?

**Comment by ju-sh** [comment]
@tzarebczan  Yeah. I'll make an attempt.
