### ISSUE TITLE
Auto unlock wallet / apply sync with blank passwords

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#716]
On Desktop, we attempt a blank password for wallet unlocking / sync apply before prompting the user. We should do the same on Android - it feels weird to ask for a password and then tell them to continue with blank. 

I'll open a separate ticket that would support changing the password in the wallet page.

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/lbry-react-native/pull/88/commits/f1c48e734ebdcba2ad72f2be2ca218571c8b90f9.
