### ISSUE TITLE
App performance issues while searching and loading related content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#736]
The UI seems to lock up quite often while searching and navigating to file pages -  mostly while it's trying to resolve single claims. We could batch those actions to see if that produces a better experience.

**Comment by kauffj** [comment]
First step: @akinwale will look at tools that can provide more reporting about when/where/why lockups happen

**Comment by kauffj** [comment]
Changes that have happened:
- File page related data loads after video play starts
- Search claim result data returned from search engine
