### ISSUE TITLE
first run: autoclaim new_android reward and allow channel creation

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#739]
Similar to the desktop/web version, we should consider doing this during the first run process. The email reward does not require rewards verification, but there are cases where it still may not be claimable (in that case, don't allow channel creation).

**Comment by tzarebczan** [comment]
@akinwale this reward is now live: new_android - can be claimed without creating an email/account. Only for new users. Existing users that sign in, and haven't been reward verified(or are), can also claim it.

**Comment by tzarebczan** [comment]
Also, keep in mind that some areas of the app check for a min balance of 0.1 LBC. 

Should this also include channel creation on first run? Maybe nudge towards it?

**Comment by akinwale** [comment]
Done. We don't nudge for channel creation but it's an easy process for users at points required: invites, publishing, and eventually comments.
