### ISSUE TITLE
search results erroneously says nothing found

### ISSUE THREAD

**Issue by dhrunia** [lbryio/lbry-android#740]
## The Issue
Searching for something returns `There are no results to display for xxxx. Please try a different search term`. However, after a couple of seconds(slower or faster depending on internet speed) all the results are displayed correctly. Check the below screenshots for an expample

### Steps to reproduce
1. Search for something, slower internet connections for easier reproducibility 

### Expected behaviour
Should display the search results correctly

### Actual behaviour
Says nothing found first and then populates the results correctly after a couple of seconds

## System Configuration
- Device: Pixel 2 xl
- Android version: 10

## Screenshots
Initial search output:
![Screenshot_20191029-112621](https://user-images.githubusercontent.com/7869622/67768977-ec961880-fa53-11e9-8efa-bf2626b5d19e.png)

Final search output:
![Screenshot_20191029-120232](https://user-images.githubusercontent.com/7869622/67769000-f4ee5380-fa53-11e9-9fb7-b2cf2f6b5d02.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing this! Sent you some appreciation on Discord.

**Comment by akinwale** [comment]
Fixed.
