### ISSUE TITLE
channel title wrapping cutting off text

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#741]
See below. 

There's also clashing on the background, but not sure what we can do about that. Will file a separate issue for adjusting the display of channel covers. 

![Screenshot_20191029-165102](https://user-images.githubusercontent.com/8120721/67808216-a1d4ca80-fa6c-11e9-8bf5-addd4200437f.jpg)
vs 
![image](https://user-images.githubusercontent.com/8120721/67808191-92558180-fa6c-11e9-948c-6916aa8b72ad.png)

**Comment by akinwale** [comment]
Fixed.
