### ISSUE TITLE
Explore tag search doesn't update with new search / sometimes not shown

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#744]
![Screenshot_20191030-143749](https://user-images.githubusercontent.com/8120721/67888707-fe46f100-fb23-11e9-87e9-2af5ea3acbcf.jpg)

If you search something, and then immediately search something else, the explore tag section doesn't update. I also noticed one time I didn't see any explore section when doing this.

**Comment by akinwale** [comment]
Fixed.
