### ISSUE TITLE
Route all the things!

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#758]
Add more routes like subscriptions, Downloads, trending, etc to https://github.com/lbryio/lbry-react-native/blob/master/src/utils/helper.js#L13 

Would be nice to keep them similar to the app ones also: https://github.com/lbryio/lbry-desktop/blob/master/src/ui/constants/pages.js

**Comment by kauffj** [comment]
Every main navigation item should have a route.

If easy, add routing for prominent subareas (e.g. trending/top/new selects on major pages)
