### ISSUE TITLE
Reward re-work / re-design, including pagination

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#761]
1. Presentation could be improved.
2. Confusing tracking claimed vs. claimable
3. Easy to miss feedback that you earned a reward

**Comment by kauffj** [comment]
4. Make sure message returned by `/reward/new` is displayed to user

**Comment by kauffj** [comment]
Post #1141, this should include pagination support as well.

**Comment by akinwale** [comment]
Added filter links to the top of the page.
