### ISSUE TITLE
Quick skip in videos

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#764]
Users should be able to tap the sides of the video to skip forward/back.

**Comment by SimonSchubert** [comment]
Any news if you will implement the feature? Its my #1 on the youtube mobile app. And it would probably be #1 for many other users if they would just new about the 'hidden' feature.

**Comment by akinwale** [comment]
Added controls in https://github.com/lbryio/lbry-react-native/commit/b9dec86caefca4b72e071d922e87dbd4c5125fa9.
