### ISSUE TITLE
Notification sounds while downloading pdf

### ISSUE THREAD

**Issue by TheCrazyGM** [lbryio/lbry-android#765]
### Steps to reproduce
1. Find a pdf file
2. Download it
3. Notification sound on

### Expected behaviour
Download goes on in the background, even though it's not a supported file type to view in the app itself.
### Actual behaviour
It may be my imagination, but it seems to correlate to one "ding" per percent of file download

## System Configuration
- Device: Samsung J260
- Android version: 9 (with all updates

## Anything Else

This is in the beta version in the play store.

## Screenshots

None taken as it's an audio symptom. 
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/fb3a34c871c16aae8dc99aa6a895ab33a04309c4. You can also go into your app-specific notification settings to disable the sound on download notifications. The notification channel name is "LBRY Downloads".
