### ISSUE TITLE
Let (Bluetooth?) headphones' pause/play button affect the video playing.

### ISSUE THREAD

**Issue by CodingEagle02** [lbryio/lbry-android#770]
## The Issue
Unlike on, for example, YouTube, the pause/play button on my headphones does not pause or resume videos I'm watching.

### Expected behaviour
It would be quite convenient if this feature was implemented, as I would be able to quickly cease whatever I am watching/listening to without reaching for my phone.

## System Configuration
- Device: Samsung Galaxy A8 2018
- Android version: 9

## Anything Else

I have only tested this on my Bluetooth headphones, so I don't know whether regular head/earphones' buttons work.
I also know this feature is missing on the desktop application.

**Comment by harshgandhi** [comment]
This is the case with my wired headset/earphones as well. Using Redmi phone. Need this feature implemented.

**Comment by akinwale** [comment]
Done.
