### ISSUE TITLE
video randomly tries to download, notification won't go away

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#774]
User recently ran into a scenario where the video tried to download (which it shouldn't) and now the notification won't go away - even after shutting down the app / swiping it away (it comes back). 
![](https://media.discordapp.net/attachments/363049604461232148/648534274722758677/Screenshot_20191125-084336_Discord.jpg?width=139&height=300)

**Comment by akinwale** [comment]
I just ran into this recently. It's the same weird issue with the sdk trying to download a video that didn't successfully start playback, after a restart. The user can click the download notification which should open up the file page and stop the download and/or delete the file from there.

**Comment by akinwale** [comment]
This should be mitigated with the graceful SDK shutdowns, and the Stop action in the download notifications.
