### ISSUE TITLE
random errors on email approval

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#782]
I ran into this a while ago and a user just ran into it recently. 
![image0](https://user-images.githubusercontent.com/8120721/69764863-d4431780-113f-11ea-960b-59ca706c3a00.jpg)

**Comment by kauffj** [comment]
In progress conditional on validating it actually happens with any frequency

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-react-native/commit/d52436e8d420840015dc187620fd736ed937b31f.
