### ISSUE TITLE
Fix icon visibility in status bar

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#783]
![Screenshot_20191202-125518](https://user-images.githubusercontent.com/530774/69982798-47afa500-1503-11ea-95e0-6ac33561359b.jpg)
![Screenshot_20191202-125532](https://user-images.githubusercontent.com/530774/69982809-4aaa9580-1503-11ea-8316-f2b82340c52b.jpg)

**Comment by kauffj** [comment]
In the first screenshot, the icon is there, but white.

**Comment by kauffj** [comment]
@tzarebczan do you ever see this? @akinwale thinks it may only be OnePlus

**Comment by tzarebczan** [comment]
Yep, I do see the same. Never noticed that before.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/a1bc3fcd7e9df18bb8b81088dcd63405ec649339.
