### ISSUE TITLE
text slightly cut off in some areas

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#788]
I've seen this in the past but thought it was related to my device...but another user is noticing it as well. Can see it happening on the wallet sync section for the 2 S's in sync status, and C/e in connected email. 

![](https://media.discordapp.net/attachments/377895389992321064/652573765003247657/Screenshot_20191206-180126_LBRY.jpg)

**Comment by akinwale** [comment]
Fixed.
