### ISSUE TITLE
percentage for download does not update / no notification

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#795]
Try one of the unsupported types from @mime channel. 

There's also no notification of the download like we used to have.

If you navigate away and back, it updates.

**Comment by akinwale** [comment]
The `file_list` return format changed in one of the newer SDK versions. This is fixed in https://github.com/lbryio/lbry-react-native/commit/f47693fb35fcd56e40e84e032aab95caf7d3e97a and  https://github.com/lbryio/lbry-android/pull/809/commits/f8de8e25acc8741ea6e9ff77e7d8f46bf2292c09.
