### ISSUE TITLE
Error when view all transactions from wallet page

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-android#803]
## The Issue
When navigating to the 'view all' transactions link from the wallet page it gives a red screen error - screenshot attached.

App build version: 0.12.1. SDK: 0.50.1

### Steps to reproduce
1. Open app
2. Select main menu > wallet
3. Scroll down to Recent Transactions and click 'view all' transactions link

### Expected behaviour
It should open the full transaction history page.

### Actual behaviour
Result is error screen as attached. App crashes.

## System Configuration
- Device: Google Pixel
- Android version: 10

## Screenshots
![Screenshot_20191225-194432](https://user-images.githubusercontent.com/39855197/71450000-f2a52e80-2750-11ea-98fe-277a8dffe0b9.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Sorry for the trouble, does this happen every time or randomly?

**Comment by tzarebczan** [comment]
This might be an issue with larger transaction histories. @akinwale , mine just crashes when I click view all.

**Comment by auber262** [comment]
It's the first time I have noticed it tbh. Can't recall going to that in the Android app before so I can't say if it always does it but certainly has done it the last few times today of opening the app.

Thanks as always, and happy holidays!

**Comment by akinwale** [comment]
Fixed.
