### ISSUE TITLE
Add more wallet info breakdown

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-android#804]
# 

## The Issue
Display more detail in the the wallet - like the desktop showing amount staked in supports, tips & publishes.

### Steps to reproduce
1. Open Android app
2. Navigate to hamburger menu and select 'wallet'

### Expected behaviour
Wallet summary appears at the top in large green box.

### Actual behaviour
Wallet summary appears at the top in large green box but uses up a lot of space and this could be used to display how the wallet amounts are apportioned - in tips, supports, publishes.

## System Configuration
- Device: Google Pixel
- Android version: 10

## Anything Else
If this is not possible I recommend making the green box smaller - it doesn't need to be so large.

## Screenshots
![Screenshot_20191225-200124](https://user-images.githubusercontent.com/39855197/71450073-73185f00-2752-11ea-888b-de5cfbce4a99.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing, but please check in Discord or Github to see if it's duplicate first. Happy holidays!

Already filed under: https://github.com/lbryio/lbry-android/issues/733

**Comment by auber262** [comment]
@tzarebczan so sorry Tom, I missed that. I recall mentioning on Discord some weeks ago but couldn't recall or see a log of it. Apologies.
