### ISSUE TITLE
App home screen crashes after a long time of scrolling down

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-android#806]
## The Issue

When on home default screen of app > trending for everyone, when you scroll down quite a long way (about 8-10 full screen-lengths down) it errors with attached red error screen.

### Steps to reproduce
1. Load app
2. Hamburger menu > all content
3. Trending for everyone
4. Scroll down the screen about  #20 full screen depths - it will trigger the error page with top message 'URL cannot include a space'.

### Expected behaviour
It shouldn't error ;-)

### Actual behaviour
Standard red error screen as attached below with error message 'URL cannot include a space': 

## System Configuration
- Device: Google Pixel
- Android version: 10

## Anything Else
Is it possible that the error was triggered by an item pulling in a preview image or content file that tripped the error? Maybe bad file formatting?

It happened after 6 test tries - each time about 1 or 2 full page lengths after where pewdiepie was listed (as at 27th Dec)

## Screenshots
![Screenshot_20191227-181326](https://user-images.githubusercontent.com/39855197/71528338-3de94980-28d7-11ea-80d1-e1dbfd1b2788.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for opening the issue. This was recently fixed on the desktop app but hasn't made it into Android yet. 

@akinwale , for the next update, please make sure you are up to date on redux (this fix is currently in a branch that should be merged soon).

**Comment by akinwale** [comment]
Fixed in latest release.
