### ISSUE TITLE
Build for KitKat?

### ISSUE THREAD

**Issue by MoTLD** [lbryio/lbry-android#807]
Is there a technical limitation that prevents building LBRY for Android versions prior to 5? I'm using an old device running 4.4.4 and I'd like to get LBRY working on it, but I'm completely inexperienced with compiling Android apps and I don't want to start here if it's just going to be an exercise in frustration. Is it even possible?

Thanks!

**Comment by tzarebczan** [comment]
For now you can check out lbry.tv on mobile, I don't think we'll be supporting older OSes at the moment unless it's super easy.  You are welcome to give it a try if you are up for it.

**Comment by akinwale** [comment]
Android 5 is the minimum version supported by the build tools and libraries, so it's currently impossible to build for a version lower than this.
