### ISSUE TITLE
Repeated Call Error on loading channel

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-android#810]
## The Issue

When clicking through from Android app homepage (trending for tags I follow) through to lbry.social's top 100 weey channel report it flashes up a red message bar in the bottom of the app with the message 'already fetching URL....' which gets s tuck and won't go. Then when you select the back button it delivers a large red error screen relating to 'maximum update depth exceeded' screenshot for both attached

### Steps to reproduce
1. Navigate to lbrynomics-top-100#8
2. If you see the red lower browser bar error then
3. Press the app back button to trigger main error screen

### Expected behaviour
Post should load

### Actual behaviour
Errors as reported above

## System Configuration
- Device: Google Pixel
- Android version: 10

## Anything Else

I am connected to strong WiFi but also tried 4G mobile - same result.

## Screenshots

![Screenshot_20191230-095037](https://user-images.githubusercontent.com/39855197/71578298-7a8f8d80-2aef-11ea-95c9-d6456ef942dc.png)
![Screenshot_20191230-095018](https://user-images.githubusercontent.com/39855197/71578299-7b282400-2aef-11ea-86ec-f607a912102f.png)
#809 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by GAUTAMRAJU15** [comment]
[https://github.com/lbryio/lbry-react-native/blob/30246a189c06a7f470eb5ee6098c7129c12bfd73/src/page/file/view.js#L233](https://github.com/lbryio/lbry-react-native/blob/30246a189c06a7f470eb5ee6098c7129c12bfd73/src/page/file/view.js#L233)
 i think inside the componentDidUpdate they forget to add an edge case like this ... anyone here ?

**Comment by tzarebczan** [comment]
Thanks for filing, we'll look into this. Does it happen everytime on this claim? Others too? 

@GAUTAMRAJU15 thanks for chiming it - maybe try to give it a shot with a fix if you are aware?

**Comment by auber262** [comment]
@tzarebczan @GAUTAMRAJU15 it only happened on this claim as far as I can tell but to be fair, after it crashed a couple of times I didn't wander around the app much further on that session as I just thought that maybe a recent update needed a patch.

**Comment by GAUTAMRAJU15** [comment]
@tzarebczan sure mate

**Comment by akinwale** [comment]
Thank you for the report. This should be fixed in the latest release.
