### ISSUE TITLE
Add watch history

### ISSUE THREAD

**Issue by harshgandhi** [lbryio/lbry-android#813]
## The Issue
App should contain a watch history list. Been using the app for some time now and need to find a video watched some time back. No such feature exists currently.

### Expected behaviour
A section in navigation drawer below "All Content" with name "Watch History". Opens up a list of all the videos watched previously.

## System Configuration
- Device: Any
- Android version: All

## Anything Else
For privacy reasons, watch history can be made local by default and user can have option to sync with email if required.

### Acceptance Criteria
1. A section in navigation drawer below "All Content" with name "Watch History". Opens up a list of all the videos watched previously.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thank for opening this feature suggestion!
