### ISSUE TITLE
Video doesn't close when tap back button on the phone

### ISSUE THREAD

**Issue by BibaJhin** [lbryio/lbry-android#814]
## The Issue
Video doesn't close when tap back button on the phone
### Steps to reproduce
1. Go to 'Menu'.
2. Go to 'All Content'.
3. Launch video.
4. Tap back button on the phone.

### Expected behaviour
Video should fully stop.

### Actual behaviour
After tap back button on the phone video closed, but sound is still play.
It can be stoped only by restart the app.

## System Configuration
- Device: Mi Max 2
- Android version: 7.1.1

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Does this happen every time? Do you have background playback enabled in settings?

**Comment by BibaJhin** [comment]
This happen every time. 
Background playback disabled in settings.

**Comment by rainbowjaw** [comment]
I have the same issue.  For me it happens especially if i press back soon after starting a video.  The audio will keep playing even after navigating to and starting a another video (leading to sound from both to play at the same time)

**Comment by akinwale** [comment]
@BibaJhin @rainbowjaw Do you still experience this in the 0.12.3 release?

**Comment by rainbowjaw** [comment]
It happened to me two days ago (after the 22nd), i'm not sure when the update happened on my device to this version, but i'm unable to reproduce the bug at this point.  I'll use the app some more over the next few days.

**Comment by BibaJhin** [comment]
I checked up this. Update for app resolved the problem. Thx team!

**Comment by tzarebczan** [comment]
Sounds like some users are still running into this, re-opening. Could not reproduce on my device.

**Comment by tzarebczan** [comment]
This happened to me again recently and continued to play in the background.

**Comment by akinwale** [comment]
Definitely fixed.
