### ISSUE TITLE
Screen stays on in android 9

### ISSUE THREAD

**Issue by rainbowjaw** [lbryio/lbry-android#819]
## The Issue
Screen doesn't shut off in the menu or around the app. This makes sense if you are watching a video, but not for browsing the rest of the app. 

### Steps to reproduce
1. Open app
2. do nothing

### Expected behaviour
Screen should turn off based on system settings

### Actual behaviour
Screen stays on (wasting battery)

## System Configuration
- Device: Moto G7
- Android version: 9 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by rainbowjaw** [comment]
after restarting my phone I haven't had this happen to me again. I will emphasize that it wasn't happening in other apps at the time, so if no one else has encountered this it must be some edge case, or related to my phone only.

**Comment by akinwale** [comment]
Closing. Please reopen if you encounter this issue again.
