### ISSUE TITLE
Quiting app does not end playback

### ISSUE THREAD

**Issue by sjukfan** [lbryio/lbry-android#820]
## The Issue
I have play in background turned on and if I close the app it keeps playing in the background and there's no way to control the playback.

### Steps to reproduce
1. Enable background media playback
2. Start a video and have it play in the background.
3. Kill the LBRY app from the task manager.

### Expected behaviour
I expected the playback to end.

### Actual behaviour
Video keeps playing without any way to quit it. (Except for a forced stop from under the app setting.)

## System Configuration
- Device: Unihertz Titan
- Android version: 9

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing. This is a known bug and will be fixed in the next release.

Dup of https://github.com/lbryio/lbry-android/issues/814
