### ISSUE TITLE
Display names on channel pages continue past the edge of the screen when too long

### ISSUE THREAD

**Issue by BrodieRobertson** [lbryio/lbry-android#822]
## The Issue

When a display name for an account is too long it will continue off the end of the screen.

### Steps to reproduce
1. Visit a channel with a long name such as lbry://@BrodieRobertson#5

### Expected behaviour
The name should either be cut off or continue on to a new line.

### Actual behaviour
The name continues off of the edge of the screen.

## System Configuration
- Device: Realme 5
- Android version: 9

## Screenshots

![83101560_494089357917911_5004950738925780992_n](https://user-images.githubusercontent.com/30792656/73160494-12a58480-4139-11ea-80dd-44d9d577a001.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Fixed.
