### ISSUE TITLE
Use lbry.tv stream URLs when launching the app from a notification upon a cold start

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#823]
In cases where a user receives a notification when the sdk service isn't running in the background, the app takes too long to start up waiting for the sdk. To speed up the app load time for a better experience, we can use the lbry.tv stream url on the media player, and then the sdk can be used when it's ready.

**Comment by kauffj** [comment]
Please make sure that when this is released we will be able to clearly compare behavior of people who entered via these notifications vs. those who entered via the previous mechanism.
