### ISSUE TITLE
Video does not stop if searching while viewing (other back bug too)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#827]
Play video > start a search > enter > video plays in background. Was able to get this to happen on my 2nd try.

If you go back, the video will be completely black while playing the audio.

**Comment by akinwale** [comment]
I am able to reliably reproduce this.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-react-native/commit/bf7f8364658b7872a8e36e02e17ae5656cdf9954.
