### ISSUE TITLE
no way of selecting a thumbnail when uploading a video

### ISSUE THREAD

**Issue by paju1986** [lbryio/lbry-android#829]
There is no way of selecting a custom thumbnail when uploading a video from the android app like on the desktop app.

**Comment by tzarebczan** [comment]
Click the edit icon in the thumbnail to do so. 
![Screenshot_20200130-073650](https://user-images.githubusercontent.com/8120721/73450429-5cf25580-4333-11ea-879a-ef4fddf81129.jpg)
