### ISSUE TITLE
Rendering of markdown code blocks doesn't work as expected

### ISSUE THREAD

**Issue by morngrar** [lbryio/lbry-android#830]
### Steps to reproduce
1. Open the app (version 0.12.3)
2. Go to: [lbry://@morngrar#9/codeblocks-test#1](lbry://@morngrar#9/codeblocks-test#1)
3. See what works, and what doesn't

### Expected behaviour
I'd expect all of the examples in the given publish to work somewhat like on the desktop app: resulting in a stylized box around the content, and preserving line endings within.

### Actual behaviour
All of the code blocks' content is printed on a single line, and there is no stylized box

## System Configuration
- Device: Sony Xperia H8324
- Android version: 10

## Screenshots
![screenshot](https://spee.ch/9/Screenshot20200130-164554)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Hi, thank you for your bug report. It appears the screenshot you included is invalid as I am unable to view it. Could you please upload another screenshot?

**Comment by morngrar** [comment]
> Hi, thank you for your bug report. It appears the screenshot you included is invalid as I am unable to view it. Could you please upload another screenshot?

Updated ;)

**Comment by morngrar** [comment]
And for reference, the source looks like this:

> 
>     # Testing code block rendering in android app
> 
>     ## Triple backtick syntax
>     ```
>         int main() {
>             printf("Hello, world");
>         }
>     ```
> 
>     ## Single backtick syntax
> 
>     `int main()`
> 
>     ## leading-whitespace syntax
> 
>         int main() {
>             printf("Hello, World.");
>         }
> 
>

**Comment by akinwale** [comment]
This works as expected with appropriate newlines in the native app rewrite. It doesn't display a stylized box container, however.

**Comment by morngrar** [comment]
What are "appropriate newlines"? 🤔 Do you mean '\r\n'? If that's the case, I wouldn't call the issue solved.

**Comment by akinwale** [comment]
I meant new lines in terms of how it's displayed in the web view.

**Comment by morngrar** [comment]
So typographic then. Is the update live on google play now, or hasn't it been pushed yet?

**Comment by akinwale** [comment]
It's live on the beta track. You'd need to enroll as a participant in the beta to be able to get that version.
