### ISSUE TITLE
F-Droid instructions / artifact

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#851]
Discussed in person, finished by midday Wednesday

**Comment by akinwale** [comment]
With the new build steps completed (https://github.com/lbryio/lbry-react-native/blob/master/README.md), building for F-Droid would require:
* Remove the Google Analytics and Firebase messaging dependencies from `build.gradle`.
```
implementation 'com.google.firebase:firebase-analytics:17.2.1'
implementation 'com.google.android.gms:play-services-base:17.1.0'
implementation 'com.google.firebase:firebase-messaging:20.1.0'
```
* Replace the constructor and the `@ReactMethod`-annotated methods in `io.lbry.browser.reactmodules.FirebaseModules` with empty placeholders, or stub in cases where a `Promise` is used.
* Remove `io.lbry.browser.LbrynetMessagingService`.
* Update `AndroidManifest.xml` to remove the Firebase references.
* Follow the necessary steps to request for F-Droid packaging.
