### ISSUE TITLE
transcode uploads

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbry-android#872]
High bit rate videos should be down-scaled before being uploaded. Here are notes on how to achieve that:

1. It's not necessary to deploy FFmpeg on Android. The Android APIs already have all the necessary functionality for analyzing and transcoding video. All modern phones have hardware-accelerated video transcoding built in. (This assumes that videos being uploaded from the phone were made on the phone and not elsewhere.)
2. The Android v10 API (level 28+) has a very nice video API. We assume that we cannot use this.
3. Any transcoding **needs to be done on a background thread** so that the UI can update progress. File analysis may also need to be done on a background thread; we are unsure at this point.
4. Things that the SDK presently verifies on a video file:
    A. Container is MP4 or WebM or OGV.
    B. Video encoding is H264 or VP8 or VP9 or AV1 or Theora.
    C. If Video is H264 we verify that the pixel format is yuv420p.
    D. Audio encoding is AAC or MP3 or FLAC or Vorbis or Opus.
    E. Faststart flag is set if container is MP4.
    F. Bit rate is below a customizable max, currently 8.4Mbps.
    G. Max volume is greater than -5 db and mean volume is greater than -22 db.
5. For now, make an assumption that none of the above are a problem except F. G will be difficult to test without FFmpeg, and modern phones should not produce videos outside any of the other parameters.
6. From the Android API we have MediaMetadataRetriever. The Retriever should be used to get the video resolution and duration and bit rate. The resolution and duration are needed by the Stream.update method in the SDK. (Don't let the SDK use Hachoir to get the width/height/duration.) The bit rate obtained there should be used for check #F above.
7. One way of lowering the video bit rate would be to lower the FPS. Some phones record video in 60 FPS or more. We can lower that to 30 FPS as one option. Another option is to reduce resolution to 1080p (or 1440p). In fact, you probably need both to get the bitrate down to a reasonable amount. 1080p@30FPS should be the target if the resolution is 1080p or more. 720p@60FPS should be the target if the resolution is 720p@120FPS or more. You need to use the MediaExtractor API to get the frames per second. That data is not available on the MediaMetadataRetriever (in the earlier Android API versions).
8. To transcode the video you need to use the MediaFormat and MediaMuxer APIs. Open the "video/avc" mime for the video encoder, set the max bitrate, possibly the average bitrate, the frame interval to 5, the frame rate to 30 or 60, the color format to COLOR_FormatYUV420Flexible. "avc" is phone-talk for H264. Almost all phones have a hardware-accelerated avc encoder (for the onboard camera). For the MediaMuxer, add all the tracks that are in the original video but replace the video track with the new one made from the MediaFormat object. Essentially, you want to copy all tracks but the video. For the video, you copy the old data into the MediaFormat object (one buffer-full at a time).
9. You're going to have to read through a lot of the examples on the web to see how to copy data into the MediaMuxer.

**Comment by BrannonKing** [comment]
The Codec Info app is a useful comparison, and it will show you which encoders are hardware-accelerated. See https://github.com/Parseus/codecinfo

**Comment by akinwale** [comment]
Transcoding implemention done using mobile-ffmpeg (https://github.com/tanersener/mobile-ffmpeg) in native app publish interface.

**Comment by BrannonKing** [comment]
Did you verify that the mobile-ffmpeg implementation uses the hardware encoders? It's important that the transcoding doesn't happen on the phone's CPU.

**Comment by akinwale** [comment]
As far as I could tell, ffmpeg does make use of MediaCodec on Android which is hardware accelerated.

ffprobe was pretty instantaneous as it returns media info in less than a second, and I was able to test the transcode using the ultrafast preset with pretty good results
