### ISSUE TITLE
Pending SDK loading missing , does not start with DHT mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#876]
@akinwale aware of the issue

- [ ] don't get message that the sdk is initializing
- [ ] In DHT mode, all systems are up but it gets stuck on starting up. 
- [ ] See "did you know you can earn 0.00 in credits" when this happens

What's strange is that even in DHT mode, it works on first startup, but not after. So if i reboot my phone, it will start up in DHT mode. And if I disable and reboot again, it shows initializing once.

**Comment by akinwale** [comment]
Fixed.
