### ISSUE TITLE
Native Java rewrite

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-android#877]
The UI unresponsiveness and occasional sluggishness with React Native have become frustrating enough to warrant a proper rewrite in native code.

**Comment by kekkyojin** [comment]
Best issue I have ever seen. React Native should have only been used for prototyping. I suggest you to begin with using native synchronization features from Android instead of an always running service. Let the system do its job so you always have some content ready to show the users.

**Comment by SimonSchubert** [comment]
I can only agree with both of you. Is Kotlin an option, too? What is the state of the iOS app? Maybe it's a good time to think about building a Kotlin multi platform project. https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/01_Introduction I have experience in building apps with kotlin mpp and could help out.
