### ISSUE TITLE
Don't self focus on the search bar when starting a new activity

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-android#879]
## The Issue
After updating to 0.15 on the Beta channel, cursor is focused on the search input box, which will always trigger the search fragment/activity. That makes the expected content not to be shown and a constantly updated result list to be shown, instead.

### Steps to reproduce
1. Open the app
2. Navigate to any sección, excepting About or Settings

### Expected behaviour
Expected content should appear

### Actual behaviour
A result list of the -unrequested- search is shown.

When browsing to Rewards, content loads but is quickly replaced by the Search Activity

## System Configuration
- Device: Xiaomi Redmi 5 Plus
- Android version: 8.1 MIUI 11
- LBRY 0.15 (from Beta channel)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by urza9814** [comment]
Are you able to actually use the app at all right now? I just updated to 0.15.2 on my LG V20 and I can't access anything now, all I get is a search box. I click the 'X' on the right side of the search, and nothing happens. I type a search term and hit enter, nothing happens. I try other tabs on the menu, all I get is search. The only things I can access right now are the Settings and About pages.

**Comment by kekkyojin** [comment]
yes, @urza9814. the workaround is to select the section you want to see on the navigation drawer of the left, then go to About and then navigate back. It works for most of the sections, including the wallet.

Latest minor updates fixed the problem for the opening activity when logged in, but it keeps unusable for other sections.

**Comment by akinwale** [comment]
Fixed.
