### ISSUE TITLE
Input field is hidden behind the keyboard while entering the reward code

### ISSUE THREAD

**Issue by e4drcf** [lbryio/lbry-android#889]
## The Issue
Input field is hidden behind the keyboard while entering the code
### Steps to reproduce
1. Open mobile app
2. Go to the rewards section
3. click on the custom code reward input

### Expected behaviour
Tell us what should happen
Input field is above the keyboard

### Actual behaviour
Tell us what happens instead
Input field is hidden behind the keyboard

## System Configuration
- Device: Redmi Note 5 
- Android version: 9 PQ1.180904.001

## Screenshots

https://www.youtube.com/watch?v=_NB_fUT_im8&feature=youtu.be
### Acceptance Criteria
1. User is able to read what he is writing.
2. An input field is above the keyboard.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Thank you for the issue report. This has been fixed and will be included in the next release tomorrow.
