### ISSUE TITLE
Crash Occurs when Uploading Video immediately after Install

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#890]
**DESCRIPTION:**
If the user attempts to upload a video immediately after installing and launching LBRY the app will crash.  The problem no longer occurs if you leave the app running for awhile before attempting to upload.

-----

**REPRO STEPS:**
1) Install LBRY 0.15.3 on Android 10
2) Launch LBRY
3) Navigate to 'Menu > New Publish'
4) Allow App access to local files
4) Select a video file

**Results:** Crash

**Expected:** Files begins uploading

-----

**ENVIRONMENT:**
Pixel 2 XL
Android 10
LBRY 0.15.3

-----

**MEDIA:**

![untitled2](https://user-images.githubusercontent.com/30788194/82837988-f4058f00-9e87-11ea-88d5-96ad1d94c3dd.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by cahlenlee** [comment]
This appears to be fixed in 15.5

**Comment by akinwale** [comment]
Fixed in 0.15.5.
