### ISSUE TITLE
Black Screen after selecting Report and returning to App

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#891]
**DESCRIPTION:**

Clicking the Report button on a video launches a new tab in a browser application.  When the user returns to the LBRY App using the Overview Button the screen is black.

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.3 on Android 10
2) Click on any video someone else published
3) Click 'Report'
4) Click Overview Button and select the LBRY App

**Results:** Screen is black 

**Expected:** Video page renders

-----

**ENVIRONMENT:**
Pixel 2 XL
Android 10
LBRY 0.15.3

-----

**MEDIA:**
![untitled](https://user-images.githubusercontent.com/30788194/82838491-a5f18b00-9e89-11ea-8d08-43ff8e797c3b.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by cahlenlee** [comment]
This appears to be fixed in 15.5

**Comment by akinwale** [comment]
Fixed in 0.15.5.
