### ISSUE TITLE
Clicking a Pending File in Publishes Menu shows Cutoff Message in Portrait Orientation

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#892]
**DESCRIPTION:**

The message which appears when clicking a Pending File in the Publishes Menu while in the Portrait Orientation results in a message that's not fully displayed.

"The claim is pending publish on the blockchain. You will be able to access or edit the claim in a few ..."

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.3 on Android 10 in Portrait Orientation
2) Navigate to 'Menu > New Publish > Upload a File'
3) Choose and submit an image file
4) Navigate to 'Menu > Publishes'
5) Click the Pending File

**Results:** Error message is cutoff

**Expected:** Error message displays in full

-----

**ENVIRONMENT:**
Pixel 2 XL
Android 10
LBRY 0.15.3

-----

**MEDIA:**
![CutoffMessage](https://user-images.githubusercontent.com/30788194/82839196-cf131b00-9e8b-11ea-9cb3-c4798f12712d.jpg)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by cahlenlee** [comment]
Still occurs in 15.5

**Comment by akinwale** [comment]
The default maximum number of displayed lines is 2, but this can be increased.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/898.

**Comment by cahlenlee** [comment]
Still occurs in 0.15.6
