### ISSUE TITLE
Text and Background Shift to Dark Theme after Viewing Video while Background Service Initializes

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#893]
**DESCRIPTION:**

If the user launches the app and quickly views a video and immediately backs out, the UI will shift to the Dark Theme.  Then if they open another video the Background will shift back to the default theme, but the text will remain white.

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.3 on Android 10
2) While Background Service Initializes, click on video
3) Click the Back Button (note black background now)
4) Click on another video

**Results:** Text in the UI is white, and background shifts back to non-night mode

**Expected:** Text in the UI is black, and the background never shifts to night mode

-----

**ENVIRONMENT:**
Pixel 2 XL
Android 10
LBRY 0.15.3

-----

**MEDIA:**

![etc-1498](https://user-images.githubusercontent.com/30788194/82845265-135ce600-9ea1-11ea-8531-bb42ec0c5a28.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in 0.15.5.

**Comment by cahlenlee** [comment]
Fix Verified in 0.15.6
