### ISSUE TITLE
Channel Links in Publishes Menu go to Wrong Page

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#896]
**DESCRIPTION:**

Clicking the channel links in the Publishes menu take the user to a page formatted for files not Channels.  The thumbnail is a large version of the channel icon, the Views show as 0, and the Channel is labeled Anonymous.  A load icon spins continuously over the thumbnail.

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.3 on Android 10
2) Navigate to 'Menu > Publishes'
3) Click on a Channel Link

**Results:** Taken to an invalid page

**Expected:** Taken to the Channel's profile page

-----

**ENVIRONMENT:**

- Pixel 2 XL
- Android 10
- LBRY 0.15.3

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82855330-41095580-9ec8-11ea-8f6c-0db1db9be43d.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Thanks for opening the issues - sent some appreciation over via our email convo!

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/898.

**Comment by cahlenlee** [comment]
Still occurs in 0.15.6

**Comment by cahlenlee** [comment]
Fix Confirmed 0.15.8
