### ISSUE TITLE
Double Tapping the Discovery Link Opens 2 Menus

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#897]
**DESCRIPTION:**

If the user quickly taps the Discover link twice, two menus will appear.  The top menu will be properly populated with channels.  Dismissing the top menu reveals a blank menu underneath.

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.3 on Android 10
2) Double tap the 'Discover' link
3) Tap Back Button when menus open

**Results:** Two menus opened, one is blank

**Expected:** One menu opens

-----

**ENVIRONMENT:**

- Pixel 2 XL
- Android 10
- LBRY 0.15.3

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82855784-7c585400-9ec9-11ea-8e54-2b57429fdb0d.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/pull/898.

**Comment by cahlenlee** [comment]
This still occurs in 0.15.6

**Comment by cahlenlee** [comment]
Fix Confirmed 0.15.8
