### ISSUE TITLE
Rewards Link in Wallet is Inactive after Activating and Dismissing

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#901]
**DESCRIPTION:**

On the Wallet page there is a prompt at the top asking the user to create an account to receive rewards. Clicking this the first time works, but if the user dismisses the window which appears, the rewards link no longer works until a restart.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.6 on Android 9
2) Click 'Use LBRY'
3) Navigate to 'Menu > Wallet'
4) Click 'Skip Account'
5) Click the blue banner at the top
6) Click 'Not Interested'
7) Click the blue banner at the top

**Results:** Nothing happens

**Expected:** Account creation prompt appears

-----

**ENVIRONMENT:**

- Galaxy S5
- Android 9
- LBRY 0.15.6

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82930780-27592400-9f43-11ea-8a66-c0e935df47ff.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Thank you for your report. This is fixed in https://github.com/lbryio/lbry-android/commit/c6a6ea0445d3ea1856a102f8bbc500ed4b7860ff and will be available in the next release.

**Comment by cahlenlee** [comment]
Fix Confirmed 0.15.8
