### ISSUE TITLE
Error Messages Flashes Endlessly after Denying Storage Access

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#902]
**DESCRIPTION:**

Denying the app access to file storage on the New Publish screen results in a flashing red message at the bottom of the screen.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.6 on Android 10
2) Navigate to 'Menu > New Publish'
3) Deny initial File Storage Access Request
4) Deny and Don't Ask Again 2nd Request

**Results:** Red error message flashes repeatedly

**Expected:** Red error message appears once and disappears

-----

**ENVIRONMENT:**

- Pixel 2 XL
- Android 10
- LBRY 0.15.6

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82932596-e9113400-9f45-11ea-8dd9-1383dfa981d1.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed. Will be available in the next release.

**Comment by cahlenlee** [comment]
Fix Confirmed 0.15.8
