### ISSUE TITLE
Back Button does not work on Email Signup Screen

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#903]
**DESCRIPTION:**

The Back Button does nothing on the Email Signup Screen.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.6 on Android 9
2) Navigate to 'Menu > Wallet'
3) Click 'Sign Up'
4) Tap the Back Button

**Results:** Nothing happens

**Expected:** Returns to Account Recommended screen

-----

**ENVIRONMENT:**

- Galaxy S5
- Android 9
- LBRY 0.15.6

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82934526-d2201100-9f48-11ea-8217-f7adaaedff0e.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
This is intentional, for properly handling the email verification process. In order to exit the sign in / up screen, you would need to use the close button at the top right.
