### ISSUE TITLE
Channels can Appear Twice or Not Appear on First Login

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#904]
**DESCRIPTION:**

If the user accesses the Channel page immediately after first logging into an existing account, the Channel List will occasionally contain two listings of the same Channel, and will sometimes not contain a Channel which should appear.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.6 on Android 10
2) Sign into an existing account with at least 2 channels
3) Navigate to 'Menu > Channels'
4) Navigate to 'Menu > Following'
5) Navigate to 'Menu > Channels'
6) Repeat 4 and 5 until Channels page has loading icon
7) Wait for Channels to load

**Results:** Sometimes the same channel is listed twice or a channel is missing

**Expected:** All channels appear once

**Note:** In the GIF below, the Wizard Studio channel is missing and the Cahlen Lee channel appears twice.  Sometimes Wizard Studio is present when Cahlen Lee shows up twice.

-----

**ENVIRONMENT:**

- Pixel 2 XL
- Android 10
- LBRY 0.15.6

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/82935447-4ad39d00-9f4a-11ea-855e-7a324e4ec83f.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
This is due to the wallet syncing, so we'll close and cover in https://github.com/lbryio/lbry-android/issues/900
