### ISSUE TITLE
Cannot Pause Video while Buffering

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#906]
**DESCRIPTION:**

The user is unable to Pause a Video which has stopped playing in order to buffer.  There are many reasons that a user may want to prevent a video from starting to play again once it's sufficiently buffered.  I can provide User Stories if requested.

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.6 on Android 10
2) Begin watching any video
3) Wait for video to stop playing to buffer (increasing playback speed is helpful)
4) Attempt to pause the video

**Results:** Impossible to pause the video

**Expected:** Video is paused

-----

**ENVIRONMENT:**

- Pixel 2 XL
- Android 10
- LBRY 0.15.6

-----

**MEDIA:**

![CannotPauseOnLoad](https://user-images.githubusercontent.com/30788194/82954869-d5c48f80-9f6a-11ea-86ad-52c9eb721df3.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Thank you for your report. Fixed in https://github.com/lbryio/lbry-android/commit/52e34b3027d8f24bde1450a9b363ed7b23fb8325 and will be available in the next release.

**Comment by cahlenlee** [comment]
Fix Confirmed 0.15.8
