### ISSUE TITLE
Picture-in-Picture has Still Background on Bottom Right Edges

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#907]
**DESCRIPTION:**

Minimizing LBRY while watching a video results in a Picture-in-Picture with a still image in the background on the bottom and right edges.

This occurs on my Galaxy S5 (Android 9) and not on my Pixel 2XL (Android 10).

-----

**REPRO STEPS:**
1) Launch LBRY 0.15.6 on Android 9
2) Begin watching a video
3) Tap the Home key to minimize LBRY
4) View the PiP

**Results:** Still image as background on right and bottom

**Expected:** Entire PiP frame is animating video

-----

**ENVIRONMENT:**

- Galaxy S5
- Android 9
- LBRY 0.15.6

-----

**MEDIA:**

![PiPBackground](https://user-images.githubusercontent.com/30788194/82955220-9480af80-9f6b-11ea-80ff-df39b1782027.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/c844c4f896933ec3a1688f80e83fe4f0a12d701b. Will be available in the next release.

**Comment by cahlenlee** [comment]
Fix Confirmed in 0.15.8
