### ISSUE TITLE
Non-Responsive UI after Blocking Storage Access in New Publish Menu

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#909]
**DESCRIPTION:**

Blocking storage access permanently in the New Publish menu and then rapidly tapping 'Upload a File'' causes the app to become unresponsive.  It clears up after awhile, but it can also get pretty bad, it even crashed once.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.8 on Android 9
2) Navigate to 'Menu > New Publish'
3) Permanently Deny Storage Access
4) Rapidly tap 'Upload a File'
5) Rapidly tap the 'Menu' icon in upper left

**Results:** App in non-responsive for several seconds

**Expected:** App remains resposive

-----

**ENVIRONMENT:**

- Galaxy S5
- Android 9
- LBRY 0.15.8

-----

**MEDIA:**

![etc-1500](https://user-images.githubusercontent.com/30788194/83049390-52597b80-a008-11ea-821e-574b85504e63.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/a8596829540181ba0b43f6bfbe972ee590336a36.
