### ISSUE TITLE
Unable To Load Paid Contents With No Discalimer

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#91]
## The Issue
When I try to play a paid content, when I click on the download, it loads for about a sec and displays the "download" again, I tried as many as about 10 times and it just tries to load for 1 sec and shows the download again,

### Steps to reproduce
1. Look for a paid content
2. Try to play by clicking download
3. It'll load in about a second and show the download option again, it'll keep recurring till you you don't 
try to play anymore.

### Expected behaviour
Tell us what should happen
If the wallet app is not added to the apha app yet, then maybe contents should be filtered so that paid
contents will not be displayed, 
or user can be prompted that the requested video cannot be played on the mobile app at the moment
since it's a paid contents and requires library credit.

### Actual behaviour
Tell us what happens instead

When I try to play this content, when I click on the download, it loads for about a sec and displays the "download" again, I tried as many as about 10 times and it just tries to load for 1 sec and shows the download again, Wanted to take a screenshot of the loading but it's so fast that I'm unable to capture it, and I think the reason is that this video is priced at 0.5 LBC but there's no information about it in the app

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0
https://cdn.discordapp.com/attachments/439055085616496640/441269835125489674/Screenshot_20180502-213605_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Fixed.
