### ISSUE TITLE
Flashing Error in Image Stream when Denying Storage Access

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#911]
**DESCRIPTION:**

Denying storage access to the app while viewing an image stream causes a flashing red error at the bottom of the screen.  

This is similar to the other bug #902 which occurred in the New Publish menu.  That bug is fixed, but this one still occurs.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.8 on Android 10
2) View any Image Stream
3) Permanently Deny Storage Access

**Results:** Flashing error message

**Expected:** Single error message

-----

**ENVIRONMENT:**

- Pixel 2XL
- Android 10
- LBRY 0.15.8

-----

**MEDIA:**

![FlashingErrorBlockStorageImage](https://user-images.githubusercontent.com/30788194/83065606-fea75c00-a020-11ea-9765-e1ed770a3a91.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/6c63eb7d66829dc90940a6844916b7c2ab597945.
