### ISSUE TITLE
Video is Upside Down after Switching to Landscape Mode

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#912]
**DESCRIPTION:**

If the user is watching a video in Portrait Orientation and rotates the phone to Landscape Orientation with the bottom on the left, the video will go full screen and then rotate itself upside down.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.8 on Android 10
2) Begin watching a video in Portrait Orientation
3) Rotate to Landscape with bottom of device to the left

**Results:** Video is upside down

**Expected:** Video is rightside up

-----

**ENVIRONMENT:**

- Pixel 2XL
- Android 10
- LBRY 0.15.8

-----

**MEDIA:**

![UpsideDownLandscape](https://user-images.githubusercontent.com/30788194/83068117-00731e80-a025-11ea-91ba-6f6173f5648d.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/83a41ca6ce2db9a569e29edeebee0a96044fbd42.
