### ISSUE TITLE
Channel Links on History Page Do Nothing

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#913]
**DESCRIPTION:**

The channel links on the History Page in the Library do nothing when clicked.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.8 on Android 10
2) Watch a video or image to populate history
3) Navigate to "Menu > Library > History"
4) Click a Channel Link

**Results:** Nothing happens

**Expected:** Channel page loads

-----

**ENVIRONMENT:**

- Pixel 2XL
- Android 10
- LBRY 0.15.8

-----

**MEDIA:**

![HistoryChannelLinks](https://user-images.githubusercontent.com/30788194/83068726-fe5d8f80-a025-11ea-933c-44fe3a2b34ba.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/3283b3a60738b9070b60f617660e72912002a61c.
