### ISSUE TITLE
Recent Files are Mostly Off-Screen on New Publish in Landscape Orientation

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#918]
**DESCRIPTION:**

When viewing the New Publish screen in Landscape Orientation, the recent files at the bottom are almost entirely cutoff.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.15.8 on Android 10
2) Navigate to 'Menu > New Publish'
3) Rotate device to Landscape

**Results:** Recent files are almost entirely offscreen

**Expected:** Recent files are on screen and accessible

-----

**ENVIRONMENT:**

- Pixel 2XL
- Android 10
- LBRY 0.15.8

-----

**MEDIA:**

![UploadLandscapeMode](https://user-images.githubusercontent.com/30788194/83071171-e7b93780-a029-11ea-8331-e2e6e7da0082.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by akinwale** [comment]
Landscape layouts are currently a work in progress. The screens will be redesigned as appropriate.
