### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by 7unkrat** [lbryio/lbry-android#925]
### Steps to reproduce
1. Logged in
2. Background service on
3. Commenting crashed the app

### Expected behaviour
Tell us what should happen
posting comment
### Actual behaviour
Tell us what happens instead
crashes

## System Configuration
- Device: NExus 6P
- Android version: 8.10

## Screenshots

[https://cdn.discordapp.com/attachments/363087331475062785/717512068315742298/Screenshot_20200603-005541.png](url)
### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Hi. Thank you for your report. What app version did this occur on and do you remember the amount?

Does it still happen if you have the latest version installed (0.15.11)?

**Comment by 7unkrat** [comment]
Normally the update apply automatically on my Android. Looks like 0.15.11 was on hold for updating, updated it, now works. Thanks for the reply.
