### ISSUE TITLE
Search results messed up when enabling mature content

### ISSUE THREAD

**Issue by alpabrz** [lbryio/lbry-android#927]
## The Issue
When mature content is enabled, somehow some content is simply not shown which should be otherwise shown. My guess is that only content flagged as mature is searched for, instead of all content (at least it seems like that). A video is included to demonstrate the unexpected behavior. I didn't encounter this issue on the LBRY application for Ubuntu.

### Steps to reproduce
1. Disable mature content in settings.
2. Search some term which doesn't show much content.
3. Remember which content is shown.
4. Enable mature content in settings.
5. Try to search the same thing again. Much lesser and different content or no content at all is shown, shown content seems to be more mature / NSFW (even when **not** tagged as such, but I don't know how LBRY's mature content selector works - whether it searches also through video titles for keywords).

### Expected behaviour
If mature content is enabled, it should be shown in the search results **additional** to the SFW content.

### Actual behaviour
Instead, some content  / all content is not shown except mature content (requires further testing??? some content is flagged as such, some is not: look down below).

## System Configuration
- Device: Huawei P10 Lite
- Android version: 8.0.0 (Build Number: WAS-LX1A)
- LBRY app version: 0.15.11

## Anything Else

Even reinstalling the LBRY app and logging out didn't fix the problem. On the LBRY application (Snap Version) on Ubuntu, the behavior is as expected (mature content is shown in addition to non-mature content).
I've included two videos (+ corresponding pictures) showcasing this weird behavior. The first one shows an example when searching for DASGeek, you'll see that the channel and associated videos are shown when mature content isn't enabled and that nothing is shown when it's enabled. The second one showed an example with the search term ASMR, where it seems that only mature content is shown when mature content is enabled. However, not all content shown is tagged as such, so I'm not sure what the underlying problem is. Any help would be appreciated.

**Thanks to the LBRY team for creating such a great service and making it available on so many platforms! And the attention they pay to their userbase :)** Also, this is my first ever filed bug report, so please do state criticism, improvements if I didn't express myself clearly.

## Screenshots

Search results for term _dasgeek_ with mature content disabled:
![dasgeek_not-mature](https://user-images.githubusercontent.com/31740882/83666245-ef9a4e00-a5cc-11ea-82d8-99dc03ae03b1.jpg)
Search results for term _dasgeek_ with mature content enabled:
![dasgeek_mature](https://user-images.githubusercontent.com/31740882/83666252-f032e480-a5cc-11ea-9291-b7a9de1f9a2a.jpg)

Search results for term _asmr_ with mature content disabled:
![asmr_not-mature](https://user-images.githubusercontent.com/31740882/83666254-f0cb7b00-a5cc-11ea-8c05-5dad1f82eb3d.jpg)
Search results for term _asmr_ with mature content enabled:
![asmr_mature](https://user-images.githubusercontent.com/31740882/83666256-f1641180-a5cc-11ea-8cf0-4d796551e531.jpg)

## Videos
Search term _dasgeek_:
lbry://search-term_dasgeek#85c1af9cffbad6b141cd4d6ebe556e5ecd897689

Search term _asmr_ (+ demonstrating that some videos are tagged as mature, others are not):
lbry://search-term_asmr#0

Sorry for my shitty editing skills.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thank you for filing the issue, we'll take a look into this.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/b36813ebe6aff49290a10870a8a031ff0d00e556.
