### ISSUE TITLE
Switching Full Screen Mode starts video all over again

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#93]
## The Issue
Video starts over again when switching to full screen screen mode
### Steps to reproduce
1. Download a video you wanna play
2. Start playing the video
3. Switch to full screen mode

### Expected behaviour
Tell us what should happen
video should continue playing from from where the user switches to full screen

### Actual behaviour
Tell us what happens instead 
when i'm playing the video in normal mode and i switch to full screen, the video starts from scratch, but when i switch back to normal mode it continues
confirmed again, watched about 15 seconds in the normal mode and switched to full screen and it started from the very beginning

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0

**Comment by akinwale** [comment]
Fixed.
