### ISSUE TITLE
Comment tips are taken from balance, even the comment not get through.

### ISSUE THREAD

**Issue by survivor303** [lbryio/lbry-android#945]
If user gets error that comment cannot posted, the tip of that comment are still taken from the user wallet/balance:

![Screenshot_20200624-174135789.png](https://user-images.githubusercontent.com/3097696/85579652-bab96e00-b643-11ea-803c-7d0083267589.png)

![Screenshot_20200624-174519378.png](https://user-images.githubusercontent.com/3097696/85579691-c311a900-b643-11ea-8684-8b68387a3c8b.png)

**Comment by tzarebczan** [comment]
We've removed the tip to comment feature.
