### ISSUE TITLE
Android alpha not connecting

### ISSUE THREAD

**Issue by tmsbrdrs** [lbryio/lbry-android#95]
### Steps to reproduce
1. Install app from either app or Google play store
2. Attempt to start app
3. Wait

![screenshot_20180502-203230](https://user-images.githubusercontent.com/8120721/39557588-b1ba691e-4e56-11e8-82a4-2b357e64a262.png)
### Expected behaviour
Tell us what should happen
App should connect
### Actual behaviour
Tell us what happens instead
App does not connect

## System Configuration
- Device:le eco3
- Android version:7.1.2

**Comment by tmsbrdrs** [comment]
I tried on both.

**Comment by tzarebczan** [comment]
@akinwale is there anyway to grab logs from the mobile daemon?

**Comment by tmsbrdrs** [comment]
The mobile daemon never starts.

**Comment by tzarebczan** [comment]
@tmsbrdrs the following what?

**Comment by tmsbrdrs** [comment]
Sorry, where should I post a screenshot?

**Comment by tzarebczan** [comment]
@tmsbrdrs The current app version is broken, but your logs still may be available in /sdcard/Android/data/io.lbry.browser/files/lbrynet/lbrynet.log or /internal/Android/data/io.lbry.browser/files/lbrynet/lbrynet.log - can you try using a file manager to navigate here? 

You can drag/drop images here and it will post the screenshot (use https://github.com/lbryio/lbry-android/issues/95 / don't reply on the email)

**Comment by tzarebczan** [comment]
@tmsbrdrs the latest version here should work again: https://github.com/lbryio/lbry-android/releases - let us know if you and run this and then provide the log file according to the instructions above.

**Comment by tzarebczan** [comment]
@tmsbrdrs can you try again with the latest build: http://build.lbry.io/android/latest.apk

If it's still not working, please see my previous comments in https://github.com/lbryio/lbry-android/issues/95#issuecomment-389323330 on how to find the log file.

**Comment by tmsbrdrs** [comment]
I just updated my Android version as well as the app and it's currently
connecting properly

**Comment by tzarebczan** [comment]
@tmsbrdrs glad to hear that! Closing this issue for now. Please comment here if anyone runs into it again.
