### ISSUE TITLE
Emojis missing in notifications

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#950]
These used to work in the previous version of the app. 
![Screenshot_20200628-152609](https://user-images.githubusercontent.com/8120721/86039247-30d91e80-ba10-11ea-815e-5b80e0364309.jpg)

**Comment by clay53** [comment]
Just sent a test notification to my device to investigate this and it seems to be working fine.
![image](https://user-images.githubusercontent.com/16981283/87327847-a0680700-c502-11ea-8e57-307ed8fb20b3.png)
Has this already been fixed?  
It could be a problem with how messages from Firebase are being sent out. This is how I set up the body for my text notification: 
![image](https://user-images.githubusercontent.com/16981283/87328043-ea50ed00-c502-11ea-85ff-12dbfb91689d.png)
It's also possible that the emojis being sent out are not supported by your device. I'm no emoji _connoisseur_ so I don't know about different emoji sets and stuff between different devices and versions but it may be worth looking into.

**Comment by tzarebczan** [comment]
This was my bad - some of our emojis actually got replaced with ? . Will fix!
