### ISSUE TITLE
Video description overlay on the player in landscape mode

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#96]
## The Issue
Video description overlay on the player in landscape mode

### Steps to reproduce
1. Download the video to be play
2. Change device screen rotation to landscape
3. Try scrolling the video description

### Expected behaviour
the description text should not go over the video

### Actual behaviour
part of he description text shows on the lower part of the video

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0

## Screenshots

https://cdn.discordapp.com/attachments/439055085616496640/441600463905751051/20180503_193145.jpg

**Comment by akinwale** [comment]
This was fixed in  https://github.com/lbryio/lbry-android/commit/48350ff17591dc833bea71141a3a86731f75d71d#diff-aab5aa68ab58b5a2593075935cd008eaL28.
