### ISSUE TITLE
View counter increments following download and page refresh

### ISSUE THREAD

**Issue by blackfireburn** [lbryio/lbry-android#961]
example
lbry://0007787#d91bf8e2e09a21cc9193a9e0fc56b3a89c817bf0
First time going to page,  view increments. Switching out of page and back in does not increment. 
Click download, let it fail / stop it or complete then go back to content list or go to another application. when you switch back to the page the view counter increments. 
Tested on the ebook content and on a video, same method both have the same view count increment.
As the download does not actually need to be completed this would be a really quick way to raise view numbers. 

Also on a side note the ebook download did not go into my phone downloads and I can't open it in lbry app so I am assuming that function is also broken.  

Version
0.15.14
Sdk 0.76
Android 10

**Comment by tzarebczan** [comment]
Thanks for filing the issue. This is expected and something similar can be done on our other platforms if someone wanted to inflate view counts. They don't count for much, so it would be a waste of time anyway.
