### ISSUE TITLE
Setting to not auto-play videos

### ISSUE THREAD

**Issue by kabo** [lbryio/lbry-android#963]
## The Issue

It would be great if there was a setting to not auto-play videos when you go to them, like in the desktop app.

### Steps to reproduce
1. go to a video

### Expected behaviour
The video info to be shown along with a play button

### Actual behaviour
The video starts playing immediately

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing, we've got this under https://github.com/lbryio/lbry-android/issues/844
