### ISSUE TITLE
improve Video Player and add auto-rotate feature

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-android#97]
## The Issue
video player android app for LBRY APP should follow the accelerometer sensor if we play it in full screen mode, it would be nice if this app has this feature and can make user more happy in watching video available in this app, look at youtube app there is this feature.
### Steps to reproduce
1. Play any video in full-screen mode
2. back and forth your device
3. see the video that should follow the accelerometer sensor not working in full screen

## System Configuration
- Device: Lenovo Vibe K4 Note
- Android version: 6.0 Marshmallow

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by akinwale** [comment]
Done.
