### ISSUE TITLE
Reward offer for email verification asks for phone number

### ISSUE THREAD

**Issue by fahrradflucht** [lbryio/lbry-android#970]
## The Issue

After installing the app and logging into my account with my already verified email, I'm offered a reward 27lbry reward for verifying my email, but when I try to proceed it actually asks for a phone number.

### Expected behaviour

I'm unsure what the intended behavior is. Either:
- Don't prompt for the reward
- Prompt for a reward for phone number verification

## System Configuration
- Device: Pixel 4
- Android version: 10
- App Version: 0.15.16

**Comment by kekkyojin** [comment]
LBRY Android version?

**Comment by fahrradflucht** [comment]
> LBRY Android version?

Added

**Comment by fahrradflucht** [comment]
What is the correct behavior? Maybe it's just a translation issue? My phone language is set to German and it says "E-Mail-Adresse", which as you might guess means eMail. If it should say phone number then maybe there is just some translation string off.

**Comment by tzarebczan** [comment]
See lbry.com/faq/rewards for more information.
