### ISSUE TITLE
Audio lag/crackles when locking phone screen

### ISSUE THREAD

**Issue by returntrip** [lbryio/lbry-android#981]
## The Issue

When locking the screen, the audio reproduction will start lagging and crackling

### Steps to reproduce
1. Play anything
2. Lock the screen
3. Audio starts breaking up

### Expected behaviour
The screen should be locking and the audio should still play unaffected

### Actual behaviour
The phone locks but the audio starts breaking up

## System Configuration
- Device: Oneplus 5T
- Android version: 10

## Anything Else
App version 0.16.0
SDK 0.80.0
Platform Android 10 (API 29)

**Comment by tzarebczan** [comment]
If it was related to https://github.com/lbryio/lbry-android/issues/1101, this should be fixed now.
