### ISSUE TITLE
Notification Changes Post Release

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#982]
- [x] Issues with propagation / updating (should be discussed, not sure root problem here)
- [ ] Pull down to refresh
- [ ] Press and hold to mark as read and/or delete (hide)?
- [x] Move to web socket version

**Comment by kauffj** [comment]
- [ ] Mark all as read

**Comment by akinwale** [comment]
We may not need pull down to refresh anymore since the websocket updates in real time.

**Comment by kauffj** [comment]
- [ ] prompt account creation on notifications page for unauth users
