### ISSUE TITLE
 Text for read Notifications is not visible in Dark Theme

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#983]
**DESCRIPTION:**

Text for read Notifications is not visible in Dark Theme.

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.0 on Android 8.1.0
2) Login to an existing account
3) View Notifications and click on one
4) Change to Dark Theme in Settings
5) View the Notification you clicked on

**Results:**  Cannot read text

**Expected:** Text is readable

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.0

-----

**MEDIA:**

![Screenshot_20200821-164102_LBRY](https://user-images.githubusercontent.com/30788194/90962819-236c6d80-e470-11ea-9791-27ec48b6a71e.png)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
@akinwale this is probably a good one to fix for next patch.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/0620582a4eda0313ddb958234feb8fc6434f3bcb. Will be in 0.16.1 patch release.
