### ISSUE TITLE
Moving from Portrait to Landscape by rotating phone cannot be reversed through rotation

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#988]
**DESCRIPTION:**

Moving from Portrait to Landscape by rotating phone cannot be reversed through rotation. The user is forced to interact with the UI to revert back to Portrait mode. 

This is especially frustrating when you accidentally trigger landscape mode by moving your phone, because you can't switch it back simply by correcting your phone's angle. 

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.0 on Android 8.1.0
2) Begin watching a video in Portrait mode
3) Rotate your phone to Landscape
4) Rotate back to Portrait

**Results:**  Video remains in Landscape

**Expected:** Video transitions to Portrait

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.0

-----

**MEDIA:**

![20200822_125303](https://user-images.githubusercontent.com/30788194/90963701-36cf0700-e477-11ea-9ddc-faf87be4257d.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Believe this is a known limitation at this time.

**Comment by kauffj** [comment]
@akinwale says this is intentional and I think it makes sense, once you are in landscape you probably want it to stay that way.
