### ISSUE TITLE
Black Screen when returning to app after dismissing PiP

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#989]
**DESCRIPTION:**

Black Screen when returning to app after dismissing PiP. 

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.0 on Android 8.1.0
2) Begin watching a video
3) Press the Android home button
4) Drag the PiP off bottom of screen
5) Press the Android overview button
6) Select LBRY app

**Results:**  Video is black

**Expected:** Video plays

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.0

-----

**MEDIA:**

![20200822_130355](https://user-images.githubusercontent.com/30788194/90963832-7ba76d80-e478-11ea-919d-77ec1b771642.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by kauffj** [comment]
Thanks @cahlenlee, looking into this one this week (hopefully)

**Comment by akinwale** [comment]
Fixed.
