### ISSUE TITLE
Download shows behind the video whiles playing

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#99]
## The Issue
This was generated when I tried to play a video whiles it's still downloading in landscape mode with full screen. The video seems to overlay the download screen background which isn't suppose to be like that in fullscreen
### Steps to reproduce
1. Try downloading any video and start playing whiles the download is on going
2. Switch to full to fullscreen and you'll see part of the page showing the downloading message
3. I confirmed by reproducing issue about 3 times...

### Expected behavior
The when i full screen mode in the player, the video should fill the complete scree, that's what user wants
and that's why they will switch to full screen

### Actual behaviour
The video seems to overlay the download screen background which showing part of the downloading message.
## System Configuration
- Device: Note 8 Samsung
- Android version: 8.0.0

## Anything Else

https://cdn.discordapp.com/attachments/439055085616496640/441954561163526154/Screenshot_20180504-185553_LBRY_Browser.jpg

https://cdn.discordapp.com/attachments/439055085616496640/441954628826038282/20180504_185940.jpg

https://cdn.discordapp.com/attachments/439055085616496640/441956482070609930/Screenshot_20180504-190629_LBRY_Browser.jpg

**Comment by akinwale** [comment]
Fixed.
