### ISSUE TITLE
Previously watched video plays at 2x speed but displays 1x in UI

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbry-android#992]
**DESCRIPTION:**

Previously watched video plays at 2x speed but displays 1x in UI. 

-----

**REPRO STEPS:**
1) Install and Launch LBRY 0.16.0 on Android 8.1.0
2) Begin watching a video
3) Change speed to 2x
4) Play video to the end
5) Tap the Back button
6) Click the same video you just watched
7) Click the play button

**Results:**  Video plays at 2x but UI says 1x

**Expected:** Playback speed is correctly listed in UI

-----

**ENVIRONMENT:**

- LG V20
- Android 8.1.0
- LBRY 0.16.0

-----

**MEDIA:**

![20200822_134951](https://user-images.githubusercontent.com/30788194/90964560-ecea1f00-e47e-11ea-9589-73c7eb05aef4.gif)

-----

**INTERNAL USE:**

-----

**DEFINITION OF DONE:**
- [ ] Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

-----

**LBRY ADDRESS:**
bZSqrVdpxt5KJdn2eGMUzT9Jn3gEiRet7b
mail@cahlen.org

**Comment by tzarebczan** [comment]
Thanks for filing the issues! Got your email and we'll get some appreciation over.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/lbry-android/commit/c1106d71864f0c140417ae74607d7b80c00c5b18.
