### ISSUE TITLE
Cannot build from source with provided instructions due to missing twitter.properties file.

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-android#997]
## The Issue
Cannot build from source with provided instructions due to missing `twitter.properties` file.
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/clay53/git/github/lbryio/lbry-android/app/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':app'.
> /home/clay53/git/github/lbryio/lbry-android/app/twitter.properties (No such file or directory)
```

### Steps to reproduce
1. Clone source
2. Follow instructions in README.md
3. Error shows

### Expected behaviour
Tell us what should happen
Instructions should provide information on how to fully build the project.

### Actual behaviour
Tell us what happens instead
Instructions do not provide how to get the twitter.properties file.

**Comment by akinwale** [comment]
You can create a `twitter.properties` file in the `app` folder containing the text below. The values don't really matter as they are only required for Twitter sign in verification.
```
twitterConsumerKey=xxx
twitterConsumerSecret=xxx
```

**Comment by clay53** [comment]
The README.md still hasn't been update for this. Is this going to be done soon or should I try to do it?

**Comment by clay53** [comment]
Or should there be changes to the code to allow for building without this file?
